// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("BiomeGenDef", {
  biomeId: __t.u16(),
  name: __t.string(),
  minElevation: __t.i16(),
  maxElevation: __t.i16(),
  moistureMin: __t.i16(),
  moistureMax: __t.i16(),
  resourceBiasPermille: __t.u16(),
});


