// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("DimensionDesc", {
  entityId: __t.u64(),
  dimensionId: __t.u32(),
  networkEntityId: __t.u64(),
  interiorInstanceId: __t.u64(),
  collapseTimestamp: __t.timestamp(),
});


