// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.3 (commit 02449737ca3b29e7e39679fccbef541a50f32094).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import AccountBootstrapReducer from "./account_bootstrap_reducer";
export { AccountBootstrapReducer };
import AckServerCorrectionReducer from "./ack_server_correction_reducer";
export { AckServerCorrectionReducer };
import AgentTickReducer from "./agent_tick_reducer";
export { AgentTickReducer };
import AttackImpactReducer from "./attack_impact_reducer";
export { AttackImpactReducer };
import AttackScheduledReducer from "./attack_scheduled_reducer";
export { AttackScheduledReducer };
import AttackStartReducer from "./attack_start_reducer";
export { AttackStartReducer };
import BuildingAdvanceReducer from "./building_advance_reducer";
export { BuildingAdvanceReducer };
import BuildingDeconstructReducer from "./building_deconstruct_reducer";
export { BuildingDeconstructReducer };
import BuildingNextIdReducer from "./building_next_id_reducer";
export { BuildingNextIdReducer };
import BuildingPlaceReducer from "./building_place_reducer";
export { BuildingPlaceReducer };
import BuildingPlaceFromPreviewReducer from "./building_place_from_preview_reducer";
export { BuildingPlaceFromPreviewReducer };
import BuildingPlaceInDimensionReducer from "./building_place_in_dimension_reducer";
export { BuildingPlaceInDimensionReducer };
import BuildingValidatePreviewReducer from "./building_validate_preview_reducer";
export { BuildingValidatePreviewReducer };
import ChatSendMessageReducer from "./chat_send_message_reducer";
export { ChatSendMessageReducer };
import ClaimExpandReducer from "./claim_expand_reducer";
export { ClaimExpandReducer };
import ClaimNextIdReducer from "./claim_next_id_reducer";
export { ClaimNextIdReducer };
import ClaimTotemPlaceReducer from "./claim_totem_place_reducer";
export { ClaimTotemPlaceReducer };
import DimensionDescNextIdReducer from "./dimension_desc_next_id_reducer";
export { DimensionDescNextIdReducer };
import DimensionNetworkNextIdReducer from "./dimension_network_next_id_reducer";
export { DimensionNetworkNextIdReducer };
import EconomySetParamReducer from "./economy_set_param_reducer";
export { EconomySetParamReducer };
import EnvironmentEffectAgentLoopReducer from "./environment_effect_agent_loop_reducer";
export { EnvironmentEffectAgentLoopReducer };
import GenerateWorldReducer from "./generate_world_reducer";
export { GenerateWorldReducer };
import GenerateWorldFromParamsReducer from "./generate_world_from_params_reducer";
export { GenerateWorldFromParamsReducer };
import GenerateWorldFromParamsInDimensionReducer from "./generate_world_from_params_in_dimension_reducer";
export { GenerateWorldFromParamsInDimensionReducer };
import GenerateWorldInDimensionReducer from "./generate_world_in_dimension_reducer";
export { GenerateWorldInDimensionReducer };
import GuildCreateReducer from "./guild_create_reducer";
export { GuildCreateReducer };
import GuildJoinReducer from "./guild_join_reducer";
export { GuildJoinReducer };
import GuildProjectUpdateReducer from "./guild_project_update_reducer";
export { GuildProjectUpdateReducer };
import GuildSetRoleReducer from "./guild_set_role_reducer";
export { GuildSetRoleReducer };
import HousingChangeEntranceReducer from "./housing_change_entrance_reducer";
export { HousingChangeEntranceReducer };
import HousingCreateReducer from "./housing_create_reducer";
export { HousingCreateReducer };
import HousingEnterReducer from "./housing_enter_reducer";
export { HousingEnterReducer };
import HousingNextIdReducer from "./housing_next_id_reducer";
export { HousingNextIdReducer };
import HousingPropagatePermissionsReducer from "./housing_propagate_permissions_reducer";
export { HousingPropagatePermissionsReducer };
import IdentityConnectedReducer from "./identity_connected_reducer";
export { IdentityConnectedReducer };
import ImportCsvByTypeReducer from "./import_csv_by_type_reducer";
export { ImportCsvByTypeReducer };
import ImportCsvDataReducer from "./import_csv_data_reducer";
export { ImportCsvDataReducer };
import InteriorCollapseRebuildReducer from "./interior_collapse_rebuild_reducer";
export { InteriorCollapseRebuildReducer };
import InteriorMarkEmptyReducer from "./interior_mark_empty_reducer";
export { InteriorMarkEmptyReducer };
import InventoryBootstrapReducer from "./inventory_bootstrap_reducer";
export { InventoryBootstrapReducer };
import ItemStackMoveReducer from "./item_stack_move_reducer";
export { ItemStackMoveReducer };
import LockInventoryContainerReducer from "./lock_inventory_container_reducer";
export { LockInventoryContainerReducer };
import MarketOrderCancelReducer from "./market_order_cancel_reducer";
export { MarketOrderCancelReducer };
import MarketOrderMatchReducer from "./market_order_match_reducer";
export { MarketOrderMatchReducer };
import MarketOrderPlaceReducer from "./market_order_place_reducer";
export { MarketOrderPlaceReducer };
import ModerationApplyActionReducer from "./moderation_apply_action_reducer";
export { ModerationApplyActionReducer };
import MoveToReducer from "./move_to_reducer";
export { MoveToReducer };
import MovementFeedbackCleanupReducer from "./movement_feedback_cleanup_reducer";
export { MovementFeedbackCleanupReducer };
import MovementFeedbackCleanupGlobalReducer from "./movement_feedback_cleanup_global_reducer";
export { MovementFeedbackCleanupGlobalReducer };
import NpcActionResolveReducer from "./npc_action_resolve_reducer";
export { NpcActionResolveReducer };
import NpcAiAgentLoopReducer from "./npc_ai_agent_loop_reducer";
export { NpcAiAgentLoopReducer };
import NpcDialogueRequestReducer from "./npc_dialogue_request_reducer";
export { NpcDialogueRequestReducer };
import NpcQuestReducer from "./npc_quest_reducer";
export { NpcQuestReducer };
import NpcTalkReducer from "./npc_talk_reducer";
export { NpcTalkReducer };
import NpcTradeReducer from "./npc_trade_reducer";
export { NpcTradeReducer };
import PartyCreateReducer from "./party_create_reducer";
export { PartyCreateReducer };
import PartyJoinReducer from "./party_join_reducer";
export { PartyJoinReducer };
import PartyLeaveReducer from "./party_leave_reducer";
export { PartyLeaveReducer };
import PartyTransferLeaderReducer from "./party_transfer_leader_reducer";
export { PartyTransferLeaderReducer };
import PlayerRegenAgentLoopReducer from "./player_regen_agent_loop_reducer";
export { PlayerRegenAgentLoopReducer };
import PruneExpiredPathsReducer from "./prune_expired_paths_reducer";
export { PruneExpiredPathsReducer };
import QuestChainStartReducer from "./quest_chain_start_reducer";
export { QuestChainStartReducer };
import QuestStageCompleteReducer from "./quest_stage_complete_reducer";
export { QuestStageCompleteReducer };
import RegenerateChunksReducer from "./regenerate_chunks_reducer";
export { RegenerateChunksReducer };
import RegenerateChunksInDimensionReducer from "./regenerate_chunks_in_dimension_reducer";
export { RegenerateChunksInDimensionReducer };
import RentSetWhitelistReducer from "./rent_set_whitelist_reducer";
export { RentSetWhitelistReducer };
import ReportReviewReducer from "./report_review_reducer";
export { ReportReviewReducer };
import ReportSubmitReducer from "./report_submit_reducer";
export { ReportSubmitReducer };
import RequestPathReducer from "./request_path_reducer";
export { RequestPathReducer };
import RequestPathInDimensionReducer from "./request_path_in_dimension_reducer";
export { RequestPathInDimensionReducer };
import ResourceRegenAgentLoopReducer from "./resource_regen_agent_loop_reducer";
export { ResourceRegenAgentLoopReducer };
import RoleGrantReducer from "./role_grant_reducer";
export { RoleGrantReducer };
import RoleRevokeReducer from "./role_revoke_reducer";
export { RoleRevokeReducer };
import SeedDataReducer from "./seed_data_reducer";
export { SeedDataReducer };
import SessionCleanupAgentLoopReducer from "./session_cleanup_agent_loop_reducer";
export { SessionCleanupAgentLoopReducer };
import SetActiveDimensionReducer from "./set_active_dimension_reducer";
export { SetActiveDimensionReducer };
import SetNpcAiEnabledReducer from "./set_npc_ai_enabled_reducer";
export { SetNpcAiEnabledReducer };
import SetWorldgenParamsReducer from "./set_worldgen_params_reducer";
export { SetWorldgenParamsReducer };
import SignInReducer from "./sign_in_reducer";
export { SignInReducer };
import SignOutReducer from "./sign_out_reducer";
export { SignOutReducer };
import StartWorldAgentsReducer from "./start_world_agents_reducer";
export { StartWorldAgentsReducer };
import SubmitCombatIntentReducer from "./submit_combat_intent_reducer";
export { SubmitCombatIntentReducer };
import SubmitMotionIntentReducer from "./submit_motion_intent_reducer";
export { SubmitMotionIntentReducer };
import SyncClientFrameReducer from "./sync_client_frame_reducer";
export { SyncClientFrameReducer };
import TaxPolicySetReducer from "./tax_policy_set_reducer";
export { TaxPolicySetReducer };
import TradeAcceptReducer from "./trade_accept_reducer";
export { TradeAcceptReducer };
import TradeItemAddReducer from "./trade_item_add_reducer";
export { TradeItemAddReducer };
import TradeSessionOpenReducer from "./trade_session_open_reducer";
export { TradeSessionOpenReducer };
import UnlockInventoryContainerReducer from "./unlock_inventory_container_reducer";
export { UnlockInventoryContainerReducer };
import UpsertNpcAnchorStateReducer from "./upsert_npc_anchor_state_reducer";
export { UpsertNpcAnchorStateReducer };
import UpsertNpcPopulationDefReducer from "./upsert_npc_population_def_reducer";
export { UpsertNpcPopulationDefReducer };
import UpsertNpcTradeOrderDefReducer from "./upsert_npc_trade_order_def_reducer";
export { UpsertNpcTradeOrderDefReducer };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import AccountRow from "./account_table";
export { AccountRow };
import AccountProfileRow from "./account_profile_table";
export { AccountProfileRow };
import AchievementDefRow from "./achievement_def_table";
export { AchievementDefRow };
import AchievementStateRow from "./achievement_state_table";
export { AchievementStateRow };
import ActionRateViolationRow from "./action_rate_violation_table";
export { ActionRateViolationRow };
import ActionStateRow from "./action_state_table";
export { ActionStateRow };
import AgentRequestRow from "./agent_request_table";
export { AgentRequestRow };
import AgentResultRow from "./agent_result_table";
export { AgentResultRow };
import AntiCheatEventRow from "./anti_cheat_event_table";
export { AntiCheatEventRow };
import AntiCheatParamsRow from "./anti_cheat_params_table";
export { AntiCheatParamsRow };
import AoiStreamV2Row from "./aoi_stream_v_2_table";
export { AoiStreamV2Row };
import AttackOutcomeRow from "./attack_outcome_table";
export { AttackOutcomeRow };
import AttackScheduleStateRow from "./attack_schedule_state_table";
export { AttackScheduleStateRow };
import AuditLogRow from "./audit_log_table";
export { AuditLogRow };
import BalanceParamsRow from "./balance_params_table";
export { BalanceParamsRow };
import BanListRow from "./ban_list_table";
export { BanListRow };
import BiomeGenDefRow from "./biome_gen_def_table";
export { BiomeGenDefRow };
import BuffStateRow from "./buff_state_table";
export { BuffStateRow };
import BuildingDefRow from "./building_def_table";
export { BuildingDefRow };
import BuildingFootprintRow from "./building_footprint_table";
export { BuildingFootprintRow };
import BuildingPreviewFeedbackViewRow from "./building_preview_feedback_view_table";
export { BuildingPreviewFeedbackViewRow };
import BuildingStateRow from "./building_state_table";
export { BuildingStateRow };
import CharacterStatsRow from "./character_stats_table";
export { CharacterStatsRow };
import ChatChannelRow from "./chat_channel_table";
export { ChatChannelRow };
import ChatMessageRow from "./chat_message_table";
export { ChatMessageRow };
import ClaimStateRow from "./claim_state_table";
export { ClaimStateRow };
import ClientFrameV2Row from "./client_frame_v_2_table";
export { ClientFrameV2Row };
import CollisionProxyV2Row from "./collision_proxy_v_2_table";
export { CollisionProxyV2Row };
import CombatActionDefRow from "./combat_action_def_table";
export { CombatActionDefRow };
import CombatHitV2Row from "./combat_hit_v_2_table";
export { CombatHitV2Row };
import CombatIntentV2Row from "./combat_intent_v_2_table";
export { CombatIntentV2Row };
import CombatStateRow from "./combat_state_table";
export { CombatStateRow };
import CurrencyTxnRow from "./currency_txn_table";
export { CurrencyTxnRow };
import DimensionDescRow from "./dimension_desc_table";
export { DimensionDescRow };
import DimensionNetworkRow from "./dimension_network_table";
export { DimensionNetworkRow };
import EconomyMetricRow from "./economy_metric_table";
export { EconomyMetricRow };
import EconomyParamsRow from "./economy_params_table";
export { EconomyParamsRow };
import EntityCoreRow from "./entity_core_table";
export { EntityCoreRow };
import EnvironmentEffectDescRow from "./environment_effect_desc_table";
export { EnvironmentEffectDescRow };
import EnvironmentEffectExposureRow from "./environment_effect_exposure_table";
export { EnvironmentEffectExposureRow };
import EnvironmentEffectLoopTimerRow from "./environment_effect_loop_timer_table";
export { EnvironmentEffectLoopTimerRow };
import EnvironmentEffectStateRow from "./environment_effect_state_table";
export { EnvironmentEffectStateRow };
import EscrowItemRow from "./escrow_item_table";
export { EscrowItemRow };
import FeatureFlagsRow from "./feature_flags_table";
export { FeatureFlagsRow };
import FriendEdgeRow from "./friend_edge_table";
export { FriendEdgeRow };
import GuildMemberRow from "./guild_member_table";
export { GuildMemberRow };
import GuildProjectRow from "./guild_project_table";
export { GuildProjectRow };
import GuildStateRow from "./guild_state_table";
export { GuildStateRow };
import HousingStateRow from "./housing_state_table";
export { HousingStateRow };
import IdLeaseStateRow from "./id_lease_state_table";
export { IdLeaseStateRow };
import InstanceStateRow from "./instance_state_table";
export { InstanceStateRow };
import InteriorCollapseTimerRow from "./interior_collapse_timer_table";
export { InteriorCollapseTimerRow };
import InventoryContainerRow from "./inventory_container_table";
export { InventoryContainerRow };
import InventoryLockRow from "./inventory_lock_table";
export { InventoryLockRow };
import InventorySlotRow from "./inventory_slot_table";
export { InventorySlotRow };
import ItemDefRow from "./item_def_table";
export { ItemDefRow };
import ItemInstanceRow from "./item_instance_table";
export { ItemInstanceRow };
import ItemStackRow from "./item_stack_table";
export { ItemStackRow };
import KnowledgeStateRow from "./knowledge_state_table";
export { KnowledgeStateRow };
import LlmParamsRow from "./llm_params_table";
export { LlmParamsRow };
import MarketFillRow from "./market_fill_table";
export { MarketFillRow };
import MarketOrderRow from "./market_order_table";
export { MarketOrderRow };
import MetricDailyRow from "./metric_daily_table";
export { MetricDailyRow };
import ModerationActionRow from "./moderation_action_table";
export { ModerationActionRow };
import ModerationFlagRow from "./moderation_flag_table";
export { ModerationFlagRow };
import MotionIntentV2Row from "./motion_intent_v_2_table";
export { MotionIntentV2Row };
import MovementActorStateRow from "./movement_actor_state_table";
export { MovementActorStateRow };
import MovementRequestLogRow from "./movement_request_log_table";
export { MovementRequestLogRow };
import MovementViolationRow from "./movement_violation_table";
export { MovementViolationRow };
import NpcActionRequestRow from "./npc_action_request_table";
export { NpcActionRequestRow };
import NpcActionResultRow from "./npc_action_result_table";
export { NpcActionResultRow };
import NpcActionScheduleRow from "./npc_action_schedule_table";
export { NpcActionScheduleRow };
import NpcAiLoopTimerRow from "./npc_ai_loop_timer_table";
export { NpcAiLoopTimerRow };
import NpcAnchorStateRow from "./npc_anchor_state_table";
export { NpcAnchorStateRow };
import NpcConversationSessionRow from "./npc_conversation_session_table";
export { NpcConversationSessionRow };
import NpcConversationTurnRow from "./npc_conversation_turn_table";
export { NpcConversationTurnRow };
import NpcCostMetricsRow from "./npc_cost_metrics_table";
export { NpcCostMetricsRow };
import NpcInteractionLogRow from "./npc_interaction_log_table";
export { NpcInteractionLogRow };
import NpcMemoryLongRow from "./npc_memory_long_table";
export { NpcMemoryLongRow };
import NpcMemoryShortRow from "./npc_memory_short_table";
export { NpcMemoryShortRow };
import NpcPathStateRow from "./npc_path_state_table";
export { NpcPathStateRow };
import NpcPolicyViolationRow from "./npc_policy_violation_table";
export { NpcPolicyViolationRow };
import NpcPopulationDefRow from "./npc_population_def_table";
export { NpcPopulationDefRow };
import NpcRelationRow from "./npc_relation_table";
export { NpcRelationRow };
import NpcResponseCacheRow from "./npc_response_cache_table";
export { NpcResponseCacheRow };
import NpcStateRow from "./npc_state_table";
export { NpcStateRow };
import NpcStateStreamRow from "./npc_state_stream_table";
export { NpcStateStreamRow };
import NpcTradeOrderDefRow from "./npc_trade_order_def_table";
export { NpcTradeOrderDefRow };
import NpcTradeOrderStateRow from "./npc_trade_order_state_table";
export { NpcTradeOrderStateRow };
import OrderFillRow from "./order_fill_table";
export { OrderFillRow };
import ParamChangeLogRow from "./param_change_log_table";
export { ParamChangeLogRow };
import ParamGuardrailRow from "./param_guardrail_table";
export { ParamGuardrailRow };
import PartyMemberRow from "./party_member_table";
export { PartyMemberRow };
import PartyStateRow from "./party_state_table";
export { PartyStateRow };
import PathResultRow from "./path_result_table";
export { PathResultRow };
import PathStepRow from "./path_step_table";
export { PathStepRow };
import PermissionStateRow from "./permission_state_table";
export { PermissionStateRow };
import PhysicsStateV2Row from "./physics_state_v_2_table";
export { PhysicsStateV2Row };
import PlayerInventoryContainerViewRow from "./player_inventory_container_view_table";
export { PlayerInventoryContainerViewRow };
import PlayerInventoryItemViewRow from "./player_inventory_item_view_table";
export { PlayerInventoryItemViewRow };
import PlayerInventorySlotViewRow from "./player_inventory_slot_view_table";
export { PlayerInventorySlotViewRow };
import PlayerMovementFeedbackViewRow from "./player_movement_feedback_view_table";
export { PlayerMovementFeedbackViewRow };
import PlayerRegenLoopTimerRow from "./player_regen_loop_timer_table";
export { PlayerRegenLoopTimerRow };
import PlayerSessionViewRow from "./player_session_view_table";
export { PlayerSessionViewRow };
import PlayerStateRow from "./player_state_table";
export { PlayerStateRow };
import PlayerWalletViewRow from "./player_wallet_view_table";
export { PlayerWalletViewRow };
import PriceIndexRow from "./price_index_table";
export { PriceIndexRow };
import ProjectSiteStateRow from "./project_site_state_table";
export { ProjectSiteStateRow };
import QuestChainDefRow from "./quest_chain_def_table";
export { QuestChainDefRow };
import QuestChainStateRow from "./quest_chain_state_table";
export { QuestChainStateRow };
import QuestStageDefRow from "./quest_stage_def_table";
export { QuestStageDefRow };
import QuestStageStateRow from "./quest_stage_state_table";
export { QuestStageStateRow };
import QuestStateRow from "./quest_state_table";
export { QuestStateRow };
import RateLimitBucketRow from "./rate_limit_bucket_table";
export { RateLimitBucketRow };
import RegionStateRow from "./region_state_table";
export { RegionStateRow };
import RentStateRow from "./rent_state_table";
export { RentStateRow };
import RentWhitelistEntryRow from "./rent_whitelist_entry_table";
export { RentWhitelistEntryRow };
import ReportQueueRow from "./report_queue_table";
export { ReportQueueRow };
import ResourceClumpDefRow from "./resource_clump_def_table";
export { ResourceClumpDefRow };
import ResourceGenDefRow from "./resource_gen_def_table";
export { ResourceGenDefRow };
import ResourceNodeRow from "./resource_node_table";
export { ResourceNodeRow };
import ResourceRegenLoopTimerRow from "./resource_regen_loop_timer_table";
export { ResourceRegenLoopTimerRow };
import ResourceStateRow from "./resource_state_table";
export { ResourceStateRow };
import RoleBindingRow from "./role_binding_table";
export { RoleBindingRow };
import ServerCorrectionV2Row from "./server_correction_v_2_table";
export { ServerCorrectionV2Row };
import SessionCleanupLoopTimerRow from "./session_cleanup_loop_timer_table";
export { SessionCleanupLoopTimerRow };
import SessionStateRow from "./session_state_table";
export { SessionStateRow };
import SkillProgressRow from "./skill_progress_table";
export { SkillProgressRow };
import SocialFeedRow from "./social_feed_table";
export { SocialFeedRow };
import StatusEffectRow from "./status_effect_table";
export { StatusEffectRow };
import TaxPolicyRow from "./tax_policy_table";
export { TaxPolicyRow };
import TerrainChunkRow from "./terrain_chunk_table";
export { TerrainChunkRow };
import TerrainChunkPayloadRow from "./terrain_chunk_payload_table";
export { TerrainChunkPayloadRow };
import TerrainChunkStreamRow from "./terrain_chunk_stream_table";
export { TerrainChunkStreamRow };
import ThreatStateRow from "./threat_state_table";
export { ThreatStateRow };
import TradeOfferRow from "./trade_offer_table";
export { TradeOfferRow };
import TradeSessionRow from "./trade_session_table";
export { TradeSessionRow };
import TransformStateRow from "./transform_state_table";
export { TransformStateRow };
import WalletRow from "./wallet_table";
export { WalletRow };
import WorldGenParamsRow from "./world_gen_params_table";
export { WorldGenParamsRow };

// Import and reexport all types
import Account from "./account_type";
export { Account };
import AccountProfile from "./account_profile_type";
export { AccountProfile };
import AchievementDef from "./achievement_def_type";
export { AchievementDef };
import AchievementState from "./achievement_state_type";
export { AchievementState };
import ActionRateViolation from "./action_rate_violation_type";
export { ActionRateViolation };
import ActionState from "./action_state_type";
export { ActionState };
import AgentRequest from "./agent_request_type";
export { AgentRequest };
import AgentResult from "./agent_result_type";
export { AgentResult };
import AntiCheatEvent from "./anti_cheat_event_type";
export { AntiCheatEvent };
import AntiCheatParams from "./anti_cheat_params_type";
export { AntiCheatParams };
import AoiStreamV2 from "./aoi_stream_v_2_type";
export { AoiStreamV2 };
import AttackOutcome from "./attack_outcome_type";
export { AttackOutcome };
import AttackScheduled from "./attack_scheduled_type";
export { AttackScheduled };
import AuditLog from "./audit_log_type";
export { AuditLog };
import BalanceParams from "./balance_params_type";
export { BalanceParams };
import BanList from "./ban_list_type";
export { BanList };
import BiomeGenDef from "./biome_gen_def_type";
export { BiomeGenDef };
import BuffState from "./buff_state_type";
export { BuffState };
import BuildingDef from "./building_def_type";
export { BuildingDef };
import BuildingFootprint from "./building_footprint_type";
export { BuildingFootprint };
import BuildingPreviewFeedbackView from "./building_preview_feedback_view_type";
export { BuildingPreviewFeedbackView };
import BuildingState from "./building_state_type";
export { BuildingState };
import CharacterStats from "./character_stats_type";
export { CharacterStats };
import ChatChannel from "./chat_channel_type";
export { ChatChannel };
import ChatMessage from "./chat_message_type";
export { ChatMessage };
import ClaimState from "./claim_state_type";
export { ClaimState };
import ClientFrameV2 from "./client_frame_v_2_type";
export { ClientFrameV2 };
import CollisionProxyV2 from "./collision_proxy_v_2_type";
export { CollisionProxyV2 };
import CombatActionDef from "./combat_action_def_type";
export { CombatActionDef };
import CombatHitV2 from "./combat_hit_v_2_type";
export { CombatHitV2 };
import CombatIntentV2 from "./combat_intent_v_2_type";
export { CombatIntentV2 };
import CombatState from "./combat_state_type";
export { CombatState };
import CurrencyTxn from "./currency_txn_type";
export { CurrencyTxn };
import DimensionDesc from "./dimension_desc_type";
export { DimensionDesc };
import DimensionNetwork from "./dimension_network_type";
export { DimensionNetwork };
import EconomyMetric from "./economy_metric_type";
export { EconomyMetric };
import EconomyParams from "./economy_params_type";
export { EconomyParams };
import EntityCore from "./entity_core_type";
export { EntityCore };
import EnvironmentEffectDesc from "./environment_effect_desc_type";
export { EnvironmentEffectDesc };
import EnvironmentEffectExposure from "./environment_effect_exposure_type";
export { EnvironmentEffectExposure };
import EnvironmentEffectLoopTimer from "./environment_effect_loop_timer_type";
export { EnvironmentEffectLoopTimer };
import EnvironmentEffectState from "./environment_effect_state_type";
export { EnvironmentEffectState };
import EscrowItem from "./escrow_item_type";
export { EscrowItem };
import FeatureFlags from "./feature_flags_type";
export { FeatureFlags };
import FriendEdge from "./friend_edge_type";
export { FriendEdge };
import GuildMember from "./guild_member_type";
export { GuildMember };
import GuildProject from "./guild_project_type";
export { GuildProject };
import GuildState from "./guild_state_type";
export { GuildState };
import HousingState from "./housing_state_type";
export { HousingState };
import IdLeaseState from "./id_lease_state_type";
export { IdLeaseState };
import InstanceState from "./instance_state_type";
export { InstanceState };
import InteriorCollapseTimer from "./interior_collapse_timer_type";
export { InteriorCollapseTimer };
import InventoryContainer from "./inventory_container_type";
export { InventoryContainer };
import InventoryLock from "./inventory_lock_type";
export { InventoryLock };
import InventorySlot from "./inventory_slot_type";
export { InventorySlot };
import ItemDef from "./item_def_type";
export { ItemDef };
import ItemInstance from "./item_instance_type";
export { ItemInstance };
import ItemStack from "./item_stack_type";
export { ItemStack };
import KnowledgeState from "./knowledge_state_type";
export { KnowledgeState };
import LlmParams from "./llm_params_type";
export { LlmParams };
import MarketFill from "./market_fill_type";
export { MarketFill };
import MarketOrder from "./market_order_type";
export { MarketOrder };
import MetricDaily from "./metric_daily_type";
export { MetricDaily };
import ModerationAction from "./moderation_action_type";
export { ModerationAction };
import ModerationFlag from "./moderation_flag_type";
export { ModerationFlag };
import MotionIntentV2 from "./motion_intent_v_2_type";
export { MotionIntentV2 };
import MovementActorState from "./movement_actor_state_type";
export { MovementActorState };
import MovementRequestLog from "./movement_request_log_type";
export { MovementRequestLog };
import MovementViolation from "./movement_violation_type";
export { MovementViolation };
import NpcActionRequest from "./npc_action_request_type";
export { NpcActionRequest };
import NpcActionResult from "./npc_action_result_type";
export { NpcActionResult };
import NpcActionSchedule from "./npc_action_schedule_type";
export { NpcActionSchedule };
import NpcAiLoopTimer from "./npc_ai_loop_timer_type";
export { NpcAiLoopTimer };
import NpcAnchorState from "./npc_anchor_state_type";
export { NpcAnchorState };
import NpcConversationSession from "./npc_conversation_session_type";
export { NpcConversationSession };
import NpcConversationTurn from "./npc_conversation_turn_type";
export { NpcConversationTurn };
import NpcCostMetrics from "./npc_cost_metrics_type";
export { NpcCostMetrics };
import NpcInteractionLog from "./npc_interaction_log_type";
export { NpcInteractionLog };
import NpcMemoryLong from "./npc_memory_long_type";
export { NpcMemoryLong };
import NpcMemoryShort from "./npc_memory_short_type";
export { NpcMemoryShort };
import NpcPathState from "./npc_path_state_type";
export { NpcPathState };
import NpcPolicyViolation from "./npc_policy_violation_type";
export { NpcPolicyViolation };
import NpcPopulationDef from "./npc_population_def_type";
export { NpcPopulationDef };
import NpcRelation from "./npc_relation_type";
export { NpcRelation };
import NpcResponseCache from "./npc_response_cache_type";
export { NpcResponseCache };
import NpcState from "./npc_state_type";
export { NpcState };
import NpcStateStream from "./npc_state_stream_type";
export { NpcStateStream };
import NpcTradeOrderDef from "./npc_trade_order_def_type";
export { NpcTradeOrderDef };
import NpcTradeOrderState from "./npc_trade_order_state_type";
export { NpcTradeOrderState };
import OrderFill from "./order_fill_type";
export { OrderFill };
import ParamChangeLog from "./param_change_log_type";
export { ParamChangeLog };
import ParamGuardrail from "./param_guardrail_type";
export { ParamGuardrail };
import PartyMember from "./party_member_type";
export { PartyMember };
import PartyState from "./party_state_type";
export { PartyState };
import PathResult from "./path_result_type";
export { PathResult };
import PathStep from "./path_step_type";
export { PathStep };
import PermissionState from "./permission_state_type";
export { PermissionState };
import PhysicsStateV2 from "./physics_state_v_2_type";
export { PhysicsStateV2 };
import PlayerInventoryContainerView from "./player_inventory_container_view_type";
export { PlayerInventoryContainerView };
import PlayerInventoryItemView from "./player_inventory_item_view_type";
export { PlayerInventoryItemView };
import PlayerInventorySlotView from "./player_inventory_slot_view_type";
export { PlayerInventorySlotView };
import PlayerMovementFeedbackView from "./player_movement_feedback_view_type";
export { PlayerMovementFeedbackView };
import PlayerRegenLoopTimer from "./player_regen_loop_timer_type";
export { PlayerRegenLoopTimer };
import PlayerSessionView from "./player_session_view_type";
export { PlayerSessionView };
import PlayerState from "./player_state_type";
export { PlayerState };
import PlayerWalletView from "./player_wallet_view_type";
export { PlayerWalletView };
import PriceIndex from "./price_index_type";
export { PriceIndex };
import ProjectSiteState from "./project_site_state_type";
export { ProjectSiteState };
import QuestChainDef from "./quest_chain_def_type";
export { QuestChainDef };
import QuestChainState from "./quest_chain_state_type";
export { QuestChainState };
import QuestStageDef from "./quest_stage_def_type";
export { QuestStageDef };
import QuestStageState from "./quest_stage_state_type";
export { QuestStageState };
import QuestState from "./quest_state_type";
export { QuestState };
import RateLimitBucket from "./rate_limit_bucket_type";
export { RateLimitBucket };
import RegionState from "./region_state_type";
export { RegionState };
import RentState from "./rent_state_type";
export { RentState };
import RentWhitelistEntry from "./rent_whitelist_entry_type";
export { RentWhitelistEntry };
import ReportQueue from "./report_queue_type";
export { ReportQueue };
import ResourceClumpDef from "./resource_clump_def_type";
export { ResourceClumpDef };
import ResourceGenDef from "./resource_gen_def_type";
export { ResourceGenDef };
import ResourceNode from "./resource_node_type";
export { ResourceNode };
import ResourceRegenLoopTimer from "./resource_regen_loop_timer_type";
export { ResourceRegenLoopTimer };
import ResourceState from "./resource_state_type";
export { ResourceState };
import RoleBinding from "./role_binding_type";
export { RoleBinding };
import ServerCorrectionV2 from "./server_correction_v_2_type";
export { ServerCorrectionV2 };
import SessionCleanupLoopTimer from "./session_cleanup_loop_timer_type";
export { SessionCleanupLoopTimer };
import SessionState from "./session_state_type";
export { SessionState };
import SkillProgress from "./skill_progress_type";
export { SkillProgress };
import SocialFeed from "./social_feed_type";
export { SocialFeed };
import StatusEffect from "./status_effect_type";
export { StatusEffect };
import TaxPolicy from "./tax_policy_type";
export { TaxPolicy };
import TerrainChunk from "./terrain_chunk_type";
export { TerrainChunk };
import TerrainChunkPayload from "./terrain_chunk_payload_type";
export { TerrainChunkPayload };
import TerrainChunkStream from "./terrain_chunk_stream_type";
export { TerrainChunkStream };
import ThreatState from "./threat_state_type";
export { ThreatState };
import TradeOffer from "./trade_offer_type";
export { TradeOffer };
import TradeSession from "./trade_session_type";
export { TradeSession };
import TransformState from "./transform_state_type";
export { TransformState };
import Wallet from "./wallet_type";
export { Wallet };
import WorldGenParams from "./world_gen_params_type";
export { WorldGenParams };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'account',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'account_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AccountRow),
  __table({
    name: 'account_profile',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'account_profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AccountProfileRow),
  __table({
    name: 'achievement_def',
    indexes: [
      { name: 'achievement_id', algorithm: 'btree', columns: [
        'achievementId',
      ] },
    ],
    constraints: [
      { name: 'achievement_def_achievement_id_key', constraint: 'unique', columns: ['achievementId'] },
    ],
  }, AchievementDefRow),
  __table({
    name: 'achievement_state',
    indexes: [
      { name: 'achievement_key', algorithm: 'btree', columns: [
        'achievementKey',
      ] },
    ],
    constraints: [
      { name: 'achievement_state_achievement_key_key', constraint: 'unique', columns: ['achievementKey'] },
    ],
  }, AchievementStateRow),
  __table({
    name: 'action_rate_violation',
    indexes: [
      { name: 'violation_id', algorithm: 'btree', columns: [
        'violationId',
      ] },
    ],
    constraints: [
      { name: 'action_rate_violation_violation_id_key', constraint: 'unique', columns: ['violationId'] },
    ],
  }, ActionRateViolationRow),
  __table({
    name: 'action_state',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'action_state_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ActionStateRow),
  __table({
    name: 'agent_request',
    indexes: [
      { name: 'request_id', algorithm: 'btree', columns: [
        'requestId',
      ] },
    ],
    constraints: [
      { name: 'agent_request_request_id_key', constraint: 'unique', columns: ['requestId'] },
    ],
  }, AgentRequestRow),
  __table({
    name: 'agent_result',
    indexes: [
      { name: 'result_id', algorithm: 'btree', columns: [
        'resultId',
      ] },
    ],
    constraints: [
      { name: 'agent_result_result_id_key', constraint: 'unique', columns: ['resultId'] },
    ],
  }, AgentResultRow),
  __table({
    name: 'anti_cheat_event',
    indexes: [
      { name: 'event_id', algorithm: 'btree', columns: [
        'eventId',
      ] },
    ],
    constraints: [
      { name: 'anti_cheat_event_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
  }, AntiCheatEventRow),
  __table({
    name: 'anti_cheat_params',
    indexes: [
      { name: 'param_key', algorithm: 'btree', columns: [
        'paramKey',
      ] },
    ],
    constraints: [
      { name: 'anti_cheat_params_param_key_key', constraint: 'unique', columns: ['paramKey'] },
    ],
  }, AntiCheatParamsRow),
  __table({
    name: 'aoi_stream_v2',
    indexes: [
      { name: 'stream_key', algorithm: 'btree', columns: [
        'streamKey',
      ] },
    ],
    constraints: [
      { name: 'aoi_stream_v2_stream_key_key', constraint: 'unique', columns: ['streamKey'] },
    ],
  }, AoiStreamV2Row),
  __table({
    name: 'attack_outcome',
    indexes: [
      { name: 'outcome_id', algorithm: 'btree', columns: [
        'outcomeId',
      ] },
    ],
    constraints: [
      { name: 'attack_outcome_outcome_id_key', constraint: 'unique', columns: ['outcomeId'] },
    ],
  }, AttackOutcomeRow),
  __table({
    name: 'attack_schedule_state',
    indexes: [
      { name: 'request_key', algorithm: 'btree', columns: [
        'requestKey',
      ] },
    ],
    constraints: [
      { name: 'attack_schedule_state_request_key_key', constraint: 'unique', columns: ['requestKey'] },
    ],
  }, AttackScheduleStateRow),
  __table({
    name: 'audit_log',
    indexes: [
      { name: 'audit_id', algorithm: 'btree', columns: [
        'auditId',
      ] },
    ],
    constraints: [
      { name: 'audit_log_audit_id_key', constraint: 'unique', columns: ['auditId'] },
    ],
  }, AuditLogRow),
  __table({
    name: 'balance_params',
    indexes: [
      { name: 'param_key', algorithm: 'btree', columns: [
        'paramKey',
      ] },
    ],
    constraints: [
      { name: 'balance_params_param_key_key', constraint: 'unique', columns: ['paramKey'] },
    ],
  }, BalanceParamsRow),
  __table({
    name: 'ban_list',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'ban_list_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, BanListRow),
  __table({
    name: 'biome_gen_def',
    indexes: [
      { name: 'biome_id', algorithm: 'btree', columns: [
        'biomeId',
      ] },
    ],
    constraints: [
      { name: 'biome_gen_def_biome_id_key', constraint: 'unique', columns: ['biomeId'] },
    ],
  }, BiomeGenDefRow),
  __table({
    name: 'buff_state',
    indexes: [
      { name: 'buff_key', algorithm: 'btree', columns: [
        'buffKey',
      ] },
    ],
    constraints: [
      { name: 'buff_state_buff_key_key', constraint: 'unique', columns: ['buffKey'] },
    ],
  }, BuffStateRow),
  __table({
    name: 'building_def',
    indexes: [
      { name: 'building_def_id', algorithm: 'btree', columns: [
        'buildingDefId',
      ] },
    ],
    constraints: [
      { name: 'building_def_building_def_id_key', constraint: 'unique', columns: ['buildingDefId'] },
    ],
  }, BuildingDefRow),
  __table({
    name: 'building_footprint',
    indexes: [
      { name: 'tile_key', algorithm: 'btree', columns: [
        'tileKey',
      ] },
    ],
    constraints: [
      { name: 'building_footprint_tile_key_key', constraint: 'unique', columns: ['tileKey'] },
    ],
  }, BuildingFootprintRow),
  __table({
    name: 'building_preview_feedback_view',
    indexes: [
      { name: 'request_key', algorithm: 'btree', columns: [
        'requestKey',
      ] },
    ],
    constraints: [
      { name: 'building_preview_feedback_view_request_key_key', constraint: 'unique', columns: ['requestKey'] },
    ],
  }, BuildingPreviewFeedbackViewRow),
  __table({
    name: 'building_state',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'building_state_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, BuildingStateRow),
  __table({
    name: 'character_stats',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'character_stats_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, CharacterStatsRow),
  __table({
    name: 'chat_channel',
    indexes: [
      { name: 'channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
    ],
    constraints: [
      { name: 'chat_channel_channel_id_key', constraint: 'unique', columns: ['channelId'] },
    ],
  }, ChatChannelRow),
  __table({
    name: 'chat_message',
    indexes: [
      { name: 'message_id', algorithm: 'btree', columns: [
        'messageId',
      ] },
    ],
    constraints: [
      { name: 'chat_message_message_id_key', constraint: 'unique', columns: ['messageId'] },
    ],
  }, ChatMessageRow),
  __table({
    name: 'claim_state',
    indexes: [
      { name: 'claim_id', algorithm: 'btree', columns: [
        'claimId',
      ] },
    ],
    constraints: [
      { name: 'claim_state_claim_id_key', constraint: 'unique', columns: ['claimId'] },
    ],
  }, ClaimStateRow),
  __table({
    name: 'client_frame_v2',
    indexes: [
      { name: 'frame_key', algorithm: 'btree', columns: [
        'frameKey',
      ] },
    ],
    constraints: [
      { name: 'client_frame_v2_frame_key_key', constraint: 'unique', columns: ['frameKey'] },
    ],
  }, ClientFrameV2Row),
  __table({
    name: 'collision_proxy_v2',
    indexes: [
      { name: 'proxy_id', algorithm: 'btree', columns: [
        'proxyId',
      ] },
    ],
    constraints: [
      { name: 'collision_proxy_v2_proxy_id_key', constraint: 'unique', columns: ['proxyId'] },
    ],
  }, CollisionProxyV2Row),
  __table({
    name: 'combat_action_def',
    indexes: [
      { name: 'action_def_id', algorithm: 'btree', columns: [
        'actionDefId',
      ] },
    ],
    constraints: [
      { name: 'combat_action_def_action_def_id_key', constraint: 'unique', columns: ['actionDefId'] },
    ],
  }, CombatActionDefRow),
  __table({
    name: 'combat_hit_v2',
    indexes: [
      { name: 'hit_id', algorithm: 'btree', columns: [
        'hitId',
      ] },
    ],
    constraints: [
      { name: 'combat_hit_v2_hit_id_key', constraint: 'unique', columns: ['hitId'] },
    ],
  }, CombatHitV2Row),
  __table({
    name: 'combat_intent_v2',
    indexes: [
      { name: 'intent_id', algorithm: 'btree', columns: [
        'intentId',
      ] },
    ],
    constraints: [
      { name: 'combat_intent_v2_intent_id_key', constraint: 'unique', columns: ['intentId'] },
    ],
  }, CombatIntentV2Row),
  __table({
    name: 'combat_state',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'combat_state_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, CombatStateRow),
  __table({
    name: 'currency_txn',
    indexes: [
      { name: 'txn_id', algorithm: 'btree', columns: [
        'txnId',
      ] },
    ],
    constraints: [
      { name: 'currency_txn_txn_id_key', constraint: 'unique', columns: ['txnId'] },
    ],
  }, CurrencyTxnRow),
  __table({
    name: 'dimension_desc',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'dimension_desc_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, DimensionDescRow),
  __table({
    name: 'dimension_network',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'dimension_network_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, DimensionNetworkRow),
  __table({
    name: 'economy_metric',
    indexes: [
      { name: 'metric_id', algorithm: 'btree', columns: [
        'metricId',
      ] },
    ],
    constraints: [
      { name: 'economy_metric_metric_id_key', constraint: 'unique', columns: ['metricId'] },
    ],
  }, EconomyMetricRow),
  __table({
    name: 'economy_params',
    indexes: [
      { name: 'param_key', algorithm: 'btree', columns: [
        'paramKey',
      ] },
    ],
    constraints: [
      { name: 'economy_params_param_key_key', constraint: 'unique', columns: ['paramKey'] },
    ],
  }, EconomyParamsRow),
  __table({
    name: 'entity_core',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'entity_core_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EntityCoreRow),
  __table({
    name: 'environment_effect_desc',
    indexes: [
      { name: 'effect_id', algorithm: 'btree', columns: [
        'effectId',
      ] },
    ],
    constraints: [
      { name: 'environment_effect_desc_effect_id_key', constraint: 'unique', columns: ['effectId'] },
    ],
  }, EnvironmentEffectDescRow),
  __table({
    name: 'environment_effect_exposure',
    indexes: [
      { name: 'exposure_key', algorithm: 'btree', columns: [
        'exposureKey',
      ] },
    ],
    constraints: [
      { name: 'environment_effect_exposure_exposure_key_key', constraint: 'unique', columns: ['exposureKey'] },
    ],
  }, EnvironmentEffectExposureRow),
  __table({
    name: 'environment_effect_loop_timer',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'environment_effect_loop_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, EnvironmentEffectLoopTimerRow),
  __table({
    name: 'environment_effect_state',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'environment_effect_state_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EnvironmentEffectStateRow),
  __table({
    name: 'escrow_item',
    indexes: [
      { name: 'escrow_key', algorithm: 'btree', columns: [
        'escrowKey',
      ] },
    ],
    constraints: [
      { name: 'escrow_item_escrow_key_key', constraint: 'unique', columns: ['escrowKey'] },
    ],
  }, EscrowItemRow),
  __table({
    name: 'feature_flags',
    indexes: [
      { name: 'flag_key', algorithm: 'btree', columns: [
        'flagKey',
      ] },
    ],
    constraints: [
      { name: 'feature_flags_flag_key_key', constraint: 'unique', columns: ['flagKey'] },
    ],
  }, FeatureFlagsRow),
  __table({
    name: 'friend_edge',
    indexes: [
      { name: 'edge_key', algorithm: 'btree', columns: [
        'edgeKey',
      ] },
    ],
    constraints: [
      { name: 'friend_edge_edge_key_key', constraint: 'unique', columns: ['edgeKey'] },
    ],
  }, FriendEdgeRow),
  __table({
    name: 'guild_member',
    indexes: [
      { name: 'member_key', algorithm: 'btree', columns: [
        'memberKey',
      ] },
    ],
    constraints: [
      { name: 'guild_member_member_key_key', constraint: 'unique', columns: ['memberKey'] },
    ],
  }, GuildMemberRow),
  __table({
    name: 'guild_project',
    indexes: [
      { name: 'project_id', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'guild_project_project_id_key', constraint: 'unique', columns: ['projectId'] },
    ],
  }, GuildProjectRow),
  __table({
    name: 'guild_state',
    indexes: [
      { name: 'guild_id', algorithm: 'btree', columns: [
        'guildId',
      ] },
    ],
    constraints: [
      { name: 'guild_state_guild_id_key', constraint: 'unique', columns: ['guildId'] },
    ],
  }, GuildStateRow),
  __table({
    name: 'housing_state',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'housing_state_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, HousingStateRow),
  __table({
    name: 'id_lease_state',
    indexes: [
      { name: 'lease_key', algorithm: 'btree', columns: [
        'leaseKey',
      ] },
    ],
    constraints: [
      { name: 'id_lease_state_lease_key_key', constraint: 'unique', columns: ['leaseKey'] },
    ],
  }, IdLeaseStateRow),
  __table({
    name: 'instance_state',
    indexes: [
      { name: 'instance_id', algorithm: 'btree', columns: [
        'instanceId',
      ] },
    ],
    constraints: [
      { name: 'instance_state_instance_id_key', constraint: 'unique', columns: ['instanceId'] },
    ],
  }, InstanceStateRow),
  __table({
    name: 'interior_collapse_timer',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'interior_collapse_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, InteriorCollapseTimerRow),
  __table({
    name: 'inventory_container',
    indexes: [
      { name: 'container_id', algorithm: 'btree', columns: [
        'containerId',
      ] },
    ],
    constraints: [
      { name: 'inventory_container_container_id_key', constraint: 'unique', columns: ['containerId'] },
    ],
  }, InventoryContainerRow),
  __table({
    name: 'inventory_lock',
    indexes: [
      { name: 'container_id', algorithm: 'btree', columns: [
        'containerId',
      ] },
    ],
    constraints: [
      { name: 'inventory_lock_container_id_key', constraint: 'unique', columns: ['containerId'] },
    ],
  }, InventoryLockRow),
  __table({
    name: 'inventory_slot',
    indexes: [
      { name: 'slot_key', algorithm: 'btree', columns: [
        'slotKey',
      ] },
    ],
    constraints: [
      { name: 'inventory_slot_slot_key_key', constraint: 'unique', columns: ['slotKey'] },
    ],
  }, InventorySlotRow),
  __table({
    name: 'item_def',
    indexes: [
      { name: 'item_def_id', algorithm: 'btree', columns: [
        'itemDefId',
      ] },
    ],
    constraints: [
      { name: 'item_def_item_def_id_key', constraint: 'unique', columns: ['itemDefId'] },
    ],
  }, ItemDefRow),
  __table({
    name: 'item_instance',
    indexes: [
      { name: 'item_instance_id', algorithm: 'btree', columns: [
        'itemInstanceId',
      ] },
    ],
    constraints: [
      { name: 'item_instance_item_instance_id_key', constraint: 'unique', columns: ['itemInstanceId'] },
    ],
  }, ItemInstanceRow),
  __table({
    name: 'item_stack',
    indexes: [
      { name: 'item_instance_id', algorithm: 'btree', columns: [
        'itemInstanceId',
      ] },
    ],
    constraints: [
      { name: 'item_stack_item_instance_id_key', constraint: 'unique', columns: ['itemInstanceId'] },
    ],
  }, ItemStackRow),
  __table({
    name: 'knowledge_state',
    indexes: [
      { name: 'knowledge_key', algorithm: 'btree', columns: [
        'knowledgeKey',
      ] },
    ],
    constraints: [
      { name: 'knowledge_state_knowledge_key_key', constraint: 'unique', columns: ['knowledgeKey'] },
    ],
  }, KnowledgeStateRow),
  __table({
    name: 'llm_params',
    indexes: [
      { name: 'param_key', algorithm: 'btree', columns: [
        'paramKey',
      ] },
    ],
    constraints: [
      { name: 'llm_params_param_key_key', constraint: 'unique', columns: ['paramKey'] },
    ],
  }, LlmParamsRow),
  __table({
    name: 'market_fill',
    indexes: [
      { name: 'fill_id', algorithm: 'btree', columns: [
        'fillId',
      ] },
    ],
    constraints: [
      { name: 'market_fill_fill_id_key', constraint: 'unique', columns: ['fillId'] },
    ],
  }, MarketFillRow),
  __table({
    name: 'market_order',
    indexes: [
      { name: 'order_id', algorithm: 'btree', columns: [
        'orderId',
      ] },
    ],
    constraints: [
      { name: 'market_order_order_id_key', constraint: 'unique', columns: ['orderId'] },
    ],
  }, MarketOrderRow),
  __table({
    name: 'metric_daily',
    indexes: [
      { name: 'metric_day_key', algorithm: 'btree', columns: [
        'metricDayKey',
      ] },
    ],
    constraints: [
      { name: 'metric_daily_metric_day_key_key', constraint: 'unique', columns: ['metricDayKey'] },
    ],
  }, MetricDailyRow),
  __table({
    name: 'moderation_action',
    indexes: [
      { name: 'action_id', algorithm: 'btree', columns: [
        'actionId',
      ] },
    ],
    constraints: [
      { name: 'moderation_action_action_id_key', constraint: 'unique', columns: ['actionId'] },
    ],
  }, ModerationActionRow),
  __table({
    name: 'moderation_flag',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'moderation_flag_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ModerationFlagRow),
  __table({
    name: 'motion_intent_v2',
    indexes: [
      { name: 'intent_id', algorithm: 'btree', columns: [
        'intentId',
      ] },
    ],
    constraints: [
      { name: 'motion_intent_v2_intent_id_key', constraint: 'unique', columns: ['intentId'] },
    ],
  }, MotionIntentV2Row),
  __table({
    name: 'movement_actor_state',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'movement_actor_state_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, MovementActorStateRow),
  __table({
    name: 'movement_request_log',
    indexes: [
      { name: 'request_key', algorithm: 'btree', columns: [
        'requestKey',
      ] },
    ],
    constraints: [
      { name: 'movement_request_log_request_key_key', constraint: 'unique', columns: ['requestKey'] },
    ],
  }, MovementRequestLogRow),
  __table({
    name: 'movement_violation',
    indexes: [
      { name: 'violation_id', algorithm: 'btree', columns: [
        'violationId',
      ] },
    ],
    constraints: [
      { name: 'movement_violation_violation_id_key', constraint: 'unique', columns: ['violationId'] },
    ],
  }, MovementViolationRow),
  __table({
    name: 'npc_action_request',
    indexes: [
      { name: 'request_id', algorithm: 'btree', columns: [
        'requestId',
      ] },
    ],
    constraints: [
      { name: 'npc_action_request_request_id_key', constraint: 'unique', columns: ['requestId'] },
    ],
  }, NpcActionRequestRow),
  __table({
    name: 'npc_action_result',
    indexes: [
      { name: 'result_id', algorithm: 'btree', columns: [
        'resultId',
      ] },
    ],
    constraints: [
      { name: 'npc_action_result_result_id_key', constraint: 'unique', columns: ['resultId'] },
    ],
  }, NpcActionResultRow),
  __table({
    name: 'npc_action_schedule',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_action_schedule_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcActionScheduleRow),
  __table({
    name: 'npc_ai_loop_timer',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'npc_ai_loop_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, NpcAiLoopTimerRow),
  __table({
    name: 'npc_anchor_state',
    indexes: [
      { name: 'anchor_id', algorithm: 'btree', columns: [
        'anchorId',
      ] },
    ],
    constraints: [
      { name: 'npc_anchor_state_anchor_id_key', constraint: 'unique', columns: ['anchorId'] },
    ],
  }, NpcAnchorStateRow),
  __table({
    name: 'npc_conversation_session',
    indexes: [
      { name: 'session_id', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'npc_conversation_session_session_id_key', constraint: 'unique', columns: ['sessionId'] },
    ],
  }, NpcConversationSessionRow),
  __table({
    name: 'npc_conversation_turn',
    indexes: [
      { name: 'turn_key', algorithm: 'btree', columns: [
        'turnKey',
      ] },
    ],
    constraints: [
      { name: 'npc_conversation_turn_turn_key_key', constraint: 'unique', columns: ['turnKey'] },
    ],
  }, NpcConversationTurnRow),
  __table({
    name: 'npc_cost_metrics',
    indexes: [
      { name: 'metric_id', algorithm: 'btree', columns: [
        'metricId',
      ] },
    ],
    constraints: [
      { name: 'npc_cost_metrics_metric_id_key', constraint: 'unique', columns: ['metricId'] },
    ],
  }, NpcCostMetricsRow),
  __table({
    name: 'npc_interaction_log',
    indexes: [
      { name: 'interaction_key', algorithm: 'btree', columns: [
        'interactionKey',
      ] },
    ],
    constraints: [
      { name: 'npc_interaction_log_interaction_key_key', constraint: 'unique', columns: ['interactionKey'] },
    ],
  }, NpcInteractionLogRow),
  __table({
    name: 'npc_memory_long',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_memory_long_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcMemoryLongRow),
  __table({
    name: 'npc_memory_short',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_memory_short_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcMemoryShortRow),
  __table({
    name: 'npc_path_state',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_path_state_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcPathStateRow),
  __table({
    name: 'npc_policy_violation',
    indexes: [
      { name: 'violation_id', algorithm: 'btree', columns: [
        'violationId',
      ] },
    ],
    constraints: [
      { name: 'npc_policy_violation_violation_id_key', constraint: 'unique', columns: ['violationId'] },
    ],
  }, NpcPolicyViolationRow),
  __table({
    name: 'npc_population_def',
    indexes: [
      { name: 'npc_type', algorithm: 'btree', columns: [
        'npcType',
      ] },
    ],
    constraints: [
      { name: 'npc_population_def_npc_type_key', constraint: 'unique', columns: ['npcType'] },
    ],
  }, NpcPopulationDefRow),
  __table({
    name: 'npc_relation',
    indexes: [
      { name: 'relation_key', algorithm: 'btree', columns: [
        'relationKey',
      ] },
    ],
    constraints: [
      { name: 'npc_relation_relation_key_key', constraint: 'unique', columns: ['relationKey'] },
    ],
  }, NpcRelationRow),
  __table({
    name: 'npc_response_cache',
    indexes: [
      { name: 'cache_key', algorithm: 'btree', columns: [
        'cacheKey',
      ] },
    ],
    constraints: [
      { name: 'npc_response_cache_cache_key_key', constraint: 'unique', columns: ['cacheKey'] },
    ],
  }, NpcResponseCacheRow),
  __table({
    name: 'npc_state',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_state_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcStateRow),
  __table({
    name: 'npc_state_stream',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_state_stream_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, NpcStateStreamRow),
  __table({
    name: 'npc_trade_order_def',
    indexes: [
      { name: 'order_def_id', algorithm: 'btree', columns: [
        'orderDefId',
      ] },
    ],
    constraints: [
      { name: 'npc_trade_order_def_order_def_id_key', constraint: 'unique', columns: ['orderDefId'] },
    ],
  }, NpcTradeOrderDefRow),
  __table({
    name: 'npc_trade_order_state',
    indexes: [
      { name: 'order_key', algorithm: 'btree', columns: [
        'orderKey',
      ] },
    ],
    constraints: [
      { name: 'npc_trade_order_state_order_key_key', constraint: 'unique', columns: ['orderKey'] },
    ],
  }, NpcTradeOrderStateRow),
  __table({
    name: 'order_fill',
    indexes: [
      { name: 'fill_id', algorithm: 'btree', columns: [
        'fillId',
      ] },
    ],
    constraints: [
      { name: 'order_fill_fill_id_key', constraint: 'unique', columns: ['fillId'] },
    ],
  }, OrderFillRow),
  __table({
    name: 'param_change_log',
    indexes: [
      { name: 'change_id', algorithm: 'btree', columns: [
        'changeId',
      ] },
    ],
    constraints: [
      { name: 'param_change_log_change_id_key', constraint: 'unique', columns: ['changeId'] },
    ],
  }, ParamChangeLogRow),
  __table({
    name: 'param_guardrail',
    indexes: [
      { name: 'guardrail_key', algorithm: 'btree', columns: [
        'guardrailKey',
      ] },
    ],
    constraints: [
      { name: 'param_guardrail_guardrail_key_key', constraint: 'unique', columns: ['guardrailKey'] },
    ],
  }, ParamGuardrailRow),
  __table({
    name: 'party_member',
    indexes: [
      { name: 'member_key', algorithm: 'btree', columns: [
        'memberKey',
      ] },
    ],
    constraints: [
      { name: 'party_member_member_key_key', constraint: 'unique', columns: ['memberKey'] },
    ],
  }, PartyMemberRow),
  __table({
    name: 'party_state',
    indexes: [
      { name: 'party_id', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
      { name: 'party_state_party_id_key', constraint: 'unique', columns: ['partyId'] },
    ],
  }, PartyStateRow),
  __table({
    name: 'path_result',
    indexes: [
      { name: 'path_id', algorithm: 'btree', columns: [
        'pathId',
      ] },
    ],
    constraints: [
      { name: 'path_result_path_id_key', constraint: 'unique', columns: ['pathId'] },
    ],
  }, PathResultRow),
  __table({
    name: 'path_step',
    indexes: [
      { name: 'step_key', algorithm: 'btree', columns: [
        'stepKey',
      ] },
    ],
    constraints: [
      { name: 'path_step_step_key_key', constraint: 'unique', columns: ['stepKey'] },
    ],
  }, PathStepRow),
  __table({
    name: 'permission_state',
    indexes: [
      { name: 'permission_key', algorithm: 'btree', columns: [
        'permissionKey',
      ] },
    ],
    constraints: [
      { name: 'permission_state_permission_key_key', constraint: 'unique', columns: ['permissionKey'] },
    ],
  }, PermissionStateRow),
  __table({
    name: 'physics_state_v2',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'physics_state_v2_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PhysicsStateV2Row),
  __table({
    name: 'player_inventory_container_view',
    indexes: [
      { name: 'view_key', algorithm: 'btree', columns: [
        'viewKey',
      ] },
    ],
    constraints: [
      { name: 'player_inventory_container_view_view_key_key', constraint: 'unique', columns: ['viewKey'] },
    ],
  }, PlayerInventoryContainerViewRow),
  __table({
    name: 'player_inventory_item_view',
    indexes: [
      { name: 'item_instance_id', algorithm: 'btree', columns: [
        'itemInstanceId',
      ] },
    ],
    constraints: [
      { name: 'player_inventory_item_view_item_instance_id_key', constraint: 'unique', columns: ['itemInstanceId'] },
    ],
  }, PlayerInventoryItemViewRow),
  __table({
    name: 'player_inventory_slot_view',
    indexes: [
      { name: 'slot_key', algorithm: 'btree', columns: [
        'slotKey',
      ] },
    ],
    constraints: [
      { name: 'player_inventory_slot_view_slot_key_key', constraint: 'unique', columns: ['slotKey'] },
    ],
  }, PlayerInventorySlotViewRow),
  __table({
    name: 'player_movement_feedback_view',
    indexes: [
      { name: 'request_key', algorithm: 'btree', columns: [
        'requestKey',
      ] },
    ],
    constraints: [
      { name: 'player_movement_feedback_view_request_key_key', constraint: 'unique', columns: ['requestKey'] },
    ],
  }, PlayerMovementFeedbackViewRow),
  __table({
    name: 'player_regen_loop_timer',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'player_regen_loop_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, PlayerRegenLoopTimerRow),
  __table({
    name: 'player_session_view',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_session_view_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerSessionViewRow),
  __table({
    name: 'player_state',
    indexes: [
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_state_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, PlayerStateRow),
  __table({
    name: 'player_wallet_view',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_wallet_view_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerWalletViewRow),
  __table({
    name: 'price_index',
    indexes: [
      { name: 'index_key', algorithm: 'btree', columns: [
        'indexKey',
      ] },
    ],
    constraints: [
      { name: 'price_index_index_key_key', constraint: 'unique', columns: ['indexKey'] },
    ],
  }, PriceIndexRow),
  __table({
    name: 'project_site_state',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'project_site_state_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ProjectSiteStateRow),
  __table({
    name: 'quest_chain_def',
    indexes: [
      { name: 'chain_id', algorithm: 'btree', columns: [
        'chainId',
      ] },
    ],
    constraints: [
      { name: 'quest_chain_def_chain_id_key', constraint: 'unique', columns: ['chainId'] },
    ],
  }, QuestChainDefRow),
  __table({
    name: 'quest_chain_state',
    indexes: [
      { name: 'chain_key', algorithm: 'btree', columns: [
        'chainKey',
      ] },
    ],
    constraints: [
      { name: 'quest_chain_state_chain_key_key', constraint: 'unique', columns: ['chainKey'] },
    ],
  }, QuestChainStateRow),
  __table({
    name: 'quest_stage_def',
    indexes: [
      { name: 'stage_id', algorithm: 'btree', columns: [
        'stageId',
      ] },
    ],
    constraints: [
      { name: 'quest_stage_def_stage_id_key', constraint: 'unique', columns: ['stageId'] },
    ],
  }, QuestStageDefRow),
  __table({
    name: 'quest_stage_state',
    indexes: [
      { name: 'stage_key', algorithm: 'btree', columns: [
        'stageKey',
      ] },
    ],
    constraints: [
      { name: 'quest_stage_state_stage_key_key', constraint: 'unique', columns: ['stageKey'] },
    ],
  }, QuestStageStateRow),
  __table({
    name: 'quest_state',
    indexes: [
      { name: 'quest_key', algorithm: 'btree', columns: [
        'questKey',
      ] },
    ],
    constraints: [
      { name: 'quest_state_quest_key_key', constraint: 'unique', columns: ['questKey'] },
    ],
  }, QuestStateRow),
  __table({
    name: 'rate_limit_bucket',
    indexes: [
      { name: 'bucket_key', algorithm: 'btree', columns: [
        'bucketKey',
      ] },
    ],
    constraints: [
      { name: 'rate_limit_bucket_bucket_key_key', constraint: 'unique', columns: ['bucketKey'] },
    ],
  }, RateLimitBucketRow),
  __table({
    name: 'region_state',
    indexes: [
      { name: 'region_id', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'region_state_region_id_key', constraint: 'unique', columns: ['regionId'] },
    ],
  }, RegionStateRow),
  __table({
    name: 'rent_state',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'rent_state_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, RentStateRow),
  __table({
    name: 'rent_whitelist_entry',
    indexes: [
      { name: 'entry_key', algorithm: 'btree', columns: [
        'entryKey',
      ] },
    ],
    constraints: [
      { name: 'rent_whitelist_entry_entry_key_key', constraint: 'unique', columns: ['entryKey'] },
    ],
  }, RentWhitelistEntryRow),
  __table({
    name: 'report_queue',
    indexes: [
      { name: 'report_id', algorithm: 'btree', columns: [
        'reportId',
      ] },
    ],
    constraints: [
      { name: 'report_queue_report_id_key', constraint: 'unique', columns: ['reportId'] },
    ],
  }, ReportQueueRow),
  __table({
    name: 'resource_clump_def',
    indexes: [
      { name: 'clump_key', algorithm: 'btree', columns: [
        'clumpKey',
      ] },
    ],
    constraints: [
      { name: 'resource_clump_def_clump_key_key', constraint: 'unique', columns: ['clumpKey'] },
    ],
  }, ResourceClumpDefRow),
  __table({
    name: 'resource_gen_def',
    indexes: [
      { name: 'resource_type', algorithm: 'btree', columns: [
        'resourceType',
      ] },
    ],
    constraints: [
      { name: 'resource_gen_def_resource_type_key', constraint: 'unique', columns: ['resourceType'] },
    ],
  }, ResourceGenDefRow),
  __table({
    name: 'resource_node',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'resource_node_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ResourceNodeRow),
  __table({
    name: 'resource_regen_loop_timer',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'resource_regen_loop_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ResourceRegenLoopTimerRow),
  __table({
    name: 'resource_state',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'resource_state_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ResourceStateRow),
  __table({
    name: 'role_binding',
    indexes: [
      { name: 'binding_id', algorithm: 'btree', columns: [
        'bindingId',
      ] },
    ],
    constraints: [
      { name: 'role_binding_binding_id_key', constraint: 'unique', columns: ['bindingId'] },
    ],
  }, RoleBindingRow),
  __table({
    name: 'server_correction_v2',
    indexes: [
      { name: 'correction_id', algorithm: 'btree', columns: [
        'correctionId',
      ] },
    ],
    constraints: [
      { name: 'server_correction_v2_correction_id_key', constraint: 'unique', columns: ['correctionId'] },
    ],
  }, ServerCorrectionV2Row),
  __table({
    name: 'session_cleanup_loop_timer',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'session_cleanup_loop_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, SessionCleanupLoopTimerRow),
  __table({
    name: 'session_state',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'session_state_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, SessionStateRow),
  __table({
    name: 'skill_progress',
    indexes: [
      { name: 'skill_key', algorithm: 'btree', columns: [
        'skillKey',
      ] },
    ],
    constraints: [
      { name: 'skill_progress_skill_key_key', constraint: 'unique', columns: ['skillKey'] },
    ],
  }, SkillProgressRow),
  __table({
    name: 'social_feed',
    indexes: [
      { name: 'feed_id', algorithm: 'btree', columns: [
        'feedId',
      ] },
    ],
    constraints: [
      { name: 'social_feed_feed_id_key', constraint: 'unique', columns: ['feedId'] },
    ],
  }, SocialFeedRow),
  __table({
    name: 'status_effect',
    indexes: [
      { name: 'status_key', algorithm: 'btree', columns: [
        'statusKey',
      ] },
    ],
    constraints: [
      { name: 'status_effect_status_key_key', constraint: 'unique', columns: ['statusKey'] },
    ],
  }, StatusEffectRow),
  __table({
    name: 'tax_policy',
    indexes: [
      { name: 'item_def_id', algorithm: 'btree', columns: [
        'itemDefId',
      ] },
    ],
    constraints: [
      { name: 'tax_policy_item_def_id_key', constraint: 'unique', columns: ['itemDefId'] },
    ],
  }, TaxPolicyRow),
  __table({
    name: 'terrain_chunk',
    indexes: [
      { name: 'chunk_key', algorithm: 'btree', columns: [
        'chunkKey',
      ] },
    ],
    constraints: [
      { name: 'terrain_chunk_chunk_key_key', constraint: 'unique', columns: ['chunkKey'] },
    ],
  }, TerrainChunkRow),
  __table({
    name: 'terrain_chunk_payload',
    indexes: [
      { name: 'chunk_key', algorithm: 'btree', columns: [
        'chunkKey',
      ] },
    ],
    constraints: [
      { name: 'terrain_chunk_payload_chunk_key_key', constraint: 'unique', columns: ['chunkKey'] },
    ],
  }, TerrainChunkPayloadRow),
  __table({
    name: 'terrain_chunk_stream',
    indexes: [
      { name: 'chunk_key', algorithm: 'btree', columns: [
        'chunkKey',
      ] },
    ],
    constraints: [
      { name: 'terrain_chunk_stream_chunk_key_key', constraint: 'unique', columns: ['chunkKey'] },
    ],
  }, TerrainChunkStreamRow),
  __table({
    name: 'threat_state',
    indexes: [
      { name: 'threat_key', algorithm: 'btree', columns: [
        'threatKey',
      ] },
    ],
    constraints: [
      { name: 'threat_state_threat_key_key', constraint: 'unique', columns: ['threatKey'] },
    ],
  }, ThreatStateRow),
  __table({
    name: 'trade_offer',
    indexes: [
      { name: 'offer_key', algorithm: 'btree', columns: [
        'offerKey',
      ] },
    ],
    constraints: [
      { name: 'trade_offer_offer_key_key', constraint: 'unique', columns: ['offerKey'] },
    ],
  }, TradeOfferRow),
  __table({
    name: 'trade_session',
    indexes: [
      { name: 'session_id', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'trade_session_session_id_key', constraint: 'unique', columns: ['sessionId'] },
    ],
  }, TradeSessionRow),
  __table({
    name: 'transform_state',
    indexes: [
      { name: 'entity_id', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'transform_state_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, TransformStateRow),
  __table({
    name: 'wallet',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'wallet_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, WalletRow),
  __table({
    name: 'world_gen_params',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_gen_params_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldGenParamsRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("account_bootstrap", AccountBootstrapReducer),
  __reducerSchema("ack_server_correction", AckServerCorrectionReducer),
  __reducerSchema("agent_tick", AgentTickReducer),
  __reducerSchema("attack_impact", AttackImpactReducer),
  __reducerSchema("attack_scheduled", AttackScheduledReducer),
  __reducerSchema("attack_start", AttackStartReducer),
  __reducerSchema("building_advance", BuildingAdvanceReducer),
  __reducerSchema("building_deconstruct", BuildingDeconstructReducer),
  __reducerSchema("building_next_id", BuildingNextIdReducer),
  __reducerSchema("building_place", BuildingPlaceReducer),
  __reducerSchema("building_place_from_preview", BuildingPlaceFromPreviewReducer),
  __reducerSchema("building_place_in_dimension", BuildingPlaceInDimensionReducer),
  __reducerSchema("building_validate_preview", BuildingValidatePreviewReducer),
  __reducerSchema("chat_send_message", ChatSendMessageReducer),
  __reducerSchema("claim_expand", ClaimExpandReducer),
  __reducerSchema("claim_next_id", ClaimNextIdReducer),
  __reducerSchema("claim_totem_place", ClaimTotemPlaceReducer),
  __reducerSchema("dimension_desc_next_id", DimensionDescNextIdReducer),
  __reducerSchema("dimension_network_next_id", DimensionNetworkNextIdReducer),
  __reducerSchema("economy_set_param", EconomySetParamReducer),
  __reducerSchema("environment_effect_agent_loop", EnvironmentEffectAgentLoopReducer),
  __reducerSchema("generate_world", GenerateWorldReducer),
  __reducerSchema("generate_world_from_params", GenerateWorldFromParamsReducer),
  __reducerSchema("generate_world_from_params_in_dimension", GenerateWorldFromParamsInDimensionReducer),
  __reducerSchema("generate_world_in_dimension", GenerateWorldInDimensionReducer),
  __reducerSchema("guild_create", GuildCreateReducer),
  __reducerSchema("guild_join", GuildJoinReducer),
  __reducerSchema("guild_project_update", GuildProjectUpdateReducer),
  __reducerSchema("guild_set_role", GuildSetRoleReducer),
  __reducerSchema("housing_change_entrance", HousingChangeEntranceReducer),
  __reducerSchema("housing_create", HousingCreateReducer),
  __reducerSchema("housing_enter", HousingEnterReducer),
  __reducerSchema("housing_next_id", HousingNextIdReducer),
  __reducerSchema("housing_propagate_permissions", HousingPropagatePermissionsReducer),
  __reducerSchema("import_csv_by_type", ImportCsvByTypeReducer),
  __reducerSchema("import_csv_data", ImportCsvDataReducer),
  __reducerSchema("interior_collapse_rebuild", InteriorCollapseRebuildReducer),
  __reducerSchema("interior_mark_empty", InteriorMarkEmptyReducer),
  __reducerSchema("inventory_bootstrap", InventoryBootstrapReducer),
  __reducerSchema("item_stack_move", ItemStackMoveReducer),
  __reducerSchema("lock_inventory_container", LockInventoryContainerReducer),
  __reducerSchema("market_order_cancel", MarketOrderCancelReducer),
  __reducerSchema("market_order_match", MarketOrderMatchReducer),
  __reducerSchema("market_order_place", MarketOrderPlaceReducer),
  __reducerSchema("moderation_apply_action", ModerationApplyActionReducer),
  __reducerSchema("move_to", MoveToReducer),
  __reducerSchema("movement_feedback_cleanup", MovementFeedbackCleanupReducer),
  __reducerSchema("movement_feedback_cleanup_global", MovementFeedbackCleanupGlobalReducer),
  __reducerSchema("npc_action_resolve", NpcActionResolveReducer),
  __reducerSchema("npc_ai_agent_loop", NpcAiAgentLoopReducer),
  __reducerSchema("npc_dialogue_request", NpcDialogueRequestReducer),
  __reducerSchema("npc_quest", NpcQuestReducer),
  __reducerSchema("npc_talk", NpcTalkReducer),
  __reducerSchema("npc_trade", NpcTradeReducer),
  __reducerSchema("party_create", PartyCreateReducer),
  __reducerSchema("party_join", PartyJoinReducer),
  __reducerSchema("party_leave", PartyLeaveReducer),
  __reducerSchema("party_transfer_leader", PartyTransferLeaderReducer),
  __reducerSchema("player_regen_agent_loop", PlayerRegenAgentLoopReducer),
  __reducerSchema("prune_expired_paths", PruneExpiredPathsReducer),
  __reducerSchema("quest_chain_start", QuestChainStartReducer),
  __reducerSchema("quest_stage_complete", QuestStageCompleteReducer),
  __reducerSchema("regenerate_chunks", RegenerateChunksReducer),
  __reducerSchema("regenerate_chunks_in_dimension", RegenerateChunksInDimensionReducer),
  __reducerSchema("rent_set_whitelist", RentSetWhitelistReducer),
  __reducerSchema("report_review", ReportReviewReducer),
  __reducerSchema("report_submit", ReportSubmitReducer),
  __reducerSchema("request_path", RequestPathReducer),
  __reducerSchema("request_path_in_dimension", RequestPathInDimensionReducer),
  __reducerSchema("resource_regen_agent_loop", ResourceRegenAgentLoopReducer),
  __reducerSchema("role_grant", RoleGrantReducer),
  __reducerSchema("role_revoke", RoleRevokeReducer),
  __reducerSchema("seed_data", SeedDataReducer),
  __reducerSchema("session_cleanup_agent_loop", SessionCleanupAgentLoopReducer),
  __reducerSchema("set_active_dimension", SetActiveDimensionReducer),
  __reducerSchema("set_npc_ai_enabled", SetNpcAiEnabledReducer),
  __reducerSchema("set_worldgen_params", SetWorldgenParamsReducer),
  __reducerSchema("sign_in", SignInReducer),
  __reducerSchema("sign_out", SignOutReducer),
  __reducerSchema("start_world_agents", StartWorldAgentsReducer),
  __reducerSchema("submit_combat_intent", SubmitCombatIntentReducer),
  __reducerSchema("submit_motion_intent", SubmitMotionIntentReducer),
  __reducerSchema("sync_client_frame", SyncClientFrameReducer),
  __reducerSchema("tax_policy_set", TaxPolicySetReducer),
  __reducerSchema("trade_accept", TradeAcceptReducer),
  __reducerSchema("trade_item_add", TradeItemAddReducer),
  __reducerSchema("trade_session_open", TradeSessionOpenReducer),
  __reducerSchema("unlock_inventory_container", UnlockInventoryContainerReducer),
  __reducerSchema("upsert_npc_anchor_state", UpsertNpcAnchorStateReducer),
  __reducerSchema("upsert_npc_population_def", UpsertNpcPopulationDefReducer),
  __reducerSchema("upsert_npc_trade_order_def", UpsertNpcTradeOrderDefReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.11.3" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

