// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  requestKey: __t.string().primaryKey().name("request_key"),
  identity: __t.identity(),
  requestId: __t.string().name("request_id"),
  regionId: __t.u64().name("region_id"),
  clientTsMs: __t.u64().name("client_ts_ms"),
  accepted: __t.bool(),
  processedAt: __t.timestamp().name("processed_at"),
});
