// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  metricId: __t.u64().primaryKey().name("metric_id"),
  npcId: __t.u64().name("npc_id"),
  tokenIn: __t.u32().name("token_in"),
  tokenOut: __t.u32().name("token_out"),
  costMicrounits: __t.u64().name("cost_microunits"),
  createdAt: __t.timestamp().name("created_at"),
});
