// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  correctionId: __t.string().primaryKey().name("correction_id"),
  identity: __t.identity(),
  regionId: __t.u64().name("region_id"),
  dimensionId: __t.u32().name("dimension_id"),
  reason: __t.string(),
  authoritativePosition: __t.array(__t.f32()).name("authoritative_position"),
  authoritativeVelocity: __t.array(__t.f32()).name("authoritative_velocity"),
  createdAt: __t.timestamp().name("created_at"),
  acknowledged: __t.bool(),
  ackedClientFrameNo: __t.u64().name("acked_client_frame_no"),
  ackedAt: __t.timestamp().name("acked_at"),
});
