#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
if REPO_ROOT="$(git -C "$SKILL_DIR" rev-parse --show-toplevel 2>/dev/null)"; then
  :
else
  REPO_ROOT="$(cd "$SKILL_DIR/../../.." && pwd)"
fi

OUT_MD="$SKILL_DIR/references/00-source-index.md"
OUT_TSV="$SKILL_DIR/references/source-index.tsv"

LOCAL_SOURCES=(
  "orillusion/README.md"
  "orillusion/CHANGELOG.md"
  "orillusion/package.json"
  "orillusion/src/Engine3D.ts"
  "orillusion/src/assets/Res.ts"
  "orillusion/src/core/entities/Object3D.ts"
  "orillusion/src/core/entities/Entity.ts"
  "orillusion/src/components/renderer/RenderNode.ts"
  "orillusion/src/setting/EngineSetting.ts"
  "orillusion/src/setting/RenderSetting.ts"
  "orillusion/src/setting/ShadowSetting.ts"
  "orillusion/src/setting/GlobalIlluminationSetting.ts"
  "orillusion/src/setting/PickSetting.ts"
  "orillusion/samples"
  "orillusion/packages/physics/README.md"
  "orillusion/packages/particle/README.md"
  "orillusion/packages/stats/README.md"
  "orillusion/packages/graphic"
  "orillusion/packages/geometry/README.md"
  "orillusion/packages/media-extention/README.md"
  "orillusion-web/package.json"
  "orillusion-web/docs/.vitepress/config.ts"
  "orillusion-web/docs/index.md"
  "orillusion-web/docs/guide"
  "orillusion-web/docs/guide/getting_start/install.md"
  "orillusion-web/docs/guide/getting_start/initialization.md"
  "orillusion-web/docs/guide/core/engine.md"
  "orillusion-web/docs/guide/core/config.md"
  "orillusion-web/docs/guide/core/component.md"
  "orillusion-web/docs/guide/core/object.md"
  "orillusion-web/docs/guide/core/script.md"
  "orillusion-web/docs/guide/graphics/camera.md"
  "orillusion-web/docs/guide/graphics/lighting.md"
  "orillusion-web/docs/guide/graphics/shadow.md"
  "orillusion-web/docs/guide/graphics/materials.md"
  "orillusion-web/docs/guide/graphics/texture.md"
  "orillusion-web/docs/guide/graphics/graphics.md"
  "orillusion-web/docs/guide/resource/Readme.md"
  "orillusion-web/docs/guide/resource/gltf.md"
  "orillusion-web/docs/guide/performance/Readme.md"
  "orillusion-web/docs/guide/advanced/gi.md"
  "orillusion-web/docs/guide/advanced/posteffect.md"
  "orillusion-web/docs/guide/advanced/post_bloom.md"
  "orillusion-web/docs/guide/advanced/post_ssr.md"
  "orillusion-web/docs/guide/advanced/shader/shader_material.md"
  "orillusion-web/docs/guide/advanced/shader/shader_include.md"
  "orillusion-web/docs/guide/advanced/shader/shader_variants.md"
  "orillusion-web/docs/guide/advanced/shader/shader_compute.md"
  "orillusion-web/docs/guide/particle/Readme.md"
  "orillusion-web/docs/guide/physics/Readme.md"
  "orillusion-web/docs/guide/gui/Readme.md"
  "orillusion-web/docs/public/demos"
)

EXTERNAL_SOURCES=(
  "https://www.orillusion.com/guide/"
  "https://www.orillusion.com/zh/webgpu.html"
  "https://www.orillusion.com/zh/wgsl.html"
  "https://www.khronos.org/gltf"
  "https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts"
  "https://www.npmjs.com/package/@orillusion/core"
)

for src in "${LOCAL_SOURCES[@]}"; do
  if [[ ! -e "$REPO_ROOT/$src" ]]; then
    echo "Missing local source: $src" >&2
    exit 1
  fi
done

mkdir -p "$SKILL_DIR/references"

{
  echo -e "type\tpath"
  for src in "${LOCAL_SOURCES[@]}"; do
    echo -e "local\t$src"
  done
  for src in "${EXTERNAL_SOURCES[@]}"; do
    echo -e "external\t$src"
  done
} > "$OUT_TSV"

{
  echo "# Orillusion Source Index"
  echo
  echo 'Generated by `scripts/build_reference_index.sh`.'
  echo
  echo "## Local Sources"
  echo
  echo "| Type | Path |"
  echo "|---|---|"
  for src in "${LOCAL_SOURCES[@]}"; do
    printf '| local | `%s` |\n' "$src"
  done
  echo
  echo "## External Sources"
  echo
  echo "| Type | Link |"
  echo "|---|---|"
  for src in "${EXTERNAL_SOURCES[@]}"; do
    echo "| external | <$src> |"
  done
} > "$OUT_MD"

echo "Generated: $OUT_MD"
echo "Generated: $OUT_TSV"
