// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AccountProfile {
    pub identity: __sdk::Identity,
    pub display_name: String,
    pub avatar_id: u64,
    pub locale: String,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for AccountProfile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AccountProfile`.
///
/// Provides typed access to columns for query building.
pub struct AccountProfileCols {
    pub identity: __sdk::__query_builder::Col<AccountProfile, __sdk::Identity>,
    pub display_name: __sdk::__query_builder::Col<AccountProfile, String>,
    pub avatar_id: __sdk::__query_builder::Col<AccountProfile, u64>,
    pub locale: __sdk::__query_builder::Col<AccountProfile, String>,
    pub updated_at: __sdk::__query_builder::Col<AccountProfile, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AccountProfile {
    type Cols = AccountProfileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountProfileCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            avatar_id: __sdk::__query_builder::Col::new(table_name, "avatar_id"),
            locale: __sdk::__query_builder::Col::new(table_name, "locale"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AccountProfile`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccountProfileIxCols {
    pub identity: __sdk::__query_builder::IxCol<AccountProfile, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for AccountProfile {
    type IxCols = AccountProfileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccountProfileIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AccountProfile {}
