// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AchievementState {
    pub achievement_key: String,
    pub entity_id: u64,
    pub achievement_id: u64,
    pub progress: u32,
    pub completed_at: __sdk::Timestamp,
}

impl __sdk::InModule for AchievementState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AchievementState`.
///
/// Provides typed access to columns for query building.
pub struct AchievementStateCols {
    pub achievement_key: __sdk::__query_builder::Col<AchievementState, String>,
    pub entity_id: __sdk::__query_builder::Col<AchievementState, u64>,
    pub achievement_id: __sdk::__query_builder::Col<AchievementState, u64>,
    pub progress: __sdk::__query_builder::Col<AchievementState, u32>,
    pub completed_at: __sdk::__query_builder::Col<AchievementState, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AchievementState {
    type Cols = AchievementStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AchievementStateCols {
            achievement_key: __sdk::__query_builder::Col::new(table_name, "achievement_key"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            achievement_id: __sdk::__query_builder::Col::new(table_name, "achievement_id"),
            progress: __sdk::__query_builder::Col::new(table_name, "progress"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AchievementState`.
///
/// Provides typed access to indexed columns for query building.
pub struct AchievementStateIxCols {
    pub achievement_key: __sdk::__query_builder::IxCol<AchievementState, String>,
}

impl __sdk::__query_builder::HasIxCols for AchievementState {
    type IxCols = AchievementStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AchievementStateIxCols {
            achievement_key: __sdk::__query_builder::IxCol::new(table_name, "achievement_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AchievementState {}
