// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ActionRateViolation {
    pub violation_id: u64,
    pub identity_hex: String,
    pub action_type: String,
    pub count_in_window: u32,
    pub window_started_at: __sdk::Timestamp,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for ActionRateViolation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ActionRateViolation`.
///
/// Provides typed access to columns for query building.
pub struct ActionRateViolationCols {
    pub violation_id: __sdk::__query_builder::Col<ActionRateViolation, u64>,
    pub identity_hex: __sdk::__query_builder::Col<ActionRateViolation, String>,
    pub action_type: __sdk::__query_builder::Col<ActionRateViolation, String>,
    pub count_in_window: __sdk::__query_builder::Col<ActionRateViolation, u32>,
    pub window_started_at: __sdk::__query_builder::Col<ActionRateViolation, __sdk::Timestamp>,
    pub created_at: __sdk::__query_builder::Col<ActionRateViolation, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ActionRateViolation {
    type Cols = ActionRateViolationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActionRateViolationCols {
            violation_id: __sdk::__query_builder::Col::new(table_name, "violation_id"),
            identity_hex: __sdk::__query_builder::Col::new(table_name, "identity_hex"),
            action_type: __sdk::__query_builder::Col::new(table_name, "action_type"),
            count_in_window: __sdk::__query_builder::Col::new(table_name, "count_in_window"),
            window_started_at: __sdk::__query_builder::Col::new(table_name, "window_started_at"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ActionRateViolation`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActionRateViolationIxCols {
    pub violation_id: __sdk::__query_builder::IxCol<ActionRateViolation, u64>,
}

impl __sdk::__query_builder::HasIxCols for ActionRateViolation {
    type IxCols = ActionRateViolationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActionRateViolationIxCols {
            violation_id: __sdk::__query_builder::IxCol::new(table_name, "violation_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ActionRateViolation {}
