// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AttackStartArgs {
    pub request_id: String,
    pub target_identity: __sdk::Identity,
    pub client_ts_ms: u64,
}

impl From<AttackStartArgs> for super::Reducer {
    fn from(args: AttackStartArgs) -> Self {
        Self::AttackStart {
            request_id: args.request_id,
            target_identity: args.target_identity,
            client_ts_ms: args.client_ts_ms,
        }
    }
}

impl __sdk::InModule for AttackStartArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `attack_start`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait attack_start {
    /// Request that the remote module invoke the reducer `attack_start` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`attack_start:attack_start_then`] to run a callback after the reducer completes.
    fn attack_start(
        &self,
        request_id: String,
        target_identity: __sdk::Identity,
        client_ts_ms: u64,
    ) -> __sdk::Result<()> {
        self.attack_start_then(request_id, target_identity, client_ts_ms, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `attack_start` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn attack_start_then(
        &self,
        request_id: String,
        target_identity: __sdk::Identity,
        client_ts_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl attack_start for super::RemoteReducers {
    fn attack_start_then(
        &self,
        request_id: String,
        target_identity: __sdk::Identity,
        client_ts_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AttackStartArgs {
                request_id,
                target_identity,
                client_ts_ms,
            },
            callback,
        )
    }
}
