// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BanList {
    pub identity: __sdk::Identity,
    pub until_at: __sdk::Timestamp,
    pub reason: String,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for BanList {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BanList`.
///
/// Provides typed access to columns for query building.
pub struct BanListCols {
    pub identity: __sdk::__query_builder::Col<BanList, __sdk::Identity>,
    pub until_at: __sdk::__query_builder::Col<BanList, __sdk::Timestamp>,
    pub reason: __sdk::__query_builder::Col<BanList, String>,
    pub updated_at: __sdk::__query_builder::Col<BanList, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for BanList {
    type Cols = BanListCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BanListCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            until_at: __sdk::__query_builder::Col::new(table_name, "until_at"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `BanList`.
///
/// Provides typed access to indexed columns for query building.
pub struct BanListIxCols {
    pub identity: __sdk::__query_builder::IxCol<BanList, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for BanList {
    type IxCols = BanListIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BanListIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BanList {}
