// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::biome_gen_def_type::BiomeGenDef;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `biome_gen_def`.
///
/// Obtain a handle from the [`BiomeGenDefTableAccess::biome_gen_def`] method on [`super::RemoteTables`],
/// like `ctx.db.biome_gen_def()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.biome_gen_def().on_insert(...)`.
pub struct BiomeGenDefTableHandle<'ctx> {
    imp: __sdk::TableHandle<BiomeGenDef>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `biome_gen_def`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BiomeGenDefTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BiomeGenDefTableHandle`], which mediates access to the table `biome_gen_def`.
    fn biome_gen_def(&self) -> BiomeGenDefTableHandle<'_>;
}

impl BiomeGenDefTableAccess for super::RemoteTables {
    fn biome_gen_def(&self) -> BiomeGenDefTableHandle<'_> {
        BiomeGenDefTableHandle {
            imp: self.imp.get_table::<BiomeGenDef>("biome_gen_def"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BiomeGenDefInsertCallbackId(__sdk::CallbackId);
pub struct BiomeGenDefDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BiomeGenDefTableHandle<'ctx> {
    type Row = BiomeGenDef;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BiomeGenDef> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BiomeGenDefInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BiomeGenDefInsertCallbackId {
        BiomeGenDefInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BiomeGenDefInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BiomeGenDefDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BiomeGenDefDeleteCallbackId {
        BiomeGenDefDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BiomeGenDefDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BiomeGenDefUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BiomeGenDefTableHandle<'ctx> {
    type UpdateCallbackId = BiomeGenDefUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BiomeGenDefUpdateCallbackId {
        BiomeGenDefUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BiomeGenDefUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `biome_id` unique index on the table `biome_gen_def`,
/// which allows point queries on the field of the same name
/// via the [`BiomeGenDefBiomeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.biome_gen_def().biome_id().find(...)`.
pub struct BiomeGenDefBiomeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BiomeGenDef, u16>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BiomeGenDefTableHandle<'ctx> {
    /// Get a handle on the `biome_id` unique index on the table `biome_gen_def`.
    pub fn biome_id(&self) -> BiomeGenDefBiomeIdUnique<'ctx> {
        BiomeGenDefBiomeIdUnique {
            imp: self.imp.get_unique_constraint::<u16>("biome_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BiomeGenDefBiomeIdUnique<'ctx> {
    /// Find the subscribed row whose `biome_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u16) -> Option<BiomeGenDef> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BiomeGenDef>("biome_gen_def");
    _table.add_unique_constraint::<u16>("biome_id", |row| &row.biome_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BiomeGenDef>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BiomeGenDef>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BiomeGenDef`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait biome_gen_defQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BiomeGenDef`.
    fn biome_gen_def(&self) -> __sdk::__query_builder::Table<BiomeGenDef>;
}

impl biome_gen_defQueryTableAccess for __sdk::QueryTableAccessor {
    fn biome_gen_def(&self) -> __sdk::__query_builder::Table<BiomeGenDef> {
        __sdk::__query_builder::Table::new("biome_gen_def")
    }
}
