// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BuffState {
    pub buff_key: String,
    pub entity_id: u64,
    pub buff_id: u64,
    pub stack: u16,
    pub expires_at: __sdk::Timestamp,
}

impl __sdk::InModule for BuffState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BuffState`.
///
/// Provides typed access to columns for query building.
pub struct BuffStateCols {
    pub buff_key: __sdk::__query_builder::Col<BuffState, String>,
    pub entity_id: __sdk::__query_builder::Col<BuffState, u64>,
    pub buff_id: __sdk::__query_builder::Col<BuffState, u64>,
    pub stack: __sdk::__query_builder::Col<BuffState, u16>,
    pub expires_at: __sdk::__query_builder::Col<BuffState, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for BuffState {
    type Cols = BuffStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BuffStateCols {
            buff_key: __sdk::__query_builder::Col::new(table_name, "buff_key"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            buff_id: __sdk::__query_builder::Col::new(table_name, "buff_id"),
            stack: __sdk::__query_builder::Col::new(table_name, "stack"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `BuffState`.
///
/// Provides typed access to indexed columns for query building.
pub struct BuffStateIxCols {
    pub buff_key: __sdk::__query_builder::IxCol<BuffState, String>,
}

impl __sdk::__query_builder::HasIxCols for BuffState {
    type IxCols = BuffStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BuffStateIxCols {
            buff_key: __sdk::__query_builder::IxCol::new(table_name, "buff_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BuffState {}
