// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BuildingDef {
    pub building_def_id: u64,
    pub required_item_def_id: u64,
    pub required_item_qty: u32,
    pub build_required: u32,
    pub footprint_radius: u32,
}

impl __sdk::InModule for BuildingDef {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BuildingDef`.
///
/// Provides typed access to columns for query building.
pub struct BuildingDefCols {
    pub building_def_id: __sdk::__query_builder::Col<BuildingDef, u64>,
    pub required_item_def_id: __sdk::__query_builder::Col<BuildingDef, u64>,
    pub required_item_qty: __sdk::__query_builder::Col<BuildingDef, u32>,
    pub build_required: __sdk::__query_builder::Col<BuildingDef, u32>,
    pub footprint_radius: __sdk::__query_builder::Col<BuildingDef, u32>,
}

impl __sdk::__query_builder::HasCols for BuildingDef {
    type Cols = BuildingDefCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BuildingDefCols {
            building_def_id: __sdk::__query_builder::Col::new(table_name, "building_def_id"),
            required_item_def_id: __sdk::__query_builder::Col::new(
                table_name,
                "required_item_def_id",
            ),
            required_item_qty: __sdk::__query_builder::Col::new(table_name, "required_item_qty"),
            build_required: __sdk::__query_builder::Col::new(table_name, "build_required"),
            footprint_radius: __sdk::__query_builder::Col::new(table_name, "footprint_radius"),
        }
    }
}

/// Indexed column accessor struct for the table `BuildingDef`.
///
/// Provides typed access to indexed columns for query building.
pub struct BuildingDefIxCols {
    pub building_def_id: __sdk::__query_builder::IxCol<BuildingDef, u64>,
}

impl __sdk::__query_builder::HasIxCols for BuildingDef {
    type IxCols = BuildingDefIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BuildingDefIxCols {
            building_def_id: __sdk::__query_builder::IxCol::new(table_name, "building_def_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BuildingDef {}
