// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BuildingAdvanceArgs {
    pub building_id: u64,
    pub steps: u32,
}

impl From<BuildingAdvanceArgs> for super::Reducer {
    fn from(args: BuildingAdvanceArgs) -> Self {
        Self::BuildingAdvance {
            building_id: args.building_id,
            steps: args.steps,
        }
    }
}

impl __sdk::InModule for BuildingAdvanceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `building_advance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait building_advance {
    /// Request that the remote module invoke the reducer `building_advance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`building_advance:building_advance_then`] to run a callback after the reducer completes.
    fn building_advance(&self, building_id: u64, steps: u32) -> __sdk::Result<()> {
        self.building_advance_then(building_id, steps, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `building_advance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn building_advance_then(
        &self,
        building_id: u64,
        steps: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl building_advance for super::RemoteReducers {
    fn building_advance_then(
        &self,
        building_id: u64,
        steps: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(BuildingAdvanceArgs { building_id, steps }, callback)
    }
}
