// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimTotemPlaceArgs {
    pub claim_id: u64,
    pub totem_building_id: u64,
    pub radius: u32,
}

impl From<ClaimTotemPlaceArgs> for super::Reducer {
    fn from(args: ClaimTotemPlaceArgs) -> Self {
        Self::ClaimTotemPlace {
            claim_id: args.claim_id,
            totem_building_id: args.totem_building_id,
            radius: args.radius,
        }
    }
}

impl __sdk::InModule for ClaimTotemPlaceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_totem_place`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_totem_place {
    /// Request that the remote module invoke the reducer `claim_totem_place` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_totem_place:claim_totem_place_then`] to run a callback after the reducer completes.
    fn claim_totem_place(
        &self,
        claim_id: u64,
        totem_building_id: u64,
        radius: u32,
    ) -> __sdk::Result<()> {
        self.claim_totem_place_then(claim_id, totem_building_id, radius, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_totem_place` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_totem_place_then(
        &self,
        claim_id: u64,
        totem_building_id: u64,
        radius: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_totem_place for super::RemoteReducers {
    fn claim_totem_place_then(
        &self,
        claim_id: u64,
        totem_building_id: u64,
        radius: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ClaimTotemPlaceArgs {
                claim_id,
                totem_building_id,
                radius,
            },
            callback,
        )
    }
}
