// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::combat_intent_v_2_type::CombatIntentV2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `combat_intent`.
///
/// Obtain a handle from the [`CombatIntentTableAccess::combat_intent`] method on [`super::RemoteTables`],
/// like `ctx.db.combat_intent()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.combat_intent().on_insert(...)`.
pub struct CombatIntentTableHandle<'ctx> {
    imp: __sdk::TableHandle<CombatIntentV2>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `combat_intent`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CombatIntentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CombatIntentTableHandle`], which mediates access to the table `combat_intent`.
    fn combat_intent(&self) -> CombatIntentTableHandle<'_>;
}

impl CombatIntentTableAccess for super::RemoteTables {
    fn combat_intent(&self) -> CombatIntentTableHandle<'_> {
        CombatIntentTableHandle {
            imp: self.imp.get_table::<CombatIntentV2>("combat_intent"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CombatIntentInsertCallbackId(__sdk::CallbackId);
pub struct CombatIntentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CombatIntentTableHandle<'ctx> {
    type Row = CombatIntentV2;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CombatIntentV2> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CombatIntentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatIntentInsertCallbackId {
        CombatIntentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CombatIntentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CombatIntentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatIntentDeleteCallbackId {
        CombatIntentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CombatIntentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CombatIntentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CombatIntentTableHandle<'ctx> {
    type UpdateCallbackId = CombatIntentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CombatIntentUpdateCallbackId {
        CombatIntentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CombatIntentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `intent_id` unique index on the table `combat_intent`,
/// which allows point queries on the field of the same name
/// via the [`CombatIntentIntentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.combat_intent().intent_id().find(...)`.
pub struct CombatIntentIntentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CombatIntentV2, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CombatIntentTableHandle<'ctx> {
    /// Get a handle on the `intent_id` unique index on the table `combat_intent`.
    pub fn intent_id(&self) -> CombatIntentIntentIdUnique<'ctx> {
        CombatIntentIntentIdUnique {
            imp: self.imp.get_unique_constraint::<String>("intent_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CombatIntentIntentIdUnique<'ctx> {
    /// Find the subscribed row whose `intent_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<CombatIntentV2> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CombatIntentV2>("combat_intent");
    _table.add_unique_constraint::<String>("intent_id", |row| &row.intent_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CombatIntentV2>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CombatIntentV2>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CombatIntentV2`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait combat_intentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CombatIntentV2`.
    fn combat_intent(&self) -> __sdk::__query_builder::Table<CombatIntentV2>;
}

impl combat_intentQueryTableAccess for __sdk::QueryTableAccessor {
    fn combat_intent(&self) -> __sdk::__query_builder::Table<CombatIntentV2> {
        __sdk::__query_builder::Table::new("combat_intent")
    }
}
