// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EconomyParams {
    pub param_key: String,
    pub int_value: i64,
    pub float_value: f64,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for EconomyParams {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EconomyParams`.
///
/// Provides typed access to columns for query building.
pub struct EconomyParamsCols {
    pub param_key: __sdk::__query_builder::Col<EconomyParams, String>,
    pub int_value: __sdk::__query_builder::Col<EconomyParams, i64>,
    pub float_value: __sdk::__query_builder::Col<EconomyParams, f64>,
    pub updated_at: __sdk::__query_builder::Col<EconomyParams, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for EconomyParams {
    type Cols = EconomyParamsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EconomyParamsCols {
            param_key: __sdk::__query_builder::Col::new(table_name, "param_key"),
            int_value: __sdk::__query_builder::Col::new(table_name, "int_value"),
            float_value: __sdk::__query_builder::Col::new(table_name, "float_value"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `EconomyParams`.
///
/// Provides typed access to indexed columns for query building.
pub struct EconomyParamsIxCols {
    pub param_key: __sdk::__query_builder::IxCol<EconomyParams, String>,
}

impl __sdk::__query_builder::HasIxCols for EconomyParams {
    type IxCols = EconomyParamsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EconomyParamsIxCols {
            param_key: __sdk::__query_builder::IxCol::new(table_name, "param_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EconomyParams {}
