// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EntityCore {
    pub entity_id: u64,
    pub entity_type: u8,
    pub region_id: u64,
    pub instance_id: u64,
    pub visibility: u8,
}

impl __sdk::InModule for EntityCore {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EntityCore`.
///
/// Provides typed access to columns for query building.
pub struct EntityCoreCols {
    pub entity_id: __sdk::__query_builder::Col<EntityCore, u64>,
    pub entity_type: __sdk::__query_builder::Col<EntityCore, u8>,
    pub region_id: __sdk::__query_builder::Col<EntityCore, u64>,
    pub instance_id: __sdk::__query_builder::Col<EntityCore, u64>,
    pub visibility: __sdk::__query_builder::Col<EntityCore, u8>,
}

impl __sdk::__query_builder::HasCols for EntityCore {
    type Cols = EntityCoreCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityCoreCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            entity_type: __sdk::__query_builder::Col::new(table_name, "entity_type"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
            visibility: __sdk::__query_builder::Col::new(table_name, "visibility"),
        }
    }
}

/// Indexed column accessor struct for the table `EntityCore`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityCoreIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<EntityCore, u64>,
}

impl __sdk::__query_builder::HasIxCols for EntityCore {
    type IxCols = EntityCoreIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityCoreIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EntityCore {}
