// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_core_type::EntityCore;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `entity_core`.
///
/// Obtain a handle from the [`EntityCoreTableAccess::entity_core`] method on [`super::RemoteTables`],
/// like `ctx.db.entity_core()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_core().on_insert(...)`.
pub struct EntityCoreTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityCore>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `entity_core`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EntityCoreTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EntityCoreTableHandle`], which mediates access to the table `entity_core`.
    fn entity_core(&self) -> EntityCoreTableHandle<'_>;
}

impl EntityCoreTableAccess for super::RemoteTables {
    fn entity_core(&self) -> EntityCoreTableHandle<'_> {
        EntityCoreTableHandle {
            imp: self.imp.get_table::<EntityCore>("entity_core"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EntityCoreInsertCallbackId(__sdk::CallbackId);
pub struct EntityCoreDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EntityCoreTableHandle<'ctx> {
    type Row = EntityCore;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityCore> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EntityCoreInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityCoreInsertCallbackId {
        EntityCoreInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EntityCoreInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EntityCoreDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityCoreDeleteCallbackId {
        EntityCoreDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EntityCoreDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EntityCoreUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EntityCoreTableHandle<'ctx> {
    type UpdateCallbackId = EntityCoreUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EntityCoreUpdateCallbackId {
        EntityCoreUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EntityCoreUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `entity_core`,
/// which allows point queries on the field of the same name
/// via the [`EntityCoreEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_core().entity_id().find(...)`.
pub struct EntityCoreEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EntityCore, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EntityCoreTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `entity_core`.
    pub fn entity_id(&self) -> EntityCoreEntityIdUnique<'ctx> {
        EntityCoreEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EntityCoreEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EntityCore> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityCore>("entity_core");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EntityCore>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityCore>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EntityCore`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait entity_coreQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EntityCore`.
    fn entity_core(&self) -> __sdk::__query_builder::Table<EntityCore>;
}

impl entity_coreQueryTableAccess for __sdk::QueryTableAccessor {
    fn entity_core(&self) -> __sdk::__query_builder::Table<EntityCore> {
        __sdk::__query_builder::Table::new("entity_core")
    }
}
