// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EnvironmentEffectLoopTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub last_run_at: __sdk::Timestamp,
}

impl __sdk::InModule for EnvironmentEffectLoopTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EnvironmentEffectLoopTimer`.
///
/// Provides typed access to columns for query building.
pub struct EnvironmentEffectLoopTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<EnvironmentEffectLoopTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<EnvironmentEffectLoopTimer, __sdk::ScheduleAt>,
    pub last_run_at: __sdk::__query_builder::Col<EnvironmentEffectLoopTimer, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for EnvironmentEffectLoopTimer {
    type Cols = EnvironmentEffectLoopTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EnvironmentEffectLoopTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            last_run_at: __sdk::__query_builder::Col::new(table_name, "last_run_at"),
        }
    }
}

/// Indexed column accessor struct for the table `EnvironmentEffectLoopTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct EnvironmentEffectLoopTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<EnvironmentEffectLoopTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for EnvironmentEffectLoopTimer {
    type IxCols = EnvironmentEffectLoopTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EnvironmentEffectLoopTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EnvironmentEffectLoopTimer {}
