// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FxEventV2 {
    pub event_id: String,
    pub region_id: u64,
    pub dimension_id: u32,
    pub event_type: String,
    pub payload_json: String,
    pub emitted_at: __sdk::Timestamp,
}

impl __sdk::InModule for FxEventV2 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FxEventV2`.
///
/// Provides typed access to columns for query building.
pub struct FxEventV2Cols {
    pub event_id: __sdk::__query_builder::Col<FxEventV2, String>,
    pub region_id: __sdk::__query_builder::Col<FxEventV2, u64>,
    pub dimension_id: __sdk::__query_builder::Col<FxEventV2, u32>,
    pub event_type: __sdk::__query_builder::Col<FxEventV2, String>,
    pub payload_json: __sdk::__query_builder::Col<FxEventV2, String>,
    pub emitted_at: __sdk::__query_builder::Col<FxEventV2, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for FxEventV2 {
    type Cols = FxEventV2Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FxEventV2Cols {
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            dimension_id: __sdk::__query_builder::Col::new(table_name, "dimension_id"),
            event_type: __sdk::__query_builder::Col::new(table_name, "event_type"),
            payload_json: __sdk::__query_builder::Col::new(table_name, "payload_json"),
            emitted_at: __sdk::__query_builder::Col::new(table_name, "emitted_at"),
        }
    }
}

/// Indexed column accessor struct for the table `FxEventV2`.
///
/// Provides typed access to indexed columns for query building.
pub struct FxEventV2IxCols {
    pub event_id: __sdk::__query_builder::IxCol<FxEventV2, String>,
}

impl __sdk::__query_builder::HasIxCols for FxEventV2 {
    type IxCols = FxEventV2IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FxEventV2IxCols {
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for FxEventV2 {}
