// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GenerateWorldArgs {
    pub region_id: u64,
    pub seed: u64,
    pub size_x_chunks: i32,
    pub size_y_chunks: i32,
    pub overwrite: bool,
}

impl From<GenerateWorldArgs> for super::Reducer {
    fn from(args: GenerateWorldArgs) -> Self {
        Self::GenerateWorld {
            region_id: args.region_id,
            seed: args.seed,
            size_x_chunks: args.size_x_chunks,
            size_y_chunks: args.size_y_chunks,
            overwrite: args.overwrite,
        }
    }
}

impl __sdk::InModule for GenerateWorldArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `generate_world`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait generate_world {
    /// Request that the remote module invoke the reducer `generate_world` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`generate_world:generate_world_then`] to run a callback after the reducer completes.
    fn generate_world(
        &self,
        region_id: u64,
        seed: u64,
        size_x_chunks: i32,
        size_y_chunks: i32,
        overwrite: bool,
    ) -> __sdk::Result<()> {
        self.generate_world_then(
            region_id,
            seed,
            size_x_chunks,
            size_y_chunks,
            overwrite,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `generate_world` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn generate_world_then(
        &self,
        region_id: u64,
        seed: u64,
        size_x_chunks: i32,
        size_y_chunks: i32,
        overwrite: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl generate_world for super::RemoteReducers {
    fn generate_world_then(
        &self,
        region_id: u64,
        seed: u64,
        size_x_chunks: i32,
        size_y_chunks: i32,
        overwrite: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GenerateWorldArgs {
                region_id,
                seed,
                size_x_chunks,
                size_y_chunks,
                overwrite,
            },
            callback,
        )
    }
}
