// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::guild_state_type::GuildState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `guild_state`.
///
/// Obtain a handle from the [`GuildStateTableAccess::guild_state`] method on [`super::RemoteTables`],
/// like `ctx.db.guild_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.guild_state().on_insert(...)`.
pub struct GuildStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<GuildState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `guild_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GuildStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GuildStateTableHandle`], which mediates access to the table `guild_state`.
    fn guild_state(&self) -> GuildStateTableHandle<'_>;
}

impl GuildStateTableAccess for super::RemoteTables {
    fn guild_state(&self) -> GuildStateTableHandle<'_> {
        GuildStateTableHandle {
            imp: self.imp.get_table::<GuildState>("guild_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GuildStateInsertCallbackId(__sdk::CallbackId);
pub struct GuildStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GuildStateTableHandle<'ctx> {
    type Row = GuildState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GuildState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GuildStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GuildStateInsertCallbackId {
        GuildStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GuildStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GuildStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GuildStateDeleteCallbackId {
        GuildStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GuildStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GuildStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GuildStateTableHandle<'ctx> {
    type UpdateCallbackId = GuildStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GuildStateUpdateCallbackId {
        GuildStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GuildStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `guild_id` unique index on the table `guild_state`,
/// which allows point queries on the field of the same name
/// via the [`GuildStateGuildIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.guild_state().guild_id().find(...)`.
pub struct GuildStateGuildIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GuildState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GuildStateTableHandle<'ctx> {
    /// Get a handle on the `guild_id` unique index on the table `guild_state`.
    pub fn guild_id(&self) -> GuildStateGuildIdUnique<'ctx> {
        GuildStateGuildIdUnique {
            imp: self.imp.get_unique_constraint::<String>("guild_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GuildStateGuildIdUnique<'ctx> {
    /// Find the subscribed row whose `guild_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<GuildState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GuildState>("guild_state");
    _table.add_unique_constraint::<String>("guild_id", |row| &row.guild_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GuildState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GuildState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GuildState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait guild_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GuildState`.
    fn guild_state(&self) -> __sdk::__query_builder::Table<GuildState>;
}

impl guild_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn guild_state(&self) -> __sdk::__query_builder::Table<GuildState> {
        __sdk::__query_builder::Table::new("guild_state")
    }
}
