// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GuildProjectUpdateArgs {
    pub guild_id: String,
    pub project_id: String,
    pub title: String,
    pub progress_permille: u16,
}

impl From<GuildProjectUpdateArgs> for super::Reducer {
    fn from(args: GuildProjectUpdateArgs) -> Self {
        Self::GuildProjectUpdate {
            guild_id: args.guild_id,
            project_id: args.project_id,
            title: args.title,
            progress_permille: args.progress_permille,
        }
    }
}

impl __sdk::InModule for GuildProjectUpdateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `guild_project_update`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait guild_project_update {
    /// Request that the remote module invoke the reducer `guild_project_update` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`guild_project_update:guild_project_update_then`] to run a callback after the reducer completes.
    fn guild_project_update(
        &self,
        guild_id: String,
        project_id: String,
        title: String,
        progress_permille: u16,
    ) -> __sdk::Result<()> {
        self.guild_project_update_then(guild_id, project_id, title, progress_permille, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `guild_project_update` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn guild_project_update_then(
        &self,
        guild_id: String,
        project_id: String,
        title: String,
        progress_permille: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl guild_project_update for super::RemoteReducers {
    fn guild_project_update_then(
        &self,
        guild_id: String,
        project_id: String,
        title: String,
        progress_permille: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GuildProjectUpdateArgs {
                guild_id,
                project_id,
                title,
                progress_permille,
            },
            callback,
        )
    }
}
