// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HarvestResourceArgs {
    pub entity_id: u64,
    pub requested_amount: u32,
}

impl From<HarvestResourceArgs> for super::Reducer {
    fn from(args: HarvestResourceArgs) -> Self {
        Self::HarvestResource {
            entity_id: args.entity_id,
            requested_amount: args.requested_amount,
        }
    }
}

impl __sdk::InModule for HarvestResourceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `harvest_resource`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait harvest_resource {
    /// Request that the remote module invoke the reducer `harvest_resource` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`harvest_resource:harvest_resource_then`] to run a callback after the reducer completes.
    fn harvest_resource(&self, entity_id: u64, requested_amount: u32) -> __sdk::Result<()> {
        self.harvest_resource_then(entity_id, requested_amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `harvest_resource` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn harvest_resource_then(
        &self,
        entity_id: u64,
        requested_amount: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl harvest_resource for super::RemoteReducers {
    fn harvest_resource_then(
        &self,
        entity_id: u64,
        requested_amount: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            HarvestResourceArgs {
                entity_id,
                requested_amount,
            },
            callback,
        )
    }
}
