// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HousingCreateArgs {
    pub housing_entity_id: u64,
    pub entrance_building_entity_id: u64,
    pub network_entity_id: u64,
    pub dimension_entity_id: u64,
    pub dimension_id: u32,
    pub interior_instance_id: u64,
}

impl From<HousingCreateArgs> for super::Reducer {
    fn from(args: HousingCreateArgs) -> Self {
        Self::HousingCreate {
            housing_entity_id: args.housing_entity_id,
            entrance_building_entity_id: args.entrance_building_entity_id,
            network_entity_id: args.network_entity_id,
            dimension_entity_id: args.dimension_entity_id,
            dimension_id: args.dimension_id,
            interior_instance_id: args.interior_instance_id,
        }
    }
}

impl __sdk::InModule for HousingCreateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `housing_create`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait housing_create {
    /// Request that the remote module invoke the reducer `housing_create` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`housing_create:housing_create_then`] to run a callback after the reducer completes.
    fn housing_create(
        &self,
        housing_entity_id: u64,
        entrance_building_entity_id: u64,
        network_entity_id: u64,
        dimension_entity_id: u64,
        dimension_id: u32,
        interior_instance_id: u64,
    ) -> __sdk::Result<()> {
        self.housing_create_then(
            housing_entity_id,
            entrance_building_entity_id,
            network_entity_id,
            dimension_entity_id,
            dimension_id,
            interior_instance_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `housing_create` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn housing_create_then(
        &self,
        housing_entity_id: u64,
        entrance_building_entity_id: u64,
        network_entity_id: u64,
        dimension_entity_id: u64,
        dimension_id: u32,
        interior_instance_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl housing_create for super::RemoteReducers {
    fn housing_create_then(
        &self,
        housing_entity_id: u64,
        entrance_building_entity_id: u64,
        network_entity_id: u64,
        dimension_entity_id: u64,
        dimension_id: u32,
        interior_instance_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            HousingCreateArgs {
                housing_entity_id,
                entrance_building_entity_id,
                network_entity_id,
                dimension_entity_id,
                dimension_id,
                interior_instance_id,
            },
            callback,
        )
    }
}
