// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InventorySlot {
    pub slot_key: String,
    pub container_id: u64,
    pub slot_index: u32,
    pub item_instance_id: u64,
    pub volume: i32,
    pub locked: bool,
    pub item_type: u8,
}

impl __sdk::InModule for InventorySlot {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InventorySlot`.
///
/// Provides typed access to columns for query building.
pub struct InventorySlotCols {
    pub slot_key: __sdk::__query_builder::Col<InventorySlot, String>,
    pub container_id: __sdk::__query_builder::Col<InventorySlot, u64>,
    pub slot_index: __sdk::__query_builder::Col<InventorySlot, u32>,
    pub item_instance_id: __sdk::__query_builder::Col<InventorySlot, u64>,
    pub volume: __sdk::__query_builder::Col<InventorySlot, i32>,
    pub locked: __sdk::__query_builder::Col<InventorySlot, bool>,
    pub item_type: __sdk::__query_builder::Col<InventorySlot, u8>,
}

impl __sdk::__query_builder::HasCols for InventorySlot {
    type Cols = InventorySlotCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InventorySlotCols {
            slot_key: __sdk::__query_builder::Col::new(table_name, "slot_key"),
            container_id: __sdk::__query_builder::Col::new(table_name, "container_id"),
            slot_index: __sdk::__query_builder::Col::new(table_name, "slot_index"),
            item_instance_id: __sdk::__query_builder::Col::new(table_name, "item_instance_id"),
            volume: __sdk::__query_builder::Col::new(table_name, "volume"),
            locked: __sdk::__query_builder::Col::new(table_name, "locked"),
            item_type: __sdk::__query_builder::Col::new(table_name, "item_type"),
        }
    }
}

/// Indexed column accessor struct for the table `InventorySlot`.
///
/// Provides typed access to indexed columns for query building.
pub struct InventorySlotIxCols {
    pub slot_key: __sdk::__query_builder::IxCol<InventorySlot, String>,
}

impl __sdk::__query_builder::HasIxCols for InventorySlot {
    type IxCols = InventorySlotIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InventorySlotIxCols {
            slot_key: __sdk::__query_builder::IxCol::new(table_name, "slot_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InventorySlot {}
