// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::item_def_type::ItemDef;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `item_def`.
///
/// Obtain a handle from the [`ItemDefTableAccess::item_def`] method on [`super::RemoteTables`],
/// like `ctx.db.item_def()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_def().on_insert(...)`.
pub struct ItemDefTableHandle<'ctx> {
    imp: __sdk::TableHandle<ItemDef>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `item_def`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ItemDefTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ItemDefTableHandle`], which mediates access to the table `item_def`.
    fn item_def(&self) -> ItemDefTableHandle<'_>;
}

impl ItemDefTableAccess for super::RemoteTables {
    fn item_def(&self) -> ItemDefTableHandle<'_> {
        ItemDefTableHandle {
            imp: self.imp.get_table::<ItemDef>("item_def"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ItemDefInsertCallbackId(__sdk::CallbackId);
pub struct ItemDefDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ItemDefTableHandle<'ctx> {
    type Row = ItemDef;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ItemDef> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ItemDefInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemDefInsertCallbackId {
        ItemDefInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ItemDefInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ItemDefDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemDefDeleteCallbackId {
        ItemDefDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ItemDefDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ItemDefUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ItemDefTableHandle<'ctx> {
    type UpdateCallbackId = ItemDefUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ItemDefUpdateCallbackId {
        ItemDefUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ItemDefUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `item_def_id` unique index on the table `item_def`,
/// which allows point queries on the field of the same name
/// via the [`ItemDefItemDefIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_def().item_def_id().find(...)`.
pub struct ItemDefItemDefIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ItemDef, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ItemDefTableHandle<'ctx> {
    /// Get a handle on the `item_def_id` unique index on the table `item_def`.
    pub fn item_def_id(&self) -> ItemDefItemDefIdUnique<'ctx> {
        ItemDefItemDefIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("item_def_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ItemDefItemDefIdUnique<'ctx> {
    /// Find the subscribed row whose `item_def_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ItemDef> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ItemDef>("item_def");
    _table.add_unique_constraint::<u64>("item_def_id", |row| &row.item_def_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ItemDef>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ItemDef>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ItemDef`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait item_defQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ItemDef`.
    fn item_def(&self) -> __sdk::__query_builder::Table<ItemDef>;
}

impl item_defQueryTableAccess for __sdk::QueryTableAccessor {
    fn item_def(&self) -> __sdk::__query_builder::Table<ItemDef> {
        __sdk::__query_builder::Table::new("item_def")
    }
}
