// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LockInventoryContainerArgs {
    pub container_id: u64,
    pub reason: String,
}

impl From<LockInventoryContainerArgs> for super::Reducer {
    fn from(args: LockInventoryContainerArgs) -> Self {
        Self::LockInventoryContainer {
            container_id: args.container_id,
            reason: args.reason,
        }
    }
}

impl __sdk::InModule for LockInventoryContainerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `lock_inventory_container`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait lock_inventory_container {
    /// Request that the remote module invoke the reducer `lock_inventory_container` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`lock_inventory_container:lock_inventory_container_then`] to run a callback after the reducer completes.
    fn lock_inventory_container(&self, container_id: u64, reason: String) -> __sdk::Result<()> {
        self.lock_inventory_container_then(container_id, reason, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `lock_inventory_container` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn lock_inventory_container_then(
        &self,
        container_id: u64,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl lock_inventory_container for super::RemoteReducers {
    fn lock_inventory_container_then(
        &self,
        container_id: u64,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            LockInventoryContainerArgs {
                container_id,
                reason,
            },
            callback,
        )
    }
}
