// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MarketFill {
    pub fill_id: String,
    pub buy_order_id: String,
    pub sell_order_id: String,
    pub item_def_id: u64,
    pub quantity: u32,
    pub unit_price: u64,
    pub buyer_identity: __sdk::Identity,
    pub seller_identity: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for MarketFill {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MarketFill`.
///
/// Provides typed access to columns for query building.
pub struct MarketFillCols {
    pub fill_id: __sdk::__query_builder::Col<MarketFill, String>,
    pub buy_order_id: __sdk::__query_builder::Col<MarketFill, String>,
    pub sell_order_id: __sdk::__query_builder::Col<MarketFill, String>,
    pub item_def_id: __sdk::__query_builder::Col<MarketFill, u64>,
    pub quantity: __sdk::__query_builder::Col<MarketFill, u32>,
    pub unit_price: __sdk::__query_builder::Col<MarketFill, u64>,
    pub buyer_identity: __sdk::__query_builder::Col<MarketFill, __sdk::Identity>,
    pub seller_identity: __sdk::__query_builder::Col<MarketFill, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<MarketFill, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for MarketFill {
    type Cols = MarketFillCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MarketFillCols {
            fill_id: __sdk::__query_builder::Col::new(table_name, "fill_id"),
            buy_order_id: __sdk::__query_builder::Col::new(table_name, "buy_order_id"),
            sell_order_id: __sdk::__query_builder::Col::new(table_name, "sell_order_id"),
            item_def_id: __sdk::__query_builder::Col::new(table_name, "item_def_id"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            unit_price: __sdk::__query_builder::Col::new(table_name, "unit_price"),
            buyer_identity: __sdk::__query_builder::Col::new(table_name, "buyer_identity"),
            seller_identity: __sdk::__query_builder::Col::new(table_name, "seller_identity"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `MarketFill`.
///
/// Provides typed access to indexed columns for query building.
pub struct MarketFillIxCols {
    pub fill_id: __sdk::__query_builder::IxCol<MarketFill, String>,
}

impl __sdk::__query_builder::HasIxCols for MarketFill {
    type IxCols = MarketFillIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MarketFillIxCols {
            fill_id: __sdk::__query_builder::IxCol::new(table_name, "fill_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MarketFill {}
