// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ModerationFlag {
    pub identity: __sdk::Identity,
    pub score: i32,
    pub last_reason: String,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for ModerationFlag {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ModerationFlag`.
///
/// Provides typed access to columns for query building.
pub struct ModerationFlagCols {
    pub identity: __sdk::__query_builder::Col<ModerationFlag, __sdk::Identity>,
    pub score: __sdk::__query_builder::Col<ModerationFlag, i32>,
    pub last_reason: __sdk::__query_builder::Col<ModerationFlag, String>,
    pub updated_at: __sdk::__query_builder::Col<ModerationFlag, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ModerationFlag {
    type Cols = ModerationFlagCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ModerationFlagCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            score: __sdk::__query_builder::Col::new(table_name, "score"),
            last_reason: __sdk::__query_builder::Col::new(table_name, "last_reason"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ModerationFlag`.
///
/// Provides typed access to indexed columns for query building.
pub struct ModerationFlagIxCols {
    pub identity: __sdk::__query_builder::IxCol<ModerationFlag, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ModerationFlag {
    type IxCols = ModerationFlagIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ModerationFlagIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ModerationFlag {}
