// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MotionIntentV2 {
    pub intent_id: String,
    pub identity: __sdk::Identity,
    pub region_id: u64,
    pub dimension_id: u32,
    pub frame_no: u64,
    pub input_x: f32,
    pub input_z: f32,
    pub requested_speed: f32,
    pub jump: bool,
    pub submitted_at: __sdk::Timestamp,
}

impl __sdk::InModule for MotionIntentV2 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MotionIntentV2`.
///
/// Provides typed access to columns for query building.
pub struct MotionIntentV2Cols {
    pub intent_id: __sdk::__query_builder::Col<MotionIntentV2, String>,
    pub identity: __sdk::__query_builder::Col<MotionIntentV2, __sdk::Identity>,
    pub region_id: __sdk::__query_builder::Col<MotionIntentV2, u64>,
    pub dimension_id: __sdk::__query_builder::Col<MotionIntentV2, u32>,
    pub frame_no: __sdk::__query_builder::Col<MotionIntentV2, u64>,
    pub input_x: __sdk::__query_builder::Col<MotionIntentV2, f32>,
    pub input_z: __sdk::__query_builder::Col<MotionIntentV2, f32>,
    pub requested_speed: __sdk::__query_builder::Col<MotionIntentV2, f32>,
    pub jump: __sdk::__query_builder::Col<MotionIntentV2, bool>,
    pub submitted_at: __sdk::__query_builder::Col<MotionIntentV2, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for MotionIntentV2 {
    type Cols = MotionIntentV2Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MotionIntentV2Cols {
            intent_id: __sdk::__query_builder::Col::new(table_name, "intent_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            dimension_id: __sdk::__query_builder::Col::new(table_name, "dimension_id"),
            frame_no: __sdk::__query_builder::Col::new(table_name, "frame_no"),
            input_x: __sdk::__query_builder::Col::new(table_name, "input_x"),
            input_z: __sdk::__query_builder::Col::new(table_name, "input_z"),
            requested_speed: __sdk::__query_builder::Col::new(table_name, "requested_speed"),
            jump: __sdk::__query_builder::Col::new(table_name, "jump"),
            submitted_at: __sdk::__query_builder::Col::new(table_name, "submitted_at"),
        }
    }
}

/// Indexed column accessor struct for the table `MotionIntentV2`.
///
/// Provides typed access to indexed columns for query building.
pub struct MotionIntentV2IxCols {
    pub intent_id: __sdk::__query_builder::IxCol<MotionIntentV2, String>,
}

impl __sdk::__query_builder::HasIxCols for MotionIntentV2 {
    type IxCols = MotionIntentV2IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MotionIntentV2IxCols {
            intent_id: __sdk::__query_builder::IxCol::new(table_name, "intent_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MotionIntentV2 {}
