// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct NpcTradeArgs {
    pub npc_id: u64,
    pub request_id: String,
}

impl From<NpcTradeArgs> for super::Reducer {
    fn from(args: NpcTradeArgs) -> Self {
        Self::NpcTrade {
            npc_id: args.npc_id,
            request_id: args.request_id,
        }
    }
}

impl __sdk::InModule for NpcTradeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `npc_trade`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait npc_trade {
    /// Request that the remote module invoke the reducer `npc_trade` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`npc_trade:npc_trade_then`] to run a callback after the reducer completes.
    fn npc_trade(&self, npc_id: u64, request_id: String) -> __sdk::Result<()> {
        self.npc_trade_then(npc_id, request_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `npc_trade` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn npc_trade_then(
        &self,
        npc_id: u64,
        request_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl npc_trade for super::RemoteReducers {
    fn npc_trade_then(
        &self,
        npc_id: u64,
        request_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(NpcTradeArgs { npc_id, request_id }, callback)
    }
}
