// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcMemoryShort {
    pub npc_id: u64,
    pub summary: String,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for NpcMemoryShort {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcMemoryShort`.
///
/// Provides typed access to columns for query building.
pub struct NpcMemoryShortCols {
    pub npc_id: __sdk::__query_builder::Col<NpcMemoryShort, u64>,
    pub summary: __sdk::__query_builder::Col<NpcMemoryShort, String>,
    pub updated_at: __sdk::__query_builder::Col<NpcMemoryShort, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for NpcMemoryShort {
    type Cols = NpcMemoryShortCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcMemoryShortCols {
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            summary: __sdk::__query_builder::Col::new(table_name, "summary"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcMemoryShort`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcMemoryShortIxCols {
    pub npc_id: __sdk::__query_builder::IxCol<NpcMemoryShort, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcMemoryShort {
    type IxCols = NpcMemoryShortIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcMemoryShortIxCols {
            npc_id: __sdk::__query_builder::IxCol::new(table_name, "npc_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcMemoryShort {}
