// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_state_stream_type::NpcStateStream;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_state_stream`.
///
/// Obtain a handle from the [`NpcStateStreamTableAccess::npc_state_stream`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_state_stream()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_state_stream().on_insert(...)`.
pub struct NpcStateStreamTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcStateStream>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_state_stream`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcStateStreamTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcStateStreamTableHandle`], which mediates access to the table `npc_state_stream`.
    fn npc_state_stream(&self) -> NpcStateStreamTableHandle<'_>;
}

impl NpcStateStreamTableAccess for super::RemoteTables {
    fn npc_state_stream(&self) -> NpcStateStreamTableHandle<'_> {
        NpcStateStreamTableHandle {
            imp: self.imp.get_table::<NpcStateStream>("npc_state_stream"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcStateStreamInsertCallbackId(__sdk::CallbackId);
pub struct NpcStateStreamDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcStateStreamTableHandle<'ctx> {
    type Row = NpcStateStream;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcStateStream> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcStateStreamInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcStateStreamInsertCallbackId {
        NpcStateStreamInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcStateStreamInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcStateStreamDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcStateStreamDeleteCallbackId {
        NpcStateStreamDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcStateStreamDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NpcStateStreamUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcStateStreamTableHandle<'ctx> {
    type UpdateCallbackId = NpcStateStreamUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcStateStreamUpdateCallbackId {
        NpcStateStreamUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcStateStreamUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `npc_id` unique index on the table `npc_state_stream`,
/// which allows point queries on the field of the same name
/// via the [`NpcStateStreamNpcIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_state_stream().npc_id().find(...)`.
pub struct NpcStateStreamNpcIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcStateStream, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcStateStreamTableHandle<'ctx> {
    /// Get a handle on the `npc_id` unique index on the table `npc_state_stream`.
    pub fn npc_id(&self) -> NpcStateStreamNpcIdUnique<'ctx> {
        NpcStateStreamNpcIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("npc_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcStateStreamNpcIdUnique<'ctx> {
    /// Find the subscribed row whose `npc_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcStateStream> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcStateStream>("npc_state_stream");
    _table.add_unique_constraint::<u64>("npc_id", |row| &row.npc_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NpcStateStream>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcStateStream>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NpcStateStream`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait npc_state_streamQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NpcStateStream`.
    fn npc_state_stream(&self) -> __sdk::__query_builder::Table<NpcStateStream>;
}

impl npc_state_streamQueryTableAccess for __sdk::QueryTableAccessor {
    fn npc_state_stream(&self) -> __sdk::__query_builder::Table<NpcStateStream> {
        __sdk::__query_builder::Table::new("npc_state_stream")
    }
}
