// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcAnchorState {
    pub anchor_id: u64,
    pub region_id: u64,
    pub hex_x: i32,
    pub hex_z: i32,
    pub anchor_kind: u8,
    pub is_active: bool,
    pub occupied_by_npc_id: Option<u64>,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for NpcAnchorState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcAnchorState`.
///
/// Provides typed access to columns for query building.
pub struct NpcAnchorStateCols {
    pub anchor_id: __sdk::__query_builder::Col<NpcAnchorState, u64>,
    pub region_id: __sdk::__query_builder::Col<NpcAnchorState, u64>,
    pub hex_x: __sdk::__query_builder::Col<NpcAnchorState, i32>,
    pub hex_z: __sdk::__query_builder::Col<NpcAnchorState, i32>,
    pub anchor_kind: __sdk::__query_builder::Col<NpcAnchorState, u8>,
    pub is_active: __sdk::__query_builder::Col<NpcAnchorState, bool>,
    pub occupied_by_npc_id: __sdk::__query_builder::Col<NpcAnchorState, Option<u64>>,
    pub updated_at: __sdk::__query_builder::Col<NpcAnchorState, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for NpcAnchorState {
    type Cols = NpcAnchorStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcAnchorStateCols {
            anchor_id: __sdk::__query_builder::Col::new(table_name, "anchor_id"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            hex_x: __sdk::__query_builder::Col::new(table_name, "hex_x"),
            hex_z: __sdk::__query_builder::Col::new(table_name, "hex_z"),
            anchor_kind: __sdk::__query_builder::Col::new(table_name, "anchor_kind"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            occupied_by_npc_id: __sdk::__query_builder::Col::new(table_name, "occupied_by_npc_id"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcAnchorState`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcAnchorStateIxCols {
    pub anchor_id: __sdk::__query_builder::IxCol<NpcAnchorState, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcAnchorState {
    type IxCols = NpcAnchorStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcAnchorStateIxCols {
            anchor_id: __sdk::__query_builder::IxCol::new(table_name, "anchor_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcAnchorState {}
