// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OrderFill {
    pub fill_id: u64,
    pub order_id: String,
    pub fill_qty: u32,
    pub fill_price: u64,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for OrderFill {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OrderFill`.
///
/// Provides typed access to columns for query building.
pub struct OrderFillCols {
    pub fill_id: __sdk::__query_builder::Col<OrderFill, u64>,
    pub order_id: __sdk::__query_builder::Col<OrderFill, String>,
    pub fill_qty: __sdk::__query_builder::Col<OrderFill, u32>,
    pub fill_price: __sdk::__query_builder::Col<OrderFill, u64>,
    pub created_at: __sdk::__query_builder::Col<OrderFill, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for OrderFill {
    type Cols = OrderFillCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OrderFillCols {
            fill_id: __sdk::__query_builder::Col::new(table_name, "fill_id"),
            order_id: __sdk::__query_builder::Col::new(table_name, "order_id"),
            fill_qty: __sdk::__query_builder::Col::new(table_name, "fill_qty"),
            fill_price: __sdk::__query_builder::Col::new(table_name, "fill_price"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `OrderFill`.
///
/// Provides typed access to indexed columns for query building.
pub struct OrderFillIxCols {
    pub fill_id: __sdk::__query_builder::IxCol<OrderFill, u64>,
}

impl __sdk::__query_builder::HasIxCols for OrderFill {
    type IxCols = OrderFillIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OrderFillIxCols {
            fill_id: __sdk::__query_builder::IxCol::new(table_name, "fill_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OrderFill {}
