// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PartyLeaveArgs {
    pub party_id: String,
}

impl From<PartyLeaveArgs> for super::Reducer {
    fn from(args: PartyLeaveArgs) -> Self {
        Self::PartyLeave {
            party_id: args.party_id,
        }
    }
}

impl __sdk::InModule for PartyLeaveArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `party_leave`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait party_leave {
    /// Request that the remote module invoke the reducer `party_leave` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`party_leave:party_leave_then`] to run a callback after the reducer completes.
    fn party_leave(&self, party_id: String) -> __sdk::Result<()> {
        self.party_leave_then(party_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `party_leave` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn party_leave_then(
        &self,
        party_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl party_leave for super::RemoteReducers {
    fn party_leave_then(
        &self,
        party_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PartyLeaveArgs { party_id }, callback)
    }
}
