// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_inventory_container_view_type::PlayerInventoryContainerView;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_inventory_container_view`.
///
/// Obtain a handle from the [`PlayerInventoryContainerViewTableAccess::player_inventory_container_view`] method on [`super::RemoteTables`],
/// like `ctx.db.player_inventory_container_view()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_inventory_container_view().on_insert(...)`.
pub struct PlayerInventoryContainerViewTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerInventoryContainerView>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_inventory_container_view`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerInventoryContainerViewTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerInventoryContainerViewTableHandle`], which mediates access to the table `player_inventory_container_view`.
    fn player_inventory_container_view(&self) -> PlayerInventoryContainerViewTableHandle<'_>;
}

impl PlayerInventoryContainerViewTableAccess for super::RemoteTables {
    fn player_inventory_container_view(&self) -> PlayerInventoryContainerViewTableHandle<'_> {
        PlayerInventoryContainerViewTableHandle {
            imp: self
                .imp
                .get_table::<PlayerInventoryContainerView>("player_inventory_container_view"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerInventoryContainerViewInsertCallbackId(__sdk::CallbackId);
pub struct PlayerInventoryContainerViewDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerInventoryContainerViewTableHandle<'ctx> {
    type Row = PlayerInventoryContainerView;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerInventoryContainerView> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerInventoryContainerViewInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerInventoryContainerViewInsertCallbackId {
        PlayerInventoryContainerViewInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerInventoryContainerViewInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerInventoryContainerViewDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerInventoryContainerViewDeleteCallbackId {
        PlayerInventoryContainerViewDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerInventoryContainerViewDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayerInventoryContainerViewUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerInventoryContainerViewTableHandle<'ctx> {
    type UpdateCallbackId = PlayerInventoryContainerViewUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerInventoryContainerViewUpdateCallbackId {
        PlayerInventoryContainerViewUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerInventoryContainerViewUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `view_key` unique index on the table `player_inventory_container_view`,
/// which allows point queries on the field of the same name
/// via the [`PlayerInventoryContainerViewViewKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_inventory_container_view().view_key().find(...)`.
pub struct PlayerInventoryContainerViewViewKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerInventoryContainerView, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerInventoryContainerViewTableHandle<'ctx> {
    /// Get a handle on the `view_key` unique index on the table `player_inventory_container_view`.
    pub fn view_key(&self) -> PlayerInventoryContainerViewViewKeyUnique<'ctx> {
        PlayerInventoryContainerViewViewKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("view_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerInventoryContainerViewViewKeyUnique<'ctx> {
    /// Find the subscribed row whose `view_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<PlayerInventoryContainerView> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<PlayerInventoryContainerView>("player_inventory_container_view");
    _table.add_unique_constraint::<String>("view_key", |row| &row.view_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerInventoryContainerView>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<PlayerInventoryContainerView>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerInventoryContainerView`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait player_inventory_container_viewQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerInventoryContainerView`.
    fn player_inventory_container_view(
        &self,
    ) -> __sdk::__query_builder::Table<PlayerInventoryContainerView>;
}

impl player_inventory_container_viewQueryTableAccess for __sdk::QueryTableAccessor {
    fn player_inventory_container_view(
        &self,
    ) -> __sdk::__query_builder::Table<PlayerInventoryContainerView> {
        __sdk::__query_builder::Table::new("player_inventory_container_view")
    }
}
