// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerMovementFeedbackView {
    pub request_key: String,
    pub identity: __sdk::Identity,
    pub request_id: String,
    pub accepted: bool,
    pub reason_code: String,
    pub server_x: f32,
    pub server_y: f32,
    pub server_z: f32,
    pub processed_at: __sdk::Timestamp,
}

impl __sdk::InModule for PlayerMovementFeedbackView {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerMovementFeedbackView`.
///
/// Provides typed access to columns for query building.
pub struct PlayerMovementFeedbackViewCols {
    pub request_key: __sdk::__query_builder::Col<PlayerMovementFeedbackView, String>,
    pub identity: __sdk::__query_builder::Col<PlayerMovementFeedbackView, __sdk::Identity>,
    pub request_id: __sdk::__query_builder::Col<PlayerMovementFeedbackView, String>,
    pub accepted: __sdk::__query_builder::Col<PlayerMovementFeedbackView, bool>,
    pub reason_code: __sdk::__query_builder::Col<PlayerMovementFeedbackView, String>,
    pub server_x: __sdk::__query_builder::Col<PlayerMovementFeedbackView, f32>,
    pub server_y: __sdk::__query_builder::Col<PlayerMovementFeedbackView, f32>,
    pub server_z: __sdk::__query_builder::Col<PlayerMovementFeedbackView, f32>,
    pub processed_at: __sdk::__query_builder::Col<PlayerMovementFeedbackView, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PlayerMovementFeedbackView {
    type Cols = PlayerMovementFeedbackViewCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerMovementFeedbackViewCols {
            request_key: __sdk::__query_builder::Col::new(table_name, "request_key"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            accepted: __sdk::__query_builder::Col::new(table_name, "accepted"),
            reason_code: __sdk::__query_builder::Col::new(table_name, "reason_code"),
            server_x: __sdk::__query_builder::Col::new(table_name, "server_x"),
            server_y: __sdk::__query_builder::Col::new(table_name, "server_y"),
            server_z: __sdk::__query_builder::Col::new(table_name, "server_z"),
            processed_at: __sdk::__query_builder::Col::new(table_name, "processed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerMovementFeedbackView`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerMovementFeedbackViewIxCols {
    pub request_key: __sdk::__query_builder::IxCol<PlayerMovementFeedbackView, String>,
}

impl __sdk::__query_builder::HasIxCols for PlayerMovementFeedbackView {
    type IxCols = PlayerMovementFeedbackViewIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerMovementFeedbackViewIxCols {
            request_key: __sdk::__query_builder::IxCol::new(table_name, "request_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerMovementFeedbackView {}
