// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct QuestStageDef {
    pub stage_id: u64,
    pub chain_id: u64,
    pub objective_type: u8,
    pub objective_target: u64,
    pub objective_count: u32,
}

impl __sdk::InModule for QuestStageDef {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `QuestStageDef`.
///
/// Provides typed access to columns for query building.
pub struct QuestStageDefCols {
    pub stage_id: __sdk::__query_builder::Col<QuestStageDef, u64>,
    pub chain_id: __sdk::__query_builder::Col<QuestStageDef, u64>,
    pub objective_type: __sdk::__query_builder::Col<QuestStageDef, u8>,
    pub objective_target: __sdk::__query_builder::Col<QuestStageDef, u64>,
    pub objective_count: __sdk::__query_builder::Col<QuestStageDef, u32>,
}

impl __sdk::__query_builder::HasCols for QuestStageDef {
    type Cols = QuestStageDefCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        QuestStageDefCols {
            stage_id: __sdk::__query_builder::Col::new(table_name, "stage_id"),
            chain_id: __sdk::__query_builder::Col::new(table_name, "chain_id"),
            objective_type: __sdk::__query_builder::Col::new(table_name, "objective_type"),
            objective_target: __sdk::__query_builder::Col::new(table_name, "objective_target"),
            objective_count: __sdk::__query_builder::Col::new(table_name, "objective_count"),
        }
    }
}

/// Indexed column accessor struct for the table `QuestStageDef`.
///
/// Provides typed access to indexed columns for query building.
pub struct QuestStageDefIxCols {
    pub stage_id: __sdk::__query_builder::IxCol<QuestStageDef, u64>,
}

impl __sdk::__query_builder::HasIxCols for QuestStageDef {
    type IxCols = QuestStageDefIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        QuestStageDefIxCols {
            stage_id: __sdk::__query_builder::IxCol::new(table_name, "stage_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for QuestStageDef {}
