// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct QuestChainDef {
    pub chain_id: u64,
    pub start_npc_id: u64,
    pub stage_count: u32,
    pub reward_item_def_id: u64,
    pub reward_item_qty: u32,
}

impl __sdk::InModule for QuestChainDef {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `QuestChainDef`.
///
/// Provides typed access to columns for query building.
pub struct QuestChainDefCols {
    pub chain_id: __sdk::__query_builder::Col<QuestChainDef, u64>,
    pub start_npc_id: __sdk::__query_builder::Col<QuestChainDef, u64>,
    pub stage_count: __sdk::__query_builder::Col<QuestChainDef, u32>,
    pub reward_item_def_id: __sdk::__query_builder::Col<QuestChainDef, u64>,
    pub reward_item_qty: __sdk::__query_builder::Col<QuestChainDef, u32>,
}

impl __sdk::__query_builder::HasCols for QuestChainDef {
    type Cols = QuestChainDefCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        QuestChainDefCols {
            chain_id: __sdk::__query_builder::Col::new(table_name, "chain_id"),
            start_npc_id: __sdk::__query_builder::Col::new(table_name, "start_npc_id"),
            stage_count: __sdk::__query_builder::Col::new(table_name, "stage_count"),
            reward_item_def_id: __sdk::__query_builder::Col::new(table_name, "reward_item_def_id"),
            reward_item_qty: __sdk::__query_builder::Col::new(table_name, "reward_item_qty"),
        }
    }
}

/// Indexed column accessor struct for the table `QuestChainDef`.
///
/// Provides typed access to indexed columns for query building.
pub struct QuestChainDefIxCols {
    pub chain_id: __sdk::__query_builder::IxCol<QuestChainDef, u64>,
}

impl __sdk::__query_builder::HasIxCols for QuestChainDef {
    type IxCols = QuestChainDefIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        QuestChainDefIxCols {
            chain_id: __sdk::__query_builder::IxCol::new(table_name, "chain_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for QuestChainDef {}
