// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestPathInDimensionArgs {
    pub region_id: u64,
    pub dimension_id: u32,
    pub start_hex_x: i32,
    pub start_hex_z: i32,
    pub goal_hex_x: i32,
    pub goal_hex_z: i32,
    pub node_limit: u32,
}

impl From<RequestPathInDimensionArgs> for super::Reducer {
    fn from(args: RequestPathInDimensionArgs) -> Self {
        Self::RequestPathInDimension {
            region_id: args.region_id,
            dimension_id: args.dimension_id,
            start_hex_x: args.start_hex_x,
            start_hex_z: args.start_hex_z,
            goal_hex_x: args.goal_hex_x,
            goal_hex_z: args.goal_hex_z,
            node_limit: args.node_limit,
        }
    }
}

impl __sdk::InModule for RequestPathInDimensionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_path_in_dimension`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_path_in_dimension {
    /// Request that the remote module invoke the reducer `request_path_in_dimension` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_path_in_dimension:request_path_in_dimension_then`] to run a callback after the reducer completes.
    fn request_path_in_dimension(
        &self,
        region_id: u64,
        dimension_id: u32,
        start_hex_x: i32,
        start_hex_z: i32,
        goal_hex_x: i32,
        goal_hex_z: i32,
        node_limit: u32,
    ) -> __sdk::Result<()> {
        self.request_path_in_dimension_then(
            region_id,
            dimension_id,
            start_hex_x,
            start_hex_z,
            goal_hex_x,
            goal_hex_z,
            node_limit,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `request_path_in_dimension` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_path_in_dimension_then(
        &self,
        region_id: u64,
        dimension_id: u32,
        start_hex_x: i32,
        start_hex_z: i32,
        goal_hex_x: i32,
        goal_hex_z: i32,
        node_limit: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_path_in_dimension for super::RemoteReducers {
    fn request_path_in_dimension_then(
        &self,
        region_id: u64,
        dimension_id: u32,
        start_hex_x: i32,
        start_hex_z: i32,
        goal_hex_x: i32,
        goal_hex_z: i32,
        node_limit: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RequestPathInDimensionArgs {
                region_id,
                dimension_id,
                start_hex_x,
                start_hex_z,
                goal_hex_x,
                goal_hex_z,
                node_limit,
            },
            callback,
        )
    }
}
