// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::resource_clump_def_type::ResourceClumpDef;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `resource_clump_def`.
///
/// Obtain a handle from the [`ResourceClumpDefTableAccess::resource_clump_def`] method on [`super::RemoteTables`],
/// like `ctx.db.resource_clump_def()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_clump_def().on_insert(...)`.
pub struct ResourceClumpDefTableHandle<'ctx> {
    imp: __sdk::TableHandle<ResourceClumpDef>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `resource_clump_def`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ResourceClumpDefTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ResourceClumpDefTableHandle`], which mediates access to the table `resource_clump_def`.
    fn resource_clump_def(&self) -> ResourceClumpDefTableHandle<'_>;
}

impl ResourceClumpDefTableAccess for super::RemoteTables {
    fn resource_clump_def(&self) -> ResourceClumpDefTableHandle<'_> {
        ResourceClumpDefTableHandle {
            imp: self.imp.get_table::<ResourceClumpDef>("resource_clump_def"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ResourceClumpDefInsertCallbackId(__sdk::CallbackId);
pub struct ResourceClumpDefDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ResourceClumpDefTableHandle<'ctx> {
    type Row = ResourceClumpDef;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ResourceClumpDef> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ResourceClumpDefInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceClumpDefInsertCallbackId {
        ResourceClumpDefInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResourceClumpDefInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ResourceClumpDefDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceClumpDefDeleteCallbackId {
        ResourceClumpDefDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResourceClumpDefDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ResourceClumpDefUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ResourceClumpDefTableHandle<'ctx> {
    type UpdateCallbackId = ResourceClumpDefUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResourceClumpDefUpdateCallbackId {
        ResourceClumpDefUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResourceClumpDefUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `clump_key` unique index on the table `resource_clump_def`,
/// which allows point queries on the field of the same name
/// via the [`ResourceClumpDefClumpKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_clump_def().clump_key().find(...)`.
pub struct ResourceClumpDefClumpKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ResourceClumpDef, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ResourceClumpDefTableHandle<'ctx> {
    /// Get a handle on the `clump_key` unique index on the table `resource_clump_def`.
    pub fn clump_key(&self) -> ResourceClumpDefClumpKeyUnique<'ctx> {
        ResourceClumpDefClumpKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("clump_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ResourceClumpDefClumpKeyUnique<'ctx> {
    /// Find the subscribed row whose `clump_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<ResourceClumpDef> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ResourceClumpDef>("resource_clump_def");
    _table.add_unique_constraint::<String>("clump_key", |row| &row.clump_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ResourceClumpDef>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ResourceClumpDef>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ResourceClumpDef`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait resource_clump_defQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ResourceClumpDef`.
    fn resource_clump_def(&self) -> __sdk::__query_builder::Table<ResourceClumpDef>;
}

impl resource_clump_defQueryTableAccess for __sdk::QueryTableAccessor {
    fn resource_clump_def(&self) -> __sdk::__query_builder::Table<ResourceClumpDef> {
        __sdk::__query_builder::Table::new("resource_clump_def")
    }
}
