// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RoleRevokeArgs {
    pub target_identity: __sdk::Identity,
    pub role: String,
}

impl From<RoleRevokeArgs> for super::Reducer {
    fn from(args: RoleRevokeArgs) -> Self {
        Self::RoleRevoke {
            target_identity: args.target_identity,
            role: args.role,
        }
    }
}

impl __sdk::InModule for RoleRevokeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `role_revoke`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait role_revoke {
    /// Request that the remote module invoke the reducer `role_revoke` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`role_revoke:role_revoke_then`] to run a callback after the reducer completes.
    fn role_revoke(&self, target_identity: __sdk::Identity, role: String) -> __sdk::Result<()> {
        self.role_revoke_then(target_identity, role, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `role_revoke` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn role_revoke_then(
        &self,
        target_identity: __sdk::Identity,
        role: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl role_revoke for super::RemoteReducers {
    fn role_revoke_then(
        &self,
        target_identity: __sdk::Identity,
        role: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RoleRevokeArgs {
                target_identity,
                role,
            },
            callback,
        )
    }
}
