// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SessionCleanupLoopTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub last_run_at: __sdk::Timestamp,
}

impl __sdk::InModule for SessionCleanupLoopTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SessionCleanupLoopTimer`.
///
/// Provides typed access to columns for query building.
pub struct SessionCleanupLoopTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<SessionCleanupLoopTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<SessionCleanupLoopTimer, __sdk::ScheduleAt>,
    pub last_run_at: __sdk::__query_builder::Col<SessionCleanupLoopTimer, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SessionCleanupLoopTimer {
    type Cols = SessionCleanupLoopTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SessionCleanupLoopTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            last_run_at: __sdk::__query_builder::Col::new(table_name, "last_run_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SessionCleanupLoopTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct SessionCleanupLoopTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<SessionCleanupLoopTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for SessionCleanupLoopTimer {
    type IxCols = SessionCleanupLoopTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SessionCleanupLoopTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SessionCleanupLoopTimer {}
