// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetWorldgenParamsArgs {
    pub enabled: bool,
    pub seed: u64,
    pub size_x_chunks: i32,
    pub size_y_chunks: i32,
    pub sea_level: i16,
    pub regenerate_on_start: bool,
}

impl From<SetWorldgenParamsArgs> for super::Reducer {
    fn from(args: SetWorldgenParamsArgs) -> Self {
        Self::SetWorldgenParams {
            enabled: args.enabled,
            seed: args.seed,
            size_x_chunks: args.size_x_chunks,
            size_y_chunks: args.size_y_chunks,
            sea_level: args.sea_level,
            regenerate_on_start: args.regenerate_on_start,
        }
    }
}

impl __sdk::InModule for SetWorldgenParamsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_worldgen_params`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_worldgen_params {
    /// Request that the remote module invoke the reducer `set_worldgen_params` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_worldgen_params:set_worldgen_params_then`] to run a callback after the reducer completes.
    fn set_worldgen_params(
        &self,
        enabled: bool,
        seed: u64,
        size_x_chunks: i32,
        size_y_chunks: i32,
        sea_level: i16,
        regenerate_on_start: bool,
    ) -> __sdk::Result<()> {
        self.set_worldgen_params_then(
            enabled,
            seed,
            size_x_chunks,
            size_y_chunks,
            sea_level,
            regenerate_on_start,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_worldgen_params` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_worldgen_params_then(
        &self,
        enabled: bool,
        seed: u64,
        size_x_chunks: i32,
        size_y_chunks: i32,
        sea_level: i16,
        regenerate_on_start: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_worldgen_params for super::RemoteReducers {
    fn set_worldgen_params_then(
        &self,
        enabled: bool,
        seed: u64,
        size_x_chunks: i32,
        size_y_chunks: i32,
        sea_level: i16,
        regenerate_on_start: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetWorldgenParamsArgs {
                enabled,
                seed,
                size_x_chunks,
                size_y_chunks,
                sea_level,
                regenerate_on_start,
            },
            callback,
        )
    }
}
