// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetWorldgenLazyParamsArgs {
    pub enabled: bool,
    pub seed_radius_chunks: i16,
    pub chunks_per_tick: u16,
    pub prefetch_ring: i16,
}

impl From<SetWorldgenLazyParamsArgs> for super::Reducer {
    fn from(args: SetWorldgenLazyParamsArgs) -> Self {
        Self::SetWorldgenLazyParams {
            enabled: args.enabled,
            seed_radius_chunks: args.seed_radius_chunks,
            chunks_per_tick: args.chunks_per_tick,
            prefetch_ring: args.prefetch_ring,
        }
    }
}

impl __sdk::InModule for SetWorldgenLazyParamsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_worldgen_lazy_params`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_worldgen_lazy_params {
    /// Request that the remote module invoke the reducer `set_worldgen_lazy_params` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_worldgen_lazy_params:set_worldgen_lazy_params_then`] to run a callback after the reducer completes.
    fn set_worldgen_lazy_params(
        &self,
        enabled: bool,
        seed_radius_chunks: i16,
        chunks_per_tick: u16,
        prefetch_ring: i16,
    ) -> __sdk::Result<()> {
        self.set_worldgen_lazy_params_then(
            enabled,
            seed_radius_chunks,
            chunks_per_tick,
            prefetch_ring,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_worldgen_lazy_params` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_worldgen_lazy_params_then(
        &self,
        enabled: bool,
        seed_radius_chunks: i16,
        chunks_per_tick: u16,
        prefetch_ring: i16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_worldgen_lazy_params for super::RemoteReducers {
    fn set_worldgen_lazy_params_then(
        &self,
        enabled: bool,
        seed_radius_chunks: i16,
        chunks_per_tick: u16,
        prefetch_ring: i16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetWorldgenLazyParamsArgs {
                enabled,
                seed_radius_chunks,
                chunks_per_tick,
                prefetch_ring,
            },
            callback,
        )
    }
}
