// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StatusEffect {
    pub status_key: String,
    pub entity_id: u64,
    pub effect_id: u64,
    pub stack: u16,
    pub expires_at: __sdk::Timestamp,
}

impl __sdk::InModule for StatusEffect {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StatusEffect`.
///
/// Provides typed access to columns for query building.
pub struct StatusEffectCols {
    pub status_key: __sdk::__query_builder::Col<StatusEffect, String>,
    pub entity_id: __sdk::__query_builder::Col<StatusEffect, u64>,
    pub effect_id: __sdk::__query_builder::Col<StatusEffect, u64>,
    pub stack: __sdk::__query_builder::Col<StatusEffect, u16>,
    pub expires_at: __sdk::__query_builder::Col<StatusEffect, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for StatusEffect {
    type Cols = StatusEffectCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StatusEffectCols {
            status_key: __sdk::__query_builder::Col::new(table_name, "status_key"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            effect_id: __sdk::__query_builder::Col::new(table_name, "effect_id"),
            stack: __sdk::__query_builder::Col::new(table_name, "stack"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `StatusEffect`.
///
/// Provides typed access to indexed columns for query building.
pub struct StatusEffectIxCols {
    pub status_key: __sdk::__query_builder::IxCol<StatusEffect, String>,
}

impl __sdk::__query_builder::HasIxCols for StatusEffect {
    type IxCols = StatusEffectIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StatusEffectIxCols {
            status_key: __sdk::__query_builder::IxCol::new(table_name, "status_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StatusEffect {}
