// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SyncClientFrameArgs {
    pub frame_no: u64,
    pub region_id: u64,
    pub dimension_id: u32,
    pub client_time_ms: u64,
}

impl From<SyncClientFrameArgs> for super::Reducer {
    fn from(args: SyncClientFrameArgs) -> Self {
        Self::SyncClientFrame {
            frame_no: args.frame_no,
            region_id: args.region_id,
            dimension_id: args.dimension_id,
            client_time_ms: args.client_time_ms,
        }
    }
}

impl __sdk::InModule for SyncClientFrameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sync_client_frame`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sync_client_frame {
    /// Request that the remote module invoke the reducer `sync_client_frame` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sync_client_frame:sync_client_frame_then`] to run a callback after the reducer completes.
    fn sync_client_frame(
        &self,
        frame_no: u64,
        region_id: u64,
        dimension_id: u32,
        client_time_ms: u64,
    ) -> __sdk::Result<()> {
        self.sync_client_frame_then(frame_no, region_id, dimension_id, client_time_ms, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sync_client_frame` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sync_client_frame_then(
        &self,
        frame_no: u64,
        region_id: u64,
        dimension_id: u32,
        client_time_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sync_client_frame for super::RemoteReducers {
    fn sync_client_frame_then(
        &self,
        frame_no: u64,
        region_id: u64,
        dimension_id: u32,
        client_time_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SyncClientFrameArgs {
                frame_no,
                region_id,
                dimension_id,
                client_time_ms,
            },
            callback,
        )
    }
}
