// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TerrainChunk {
    pub chunk_key: String,
    pub region_id: u64,
    pub dimension_id: u32,
    pub chunk_x: i32,
    pub chunk_y: i32,
    pub biome_id: u16,
    pub seed: u64,
    pub generated_at: __sdk::Timestamp,
    pub height_min: i16,
    pub height_max: i16,
    pub water_ratio_permille: u16,
    pub cell_payload_version: u16,
    pub cell_payload: Vec<i16>,
}

impl __sdk::InModule for TerrainChunk {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TerrainChunk`.
///
/// Provides typed access to columns for query building.
pub struct TerrainChunkCols {
    pub chunk_key: __sdk::__query_builder::Col<TerrainChunk, String>,
    pub region_id: __sdk::__query_builder::Col<TerrainChunk, u64>,
    pub dimension_id: __sdk::__query_builder::Col<TerrainChunk, u32>,
    pub chunk_x: __sdk::__query_builder::Col<TerrainChunk, i32>,
    pub chunk_y: __sdk::__query_builder::Col<TerrainChunk, i32>,
    pub biome_id: __sdk::__query_builder::Col<TerrainChunk, u16>,
    pub seed: __sdk::__query_builder::Col<TerrainChunk, u64>,
    pub generated_at: __sdk::__query_builder::Col<TerrainChunk, __sdk::Timestamp>,
    pub height_min: __sdk::__query_builder::Col<TerrainChunk, i16>,
    pub height_max: __sdk::__query_builder::Col<TerrainChunk, i16>,
    pub water_ratio_permille: __sdk::__query_builder::Col<TerrainChunk, u16>,
    pub cell_payload_version: __sdk::__query_builder::Col<TerrainChunk, u16>,
    pub cell_payload: __sdk::__query_builder::Col<TerrainChunk, Vec<i16>>,
}

impl __sdk::__query_builder::HasCols for TerrainChunk {
    type Cols = TerrainChunkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TerrainChunkCols {
            chunk_key: __sdk::__query_builder::Col::new(table_name, "chunk_key"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            dimension_id: __sdk::__query_builder::Col::new(table_name, "dimension_id"),
            chunk_x: __sdk::__query_builder::Col::new(table_name, "chunk_x"),
            chunk_y: __sdk::__query_builder::Col::new(table_name, "chunk_y"),
            biome_id: __sdk::__query_builder::Col::new(table_name, "biome_id"),
            seed: __sdk::__query_builder::Col::new(table_name, "seed"),
            generated_at: __sdk::__query_builder::Col::new(table_name, "generated_at"),
            height_min: __sdk::__query_builder::Col::new(table_name, "height_min"),
            height_max: __sdk::__query_builder::Col::new(table_name, "height_max"),
            water_ratio_permille: __sdk::__query_builder::Col::new(
                table_name,
                "water_ratio_permille",
            ),
            cell_payload_version: __sdk::__query_builder::Col::new(
                table_name,
                "cell_payload_version",
            ),
            cell_payload: __sdk::__query_builder::Col::new(table_name, "cell_payload"),
        }
    }
}

/// Indexed column accessor struct for the table `TerrainChunk`.
///
/// Provides typed access to indexed columns for query building.
pub struct TerrainChunkIxCols {
    pub chunk_key: __sdk::__query_builder::IxCol<TerrainChunk, String>,
}

impl __sdk::__query_builder::HasIxCols for TerrainChunk {
    type IxCols = TerrainChunkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TerrainChunkIxCols {
            chunk_key: __sdk::__query_builder::IxCol::new(table_name, "chunk_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TerrainChunk {}
