// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TerrainChunkPayload {
    pub chunk_key: String,
    pub region_id: u64,
    pub dimension_id: u32,
    pub chunk_x: i32,
    pub chunk_y: i32,
    pub cell_payload_version: u16,
    pub cell_payload_bytes: Vec<u8>,
    pub cell_count: u32,
    pub generated_at: __sdk::Timestamp,
}

impl __sdk::InModule for TerrainChunkPayload {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TerrainChunkPayload`.
///
/// Provides typed access to columns for query building.
pub struct TerrainChunkPayloadCols {
    pub chunk_key: __sdk::__query_builder::Col<TerrainChunkPayload, String>,
    pub region_id: __sdk::__query_builder::Col<TerrainChunkPayload, u64>,
    pub dimension_id: __sdk::__query_builder::Col<TerrainChunkPayload, u32>,
    pub chunk_x: __sdk::__query_builder::Col<TerrainChunkPayload, i32>,
    pub chunk_y: __sdk::__query_builder::Col<TerrainChunkPayload, i32>,
    pub cell_payload_version: __sdk::__query_builder::Col<TerrainChunkPayload, u16>,
    pub cell_payload_bytes: __sdk::__query_builder::Col<TerrainChunkPayload, Vec<u8>>,
    pub cell_count: __sdk::__query_builder::Col<TerrainChunkPayload, u32>,
    pub generated_at: __sdk::__query_builder::Col<TerrainChunkPayload, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for TerrainChunkPayload {
    type Cols = TerrainChunkPayloadCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TerrainChunkPayloadCols {
            chunk_key: __sdk::__query_builder::Col::new(table_name, "chunk_key"),
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            dimension_id: __sdk::__query_builder::Col::new(table_name, "dimension_id"),
            chunk_x: __sdk::__query_builder::Col::new(table_name, "chunk_x"),
            chunk_y: __sdk::__query_builder::Col::new(table_name, "chunk_y"),
            cell_payload_version: __sdk::__query_builder::Col::new(
                table_name,
                "cell_payload_version",
            ),
            cell_payload_bytes: __sdk::__query_builder::Col::new(table_name, "cell_payload_bytes"),
            cell_count: __sdk::__query_builder::Col::new(table_name, "cell_count"),
            generated_at: __sdk::__query_builder::Col::new(table_name, "generated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TerrainChunkPayload`.
///
/// Provides typed access to indexed columns for query building.
pub struct TerrainChunkPayloadIxCols {
    pub chunk_key: __sdk::__query_builder::IxCol<TerrainChunkPayload, String>,
}

impl __sdk::__query_builder::HasIxCols for TerrainChunkPayload {
    type IxCols = TerrainChunkPayloadIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TerrainChunkPayloadIxCols {
            chunk_key: __sdk::__query_builder::IxCol::new(table_name, "chunk_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TerrainChunkPayload {}
