// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::terrain_chunk_stream_type::TerrainChunkStream;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `terrain_chunk_stream`.
///
/// Obtain a handle from the [`TerrainChunkStreamTableAccess::terrain_chunk_stream`] method on [`super::RemoteTables`],
/// like `ctx.db.terrain_chunk_stream()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.terrain_chunk_stream().on_insert(...)`.
pub struct TerrainChunkStreamTableHandle<'ctx> {
    imp: __sdk::TableHandle<TerrainChunkStream>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `terrain_chunk_stream`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TerrainChunkStreamTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TerrainChunkStreamTableHandle`], which mediates access to the table `terrain_chunk_stream`.
    fn terrain_chunk_stream(&self) -> TerrainChunkStreamTableHandle<'_>;
}

impl TerrainChunkStreamTableAccess for super::RemoteTables {
    fn terrain_chunk_stream(&self) -> TerrainChunkStreamTableHandle<'_> {
        TerrainChunkStreamTableHandle {
            imp: self
                .imp
                .get_table::<TerrainChunkStream>("terrain_chunk_stream"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TerrainChunkStreamInsertCallbackId(__sdk::CallbackId);
pub struct TerrainChunkStreamDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TerrainChunkStreamTableHandle<'ctx> {
    type Row = TerrainChunkStream;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TerrainChunkStream> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TerrainChunkStreamInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TerrainChunkStreamInsertCallbackId {
        TerrainChunkStreamInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TerrainChunkStreamInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TerrainChunkStreamDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TerrainChunkStreamDeleteCallbackId {
        TerrainChunkStreamDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TerrainChunkStreamDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TerrainChunkStreamUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TerrainChunkStreamTableHandle<'ctx> {
    type UpdateCallbackId = TerrainChunkStreamUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TerrainChunkStreamUpdateCallbackId {
        TerrainChunkStreamUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TerrainChunkStreamUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `chunk_key` unique index on the table `terrain_chunk_stream`,
/// which allows point queries on the field of the same name
/// via the [`TerrainChunkStreamChunkKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.terrain_chunk_stream().chunk_key().find(...)`.
pub struct TerrainChunkStreamChunkKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TerrainChunkStream, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TerrainChunkStreamTableHandle<'ctx> {
    /// Get a handle on the `chunk_key` unique index on the table `terrain_chunk_stream`.
    pub fn chunk_key(&self) -> TerrainChunkStreamChunkKeyUnique<'ctx> {
        TerrainChunkStreamChunkKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("chunk_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TerrainChunkStreamChunkKeyUnique<'ctx> {
    /// Find the subscribed row whose `chunk_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TerrainChunkStream> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TerrainChunkStream>("terrain_chunk_stream");
    _table.add_unique_constraint::<String>("chunk_key", |row| &row.chunk_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TerrainChunkStream>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TerrainChunkStream>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TerrainChunkStream`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait terrain_chunk_streamQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TerrainChunkStream`.
    fn terrain_chunk_stream(&self) -> __sdk::__query_builder::Table<TerrainChunkStream>;
}

impl terrain_chunk_streamQueryTableAccess for __sdk::QueryTableAccessor {
    fn terrain_chunk_stream(&self) -> __sdk::__query_builder::Table<TerrainChunkStream> {
        __sdk::__query_builder::Table::new("terrain_chunk_stream")
    }
}
