// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertNpcPopulationDefArgs {
    pub npc_type: u8,
    pub population_permille: u16,
    pub min_action_seconds: u16,
    pub max_action_seconds: u16,
    pub default_schedule_kind: u8,
    pub default_role: u8,
    pub traveling_enabled: bool,
    pub enabled: bool,
}

impl From<UpsertNpcPopulationDefArgs> for super::Reducer {
    fn from(args: UpsertNpcPopulationDefArgs) -> Self {
        Self::UpsertNpcPopulationDef {
            npc_type: args.npc_type,
            population_permille: args.population_permille,
            min_action_seconds: args.min_action_seconds,
            max_action_seconds: args.max_action_seconds,
            default_schedule_kind: args.default_schedule_kind,
            default_role: args.default_role,
            traveling_enabled: args.traveling_enabled,
            enabled: args.enabled,
        }
    }
}

impl __sdk::InModule for UpsertNpcPopulationDefArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_npc_population_def`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_npc_population_def {
    /// Request that the remote module invoke the reducer `upsert_npc_population_def` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_npc_population_def:upsert_npc_population_def_then`] to run a callback after the reducer completes.
    fn upsert_npc_population_def(
        &self,
        npc_type: u8,
        population_permille: u16,
        min_action_seconds: u16,
        max_action_seconds: u16,
        default_schedule_kind: u8,
        default_role: u8,
        traveling_enabled: bool,
        enabled: bool,
    ) -> __sdk::Result<()> {
        self.upsert_npc_population_def_then(
            npc_type,
            population_permille,
            min_action_seconds,
            max_action_seconds,
            default_schedule_kind,
            default_role,
            traveling_enabled,
            enabled,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `upsert_npc_population_def` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_npc_population_def_then(
        &self,
        npc_type: u8,
        population_permille: u16,
        min_action_seconds: u16,
        max_action_seconds: u16,
        default_schedule_kind: u8,
        default_role: u8,
        traveling_enabled: bool,
        enabled: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_npc_population_def for super::RemoteReducers {
    fn upsert_npc_population_def_then(
        &self,
        npc_type: u8,
        population_permille: u16,
        min_action_seconds: u16,
        max_action_seconds: u16,
        default_schedule_kind: u8,
        default_role: u8,
        traveling_enabled: bool,
        enabled: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertNpcPopulationDefArgs {
                npc_type,
                population_permille,
                min_action_seconds,
                max_action_seconds,
                default_schedule_kind,
                default_role,
                traveling_enabled,
                enabled,
            },
            callback,
        )
    }
}
