// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_gen_params_type::WorldGenParams;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_gen_params`.
///
/// Obtain a handle from the [`WorldGenParamsTableAccess::world_gen_params`] method on [`super::RemoteTables`],
/// like `ctx.db.world_gen_params()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_gen_params().on_insert(...)`.
pub struct WorldGenParamsTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldGenParams>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_gen_params`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldGenParamsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldGenParamsTableHandle`], which mediates access to the table `world_gen_params`.
    fn world_gen_params(&self) -> WorldGenParamsTableHandle<'_>;
}

impl WorldGenParamsTableAccess for super::RemoteTables {
    fn world_gen_params(&self) -> WorldGenParamsTableHandle<'_> {
        WorldGenParamsTableHandle {
            imp: self.imp.get_table::<WorldGenParams>("world_gen_params"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldGenParamsInsertCallbackId(__sdk::CallbackId);
pub struct WorldGenParamsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorldGenParamsTableHandle<'ctx> {
    type Row = WorldGenParams;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldGenParams> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldGenParamsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldGenParamsInsertCallbackId {
        WorldGenParamsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldGenParamsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldGenParamsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldGenParamsDeleteCallbackId {
        WorldGenParamsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldGenParamsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldGenParamsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldGenParamsTableHandle<'ctx> {
    type UpdateCallbackId = WorldGenParamsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldGenParamsUpdateCallbackId {
        WorldGenParamsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldGenParamsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `world_gen_params`,
/// which allows point queries on the field of the same name
/// via the [`WorldGenParamsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_gen_params().id().find(...)`.
pub struct WorldGenParamsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldGenParams, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldGenParamsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_gen_params`.
    pub fn id(&self) -> WorldGenParamsIdUnique<'ctx> {
        WorldGenParamsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldGenParamsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorldGenParams> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldGenParams>("world_gen_params");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldGenParams>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldGenParams>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldGenParams`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_gen_paramsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldGenParams`.
    fn world_gen_params(&self) -> __sdk::__query_builder::Table<WorldGenParams>;
}

impl world_gen_paramsQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_gen_params(&self) -> __sdk::__query_builder::Table<WorldGenParams> {
        __sdk::__query_builder::Table::new("world_gen_params")
    }
}
