// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldgenLazyLoopTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub last_run_at: __sdk::Timestamp,
}

impl __sdk::InModule for WorldgenLazyLoopTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldgenLazyLoopTimer`.
///
/// Provides typed access to columns for query building.
pub struct WorldgenLazyLoopTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<WorldgenLazyLoopTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<WorldgenLazyLoopTimer, __sdk::ScheduleAt>,
    pub last_run_at: __sdk::__query_builder::Col<WorldgenLazyLoopTimer, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for WorldgenLazyLoopTimer {
    type Cols = WorldgenLazyLoopTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldgenLazyLoopTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            last_run_at: __sdk::__query_builder::Col::new(table_name, "last_run_at"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldgenLazyLoopTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldgenLazyLoopTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<WorldgenLazyLoopTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for WorldgenLazyLoopTimer {
    type IxCols = WorldgenLazyLoopTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldgenLazyLoopTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WorldgenLazyLoopTimer {}
