// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  regionId: __t.u64().name("region_id"),
  dimensionId: __t.u32().name("dimension_id"),
  hexX: __t.i32().name("hex_x"),
  hexZ: __t.i32().name("hex_z"),
  state: __t.u8(),
  requiredItemDefId: __t.u64().name("required_item_def_id"),
  requiredItemQty: __t.u32().name("required_item_qty"),
  buildProgress: __t.u32().name("build_progress"),
  buildRequired: __t.u32().name("build_required"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
