// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("BuildingPreviewFeedbackView", {
  requestKey: __t.string(),
  identity: __t.identity(),
  requestId: __t.string(),
  regionId: __t.u64(),
  dimensionId: __t.u32(),
  buildingDefId: __t.u64(),
  hexX: __t.i32(),
  hexZ: __t.i32(),
  facing: __t.u8(),
  isValid: __t.bool(),
  reasonCode: __t.string(),
  checkedAt: __t.timestamp(),
});


