// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  changeId: __t.u64().primaryKey().name("change_id"),
  paramKey: __t.string().name("param_key"),
  beforeInt: __t.i64().name("before_int"),
  afterInt: __t.i64().name("after_int"),
  beforeFloat: __t.f64().name("before_float"),
  afterFloat: __t.f64().name("after_float"),
  changedAt: __t.timestamp().name("changed_at"),
});
