// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.identity().primaryKey().name("entity_id"),
  regionId: __t.u64().name("region_id"),
  dimensionId: __t.u32().name("dimension_id"),
  position: __t.array(__t.f32()),
  velocity: __t.array(__t.f32()),
  grounded: __t.bool(),
  lastIntentId: __t.string().name("last_intent_id"),
  lastFrameNo: __t.u64().name("last_frame_no"),
  updatedAt: __t.timestamp().name("updated_at"),
});
