// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chainId: __t.u64().primaryKey().name("chain_id"),
  startNpcId: __t.u64().name("start_npc_id"),
  stageCount: __t.u32().name("stage_count"),
  rewardItemDefId: __t.u64().name("reward_item_def_id"),
  rewardItemQty: __t.u32().name("reward_item_qty"),
});
