// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chunkKey: __t.string().primaryKey().name("chunk_key"),
  regionId: __t.u64().name("region_id"),
  dimensionId: __t.u32().name("dimension_id"),
  chunkX: __t.i32().name("chunk_x"),
  chunkY: __t.i32().name("chunk_y"),
  cellPayloadVersion: __t.u16().name("cell_payload_version"),
  cellPayloadBytes: __t.byteArray().name("cell_payload_bytes"),
  cellCount: __t.u32().name("cell_count"),
  generatedAt: __t.timestamp().name("generated_at"),
});
