// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  outcomeId: __t.string().primaryKey().name("outcome_id"),
  requestKey: __t.string().name("request_key"),
  attackerIdentity: __t.identity().name("attacker_identity"),
  targetIdentity: __t.identity().name("target_identity"),
  regionId: __t.u64().name("region_id"),
  dimensionId: __t.u32().name("dimension_id"),
  damage: __t.i32(),
  targetHpAfter: __t.i32().name("target_hp_after"),
  hit: __t.bool(),
  resolvedAt: __t.timestamp().name("resolved_at"),
});
