// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  claimId: __t.u64().primaryKey().name("claim_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  totemBuildingId: __t.u64().name("totem_building_id"),
  regionId: __t.u64().name("region_id"),
  centerX: __t.i32().name("center_x"),
  centerZ: __t.i32().name("center_z"),
  radius: __t.u32(),
  tier: __t.u32(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
