// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  lastBiomeId: __t.u16().name("last_biome_id"),
  lastEvaluatedAt: __t.timestamp().name("last_evaluated_at"),
  isSubmerged: __t.bool().name("is_submerged"),
});
