// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("MarketFill", {
  fillId: __t.string(),
  buyOrderId: __t.string(),
  sellOrderId: __t.string(),
  itemDefId: __t.u64(),
  quantity: __t.u32(),
  unitPrice: __t.u64(),
  buyerIdentity: __t.identity(),
  sellerIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});


