// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("QuestChainDef", {
  chainId: __t.u64(),
  startNpcId: __t.u64(),
  stageCount: __t.u32(),
  rewardItemDefId: __t.u64(),
  rewardItemQty: __t.u32(),
});


