// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  skillKey: __t.string().primaryKey().name("skill_key"),
  entityId: __t.u64().name("entity_id"),
  skillId: __t.u64().name("skill_id"),
  xp: __t.u64(),
  level: __t.u32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
