#![allow(clippy::disallowed_macros)]
use build_shared::write_if_file_changed;
use std::collections::HashMap;
use std::fs;

pub mod build_shared;

fn to_snakecase(s: &str) -> String {
    let mut output = String::new();
    for c in s.chars() {
        if c.is_ascii_uppercase() {
            if output.len() > 0 {
                output.push('_');
            }
        }
        output.push(c.to_ascii_lowercase());
    }
    output
}

fn build_knowledge() {
    println!("cargo:rerun-if-changed=src/messages/components.rs");

    // table name: indexed
    let mut achievement_table: Vec<String> = Vec::new();

    // knowledge type, component name
    let mut knowledge_table: HashMap<String, i32> = HashMap::new();

    // 1. Read GameState/mod.rs, parse all tables
    let input = fs::read_to_string("src/messages/components.rs").unwrap();

    let lines: Vec<&str> = input.split('\n').collect();
    let mut next_struct_is_table = false;
    let mut achievement = false;
    let mut knowledge_type = 0;

    for line in lines {
        if line.trim().contains("#[") {
            if line.to_ascii_lowercase().contains("spacetimedb::table") {
                next_struct_is_table = true;
            }
            achievement |= line.to_ascii_lowercase().contains("achievement");

            if line.to_ascii_lowercase().contains("knowledge_entity") {
                knowledge_type = 2;
            } else if line.to_ascii_lowercase().contains("knowledge_location") {
                knowledge_type = 3;
            } else if line.to_ascii_lowercase().contains("knowledge_recipe") {
                knowledge_type = 4;
            } else if line.to_ascii_lowercase().contains("knowledge_on_acquire_callback") {
                knowledge_type = 5;
            } else if line.to_ascii_lowercase().contains("knowledge") {
                knowledge_type = 1;
            } else {
                knowledge_type = 0;
            }

            continue;
        }

        if line.contains("pub struct") {
            if next_struct_is_table {
                next_struct_is_table = false;

                if let Some(name_index) = line.find("pub struct ") {
                    let start = name_index + 11;
                    let line = &line[start..];

                    if let Some(index) = line.find(" ") {
                        let name = &line[..index].to_string();

                        if achievement {
                            achievement_table.push(name.clone());
                        }
                        if knowledge_type > 0 {
                            // knowledge or knowledge_entity
                            knowledge_table.insert(name.clone(), knowledge_type);
                        }
                    }
                };
            }
        }

        achievement = false;
    }

    let mut output_includes = String::new();
    let mut output_discovery = String::new();
    let mut output_init = String::new();
    let mut output_commit = String::new();
    let mut output_functions = String::new();
    let mut output_generate_knowledges = String::new();

    let mut sorted_keys: Vec<String> = knowledge_table.clone().into_keys().collect();
    sorted_keys.sort();

    output_includes.push_str("//This file is auto-generated by bitcraft\\build.rs. Do not edit.\r\n\r\n");

    output_includes.push_str("use spacetimedb::{ReducerContext, Table};\r\n");
    output_includes.push_str("use crate::game::discovery::Discovery;\r\n");

    output_discovery.push_str("//This file is auto-generated by bitcraft\\build.rs. Do not edit.\r\n\r\n");

    output_discovery.push_str("use spacetimedb::{ReducerContext, Table};\r\n");
    output_discovery.push_str(
        "use crate::{game::{discovery::Discovery, coordinates::OffsetCoordinatesSmall}, messages::{components::*, static_data::*}};\r\n",
    );

    for k in &sorted_keys {
        output_discovery.push_str(format!("use crate::messages::components::{};\r\n", k).as_str());
    }

    output_discovery.push_str("\r\n\r\npub struct Knowledges {\r\n");

    output_init.push_str("#[allow(dead_code)]\r\n");
    output_init.push_str("impl Discovery {\r\n\r\n");
    output_init.push_str("    pub fn initialize(&mut self, ctx: &ReducerContext) {\r\n");
    output_init.push_str("        let player_entity_id = self.player_entity_id;\r\n");
    output_init.push_str("        self.knowledges = Some(Knowledges {\r\n");

    output_commit.push_str("    pub fn commit(&mut self, ctx: &ReducerContext) {\r\n");
    output_commit.push_str("        if self.knowledges.is_none() {\r\n");
    output_commit.push_str("            return;\r\n");
    output_commit.push_str("        }\r\n\r\n");
    output_commit.push_str("        self.on_knowledge_acquired(ctx);\r\n\r\n");
    output_commit.push_str("        let knowledges = self.knowledges.as_mut().unwrap();\r\n\r\n");
    output_commit.push_str("        let player_entity_id = self.player_entity_id;\r\n\r\n");

    output_generate_knowledges.push_str("pub fn generate_knowledges(ctx: &ReducerContext, entity_id: u64) {\r\n");

    for k in sorted_keys {
        let v = knowledge_table[&k].clone();

        let is_entity = v == 2;
        let is_location = v == 3;
        let is_recipe = v == 4;
        let has_callback = v == 5;
        let has_achievement = achievement_table.contains(&k);

        //KnowledgeBattleActionState => battle_action
        let n = k.strip_prefix("Knowledge").unwrap();
        let n = n.strip_suffix("State").unwrap();
        let n = to_snakecase(n);
        let n = n.as_str();

        let id;
        let id_type;
        let suffix;
        let entry_type;
        let hash_function;
        let cmp;

        if is_entity {
            id = format!("{}_entity_id", n);
            suffix = ": u64";
            id_type = "entity_id";
            entry_type = "KnowledgeEntityEntry";
            hash_function = "entity_entry_array_hash";
            cmp = format!("e.{} == {}", id_type, id);
        } else if is_location {
            id = "coordinates".to_string();
            suffix = ": OffsetCoordinatesSmall";
            id_type = "location_hash";
            entry_type = "KnowledgeLocationEntry";
            hash_function = "location_entry_array_hash";
            cmp = "e.location == coordinates".into();
        } else {
            id = format!("{}_id", n);
            suffix = ": i32";
            id_type = "id";
            entry_type = "KnowledgeEntry";
            hash_function = "knowledge_entry_array_hash";
            cmp = format!("e.{} == {}", id_type, id);
        }

        output_functions.push_str(
            format!(
                "    pub fn already_discovered_{}(ctx: &ReducerContext, player_entity_id: u64, {}{}) -> bool {{\r\n",
                n, id, suffix
            )
            .as_str(),
        );
        output_functions.push_str(
            format!(
                "        if let Some(knowledge) = ctx.db.{}().entity_id().find(player_entity_id) {{\r\n",
                camel_to_snake(&k)
            )
            .as_str(),
        );
        output_functions.push_str(
            format!(
                "            if let Some(_entry) = knowledge.entries.iter().find(|e| {}) {{\r\n",
                cmp
            )
            .as_str(),
        );
        output_functions.push_str("                // acquired or discovered means discovered\r\n");
        output_functions.push_str("                return true;\r\n");
        output_functions.push_str("            }\r\n");
        output_functions.push_str("        }\r\n");
        output_functions.push_str("        false\r\n");
        output_functions.push_str("    }\r\n\r\n");

        output_functions.push_str(
            format!(
                "    pub fn already_acquired_{}(ctx: &ReducerContext, player_entity_id: u64, {}{}) -> bool {{\r\n",
                n, id, suffix
            )
            .as_str(),
        );
        output_functions.push_str(
            format!(
                "        if let Some(knowledge) = ctx.db.{}().entity_id().find(player_entity_id) {{\r\n",
                camel_to_snake(&k)
            )
            .as_str(),
        );
        output_functions.push_str(format!("            if let Some(entry) = knowledge.entries.iter().find(|e| {}) {{\r\n", cmp).as_str());
        output_functions.push_str("                // acquired or discovered means discovered\r\n");
        output_functions.push_str("                return entry.state == KnowledgeState::Acquired;\r\n");
        output_functions.push_str("            }\r\n");
        output_functions.push_str("        }\r\n");
        output_functions.push_str("        false\r\n");
        output_functions.push_str("    }\r\n\r\n");

        // discovery has_discovered
        output_functions.push_str(format!("    pub fn has_discovered_{}(&self, {}{}) -> bool {{\r\n", n, id, suffix).as_str());
        output_functions.push_str("        // This should only be used internally if any change was found in the knowledges, therefore knowledges should yield a value.\r\n");
        output_functions.push_str("        if let Some(knowledges) = &self.knowledges {\r\n");
        output_functions.push_str(format!("            return knowledges.knowledge_{}.iter().any(|e| {});\r\n", n, cmp).as_str());
        output_functions.push_str("        }\r\n");
        output_functions.push_str("        false\r\n");
        output_functions.push_str("    }\r\n\r\n");

        // discovery has_acquired
        output_functions.push_str(format!("    pub fn has_acquired_{}(&self, {}{}) -> bool {{\r\n", n, id, suffix).as_str());
        output_functions.push_str("        // This should only be used internally if any change was found in the knowledges, therefore knowledges should yield a value.\r\n");
        output_functions.push_str("        if let Some(knowledges) = &self.knowledges {\r\n");
        output_functions.push_str(
            format!(
                "            return knowledges.knowledge_{}.iter().any(|e| {} && e.state == KnowledgeState::Acquired);\r\n",
                n, cmp
            )
            .as_str(),
        );
        output_functions.push_str("        }\r\n");
        output_functions.push_str("        false\r\n");
        output_functions.push_str("    }\r\n\r\n");

        // discovery discover
        output_functions.push_str(
            format!(
                "    pub fn discover_{}(&mut self, ctx: &ReducerContext, {}{}) {{\r\n",
                n, id, suffix
            )
            .as_str(),
        );
        if is_location {
            output_functions.push_str("{\r\n");
        } else {
            output_functions.push_str(format!("       if {} != 0 {{\r\n", id).as_str());
        }
        output_functions.push_str("            if self.knowledges.is_none() {\r\n");
        output_functions.push_str(
            format!(
                "                if Self::already_discovered_{}(ctx, self.player_entity_id, {}) {{\r\n",
                n, id
            )
            .as_str(),
        );
        output_functions.push_str("                    return;\r\n");
        output_functions.push_str("                }\r\n");
        output_functions.push_str("                self.initialize(ctx);\r\n");
        output_functions.push_str("            }\r\n");
        output_functions.push_str(format!("            if self.has_discovered_{}({}) {{\r\n", n, id).as_str());
        output_functions.push_str("                return;\r\n");
        output_functions.push_str("            }\r\n");
        output_functions.push_str("            let knowledges = self.knowledges.as_mut().unwrap();\r\n");
        output_functions.push_str(format!("            if !knowledges.knowledge_{}.iter().any(|e| {}) {{\r\n", n, cmp).as_str());
        output_functions.push_str(format!("                let knowledge_entry = {} {{\r\n", entry_type).as_str());
        if is_location {
            output_functions.push_str("                    location: coordinates,\r\n");
        } else {
            output_functions.push_str(format!("                    {}: {},\r\n", id_type, id).as_str());
        }
        output_functions.push_str("                    state: KnowledgeState::Discovered,\r\n");
        output_functions.push_str("                };\r\n");
        output_functions.push_str(format!("                knowledges.knowledge_{}.push(knowledge_entry);\r\n", n).as_str());
        if is_recipe {
            output_functions.push_str(format!("                self.discover_{}_recipe_components(ctx, {});\r\n", n, id).as_str());
        }
        output_functions.push_str("            };\r\n");
        output_functions.push_str("        }\r\n");
        output_functions.push_str("    }\r\n\r\n");

        // discovery acquire
        output_functions.push_str(format!("    pub fn acquire_{}(&mut self, ctx: &ReducerContext, {}{}) {{\r\n", n, id, suffix).as_str());
        if is_location {
            output_functions.push_str("{\r\n");
        } else {
            output_functions.push_str(format!("       if {} != 0 {{\r\n", id).as_str());
        }
        output_functions.push_str("            if self.knowledges.is_none() {\r\n");
        output_functions.push_str(
            format!(
                "                if Self::already_acquired_{}(ctx, self.player_entity_id, {}) {{\r\n",
                n, id
            )
            .as_str(),
        );
        output_functions.push_str("                    return;\r\n");
        output_functions.push_str("                }\r\n");
        output_functions.push_str("                self.initialize(ctx);\r\n");
        output_functions.push_str("            }\r\n");
        output_functions.push_str(format!("            if self.has_acquired_{}({}) {{\r\n", n, id).as_str());
        output_functions.push_str("                return;\r\n");
        output_functions.push_str("            }\r\n");
        output_functions.push_str(format!("            if !self.has_discovered_{}({}) {{\r\n", n, id).as_str());
        output_functions.push_str(format!("                self.discover_{}(ctx, {});\r\n", n, id).as_str());
        output_functions.push_str("            }\r\n");
        output_functions.push_str("            let knowledges = self.knowledges.as_mut().unwrap();\r\n");
        output_functions.push_str(
            format!(
                "            if let Some(entry) = knowledges.knowledge_{}.iter_mut().find(|e| {}) {{\r\n",
                n, cmp
            )
            .as_str(),
        );
        output_functions.push_str("                entry.state = KnowledgeState::Acquired;\r\n");
        output_functions.push_str("            }\r\n");
        if has_callback {
            output_functions.push_str(format!("            self.on_{}_acquired(ctx, {});\r\n", n, id).as_str());
        }

        if has_achievement {
            output_functions.push_str("            self.acquired_achievement = true;\r\n");
        }
        output_functions.push_str("        }\r\n");
        output_functions.push_str("    }\r\n\r\n");

        output_discovery.push_str(format!("    pub knowledge_{}: Vec<{}>,\r\n", n, entry_type).as_str());
        output_discovery.push_str(format!("    pub knowledge_{}_hash: i32,\r\n", n).as_str());

        output_init.push_str(
            format!(
                "            knowledge_{}: ctx.db.{}().entity_id().find(player_entity_id).unwrap().entries.clone(),\r\n",
                n,
                camel_to_snake(&k)
            )
            .as_str(),
        );
        output_init.push_str(
            format!(
                "            knowledge_{}_hash: Self::{}(&ctx.db.{}().entity_id().find(player_entity_id).unwrap().entries),\r\n",
                n,
                hash_function,
                camel_to_snake(&k)
            )
            .as_str(),
        );

        output_commit.push_str(
            format!(
                "        let knowledge_{}_hash = Self::{}(&knowledges.knowledge_{});\r\n",
                n, hash_function, n
            )
            .as_str(),
        );
        output_commit.push_str(format!("        if knowledge_{}_hash != knowledges.knowledge_{}_hash {{\r\n", n, n).as_str());
        output_commit.push_str(format!("            knowledges.knowledge_{}_hash = knowledge_{}_hash;\r\n", n, n).as_str());
        output_commit.push_str(
            format!(
                "            let mut knowledge = ctx.db.{}().entity_id().find(player_entity_id).unwrap().clone();\r\n",
                camel_to_snake(&k)
            )
            .as_str(),
        );
        output_commit.push_str(format!("            knowledge.entries = knowledges.knowledge_{}.clone();\r\n", n).as_str());
        // uncomment this line to see updated knowledge arrays on commit
        // output_commit.push_str(format!("            println!(\"{}: {{:?}}\", knowledge.entries);\r\n", n).as_str());
        output_commit.push_str(format!("            ctx.db.{}().entity_id().update(knowledge);\r\n", camel_to_snake(&k)).as_str());

        if n == "secondary" {
            output_commit.push_str("            PlayerState::collect_stats(ctx, self.player_entity_id);\r\n");
        }

        output_commit.push_str("        }\r\n");

        output_generate_knowledges.push_str(
            format!(
                "    if ctx.db.{}().try_insert({} {{ entries: Vec::new(), entity_id }}).is_err() {{}}\r\n",
                camel_to_snake(&k),
                k
            )
            .as_str(),
        );
    }

    output_generate_knowledges.push_str("}\r\n\r\n");
    output_includes.push_str("\r\n");

    output_discovery.push_str("}\r\n\r\n");
    output_init.push_str("        });\r\n");
    output_init.push_str("    }\r\n\r\n");

    output_commit.push_str("        if self.acquired_achievement {\r\n");
    output_commit.push_str("            self.acquired_achievement = false;\r\n");
    output_commit.push_str("            AchievementDesc::evaluate_all(self.player_entity_id);\r\n");
    output_commit.push_str("        }\r\n");
    output_commit.push_str("    }\r\n\r\n");
    output_functions.push_str("}\r\n");

    let discovery_str =
        output_discovery + output_generate_knowledges.as_str() + output_init.as_str() + output_commit.as_str() + output_functions.as_str();

    write_if_file_changed("src/game/discovery/autogen/_discovery.rs", discovery_str);
}

fn camel_to_snake(str: &String) -> String {
    let mut output = String::new();
    for c in str.chars() {
        if c.is_uppercase() {
            if String::is_empty(&output) {
                output.push_str(c.to_ascii_lowercase().to_string().as_str());
            } else {
                output.push_str(format!("_{}", c.to_ascii_lowercase()).as_str());
            }
        } else {
            output.push_str(c.to_string().as_str());
        }
    }
    output
}

fn main() {
    build_shared::main_shared();
    build_knowledge();
}
