[package]
name = "stitch-bevy-client"
version = "0.1.0"
edition = "2021"

[features]
default = ["web-prod-webgpu"]
web-prod-webgpu = ["bevy/web", "bevy/webgpu", "bevy/3d", "bevy/ui"]
web-prod-webgl2 = ["bevy/web", "bevy/webgl2", "bevy/3d", "bevy/ui"]
native-dev = ["bevy/3d", "bevy/ui", "bevy/dev"]

[dependencies]
anyhow = "1"
bevy = { path = "../bevy", default-features = false }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"

