// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AgentTickArgs {
    pub request_id: String,
    pub agent_kind: u8,
    pub region_id: u64,
    pub payload: String,
}

impl From<AgentTickArgs> for super::Reducer {
    fn from(args: AgentTickArgs) -> Self {
        Self::AgentTick {
            request_id: args.request_id,
            agent_kind: args.agent_kind,
            region_id: args.region_id,
            payload: args.payload,
        }
    }
}

impl __sdk::InModule for AgentTickArgs {
    type Module = super::RemoteModule;
}

pub struct AgentTickCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `agent_tick`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait agent_tick {
    /// Request that the remote module invoke the reducer `agent_tick` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_agent_tick`] callbacks.
    fn agent_tick(
        &self,
        request_id: String,
        agent_kind: u8,
        region_id: u64,
        payload: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `agent_tick`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AgentTickCallbackId`] can be passed to [`Self::remove_on_agent_tick`]
    /// to cancel the callback.
    fn on_agent_tick(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &u8, &u64, &String) + Send + 'static,
    ) -> AgentTickCallbackId;
    /// Cancel a callback previously registered by [`Self::on_agent_tick`],
    /// causing it not to run in the future.
    fn remove_on_agent_tick(&self, callback: AgentTickCallbackId);
}

impl agent_tick for super::RemoteReducers {
    fn agent_tick(
        &self,
        request_id: String,
        agent_kind: u8,
        region_id: u64,
        payload: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "agent_tick",
            AgentTickArgs {
                request_id,
                agent_kind,
                region_id,
                payload,
            },
        )
    }
    fn on_agent_tick(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &u8, &u64, &String)
            + Send
            + 'static,
    ) -> AgentTickCallbackId {
        AgentTickCallbackId(self.imp.on_reducer(
            "agent_tick",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AgentTick {
                                    request_id,
                                    agent_kind,
                                    region_id,
                                    payload,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, request_id, agent_kind, region_id, payload)
            }),
        ))
    }
    fn remove_on_agent_tick(&self, callback: AgentTickCallbackId) {
        self.imp.remove_on_reducer("agent_tick", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `agent_tick`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_agent_tick {
    /// Set the call-reducer flags for the reducer `agent_tick` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn agent_tick(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_agent_tick for super::SetReducerFlags {
    fn agent_tick(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("agent_tick", flags);
    }
}
