// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AttackScheduled {
    pub request_key: String,
    pub attacker_identity: __sdk::Identity,
    pub target_identity: __sdk::Identity,
    pub region_id: u64,
    pub client_ts_ms: u64,
    pub impact_damage: i32,
    pub phase: u8,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for AttackScheduled {
    type Module = super::RemoteModule;
}
