// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::attack_scheduled_type::AttackScheduled;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `attack_schedule_state`.
///
/// Obtain a handle from the [`AttackScheduleStateTableAccess::attack_schedule_state`] method on [`super::RemoteTables`],
/// like `ctx.db.attack_schedule_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.attack_schedule_state().on_insert(...)`.
pub struct AttackScheduleStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<AttackScheduled>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `attack_schedule_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AttackScheduleStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AttackScheduleStateTableHandle`], which mediates access to the table `attack_schedule_state`.
    fn attack_schedule_state(&self) -> AttackScheduleStateTableHandle<'_>;
}

impl AttackScheduleStateTableAccess for super::RemoteTables {
    fn attack_schedule_state(&self) -> AttackScheduleStateTableHandle<'_> {
        AttackScheduleStateTableHandle {
            imp: self
                .imp
                .get_table::<AttackScheduled>("attack_schedule_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AttackScheduleStateInsertCallbackId(__sdk::CallbackId);
pub struct AttackScheduleStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AttackScheduleStateTableHandle<'ctx> {
    type Row = AttackScheduled;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AttackScheduled> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AttackScheduleStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AttackScheduleStateInsertCallbackId {
        AttackScheduleStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AttackScheduleStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AttackScheduleStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AttackScheduleStateDeleteCallbackId {
        AttackScheduleStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AttackScheduleStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AttackScheduled>("attack_schedule_state");
    _table.add_unique_constraint::<String>("request_key", |row| &row.request_key);
}
pub struct AttackScheduleStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AttackScheduleStateTableHandle<'ctx> {
    type UpdateCallbackId = AttackScheduleStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AttackScheduleStateUpdateCallbackId {
        AttackScheduleStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AttackScheduleStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<AttackScheduled>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AttackScheduled>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `request_key` unique index on the table `attack_schedule_state`,
/// which allows point queries on the field of the same name
/// via the [`AttackScheduleStateRequestKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.attack_schedule_state().request_key().find(...)`.
pub struct AttackScheduleStateRequestKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AttackScheduled, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AttackScheduleStateTableHandle<'ctx> {
    /// Get a handle on the `request_key` unique index on the table `attack_schedule_state`.
    pub fn request_key(&self) -> AttackScheduleStateRequestKeyUnique<'ctx> {
        AttackScheduleStateRequestKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("request_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AttackScheduleStateRequestKeyUnique<'ctx> {
    /// Find the subscribed row whose `request_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<AttackScheduled> {
        self.imp.find(col_val)
    }
}
