// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BalanceParams {
    pub param_key: String,
    pub int_value: i64,
    pub float_value: f64,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for BalanceParams {
    type Module = super::RemoteModule;
}
