// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BuildingDef {
    pub building_def_id: u64,
    pub required_item_def_id: u64,
    pub required_item_qty: u32,
    pub build_required: u32,
    pub footprint_radius: u32,
}

impl __sdk::InModule for BuildingDef {
    type Module = super::RemoteModule;
}
