// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ClaimState {
    pub claim_id: u64,
    pub owner_identity: __sdk::Identity,
    pub totem_building_id: u64,
    pub region_id: u64,
    pub center_x: i32,
    pub center_z: i32,
    pub radius: u32,
    pub tier: u32,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for ClaimState {
    type Module = super::RemoteModule;
}
