// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimExpandArgs {
    pub claim_id: u64,
    pub radius_delta: u32,
}

impl From<ClaimExpandArgs> for super::Reducer {
    fn from(args: ClaimExpandArgs) -> Self {
        Self::ClaimExpand {
            claim_id: args.claim_id,
            radius_delta: args.radius_delta,
        }
    }
}

impl __sdk::InModule for ClaimExpandArgs {
    type Module = super::RemoteModule;
}

pub struct ClaimExpandCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_expand`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_expand {
    /// Request that the remote module invoke the reducer `claim_expand` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_claim_expand`] callbacks.
    fn claim_expand(&self, claim_id: u64, radius_delta: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `claim_expand`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ClaimExpandCallbackId`] can be passed to [`Self::remove_on_claim_expand`]
    /// to cancel the callback.
    fn on_claim_expand(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &u32) + Send + 'static,
    ) -> ClaimExpandCallbackId;
    /// Cancel a callback previously registered by [`Self::on_claim_expand`],
    /// causing it not to run in the future.
    fn remove_on_claim_expand(&self, callback: ClaimExpandCallbackId);
}

impl claim_expand for super::RemoteReducers {
    fn claim_expand(&self, claim_id: u64, radius_delta: u32) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "claim_expand",
            ClaimExpandArgs {
                claim_id,
                radius_delta,
            },
        )
    }
    fn on_claim_expand(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &u32) + Send + 'static,
    ) -> ClaimExpandCallbackId {
        ClaimExpandCallbackId(self.imp.on_reducer(
            "claim_expand",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ClaimExpand {
                                    claim_id,
                                    radius_delta,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, claim_id, radius_delta)
            }),
        ))
    }
    fn remove_on_claim_expand(&self, callback: ClaimExpandCallbackId) {
        self.imp.remove_on_reducer("claim_expand", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `claim_expand`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_claim_expand {
    /// Set the call-reducer flags for the reducer `claim_expand` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn claim_expand(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_claim_expand for super::SetReducerFlags {
    fn claim_expand(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("claim_expand", flags);
    }
}
