// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::claim_state_type::ClaimState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `claim_state`.
///
/// Obtain a handle from the [`ClaimStateTableAccess::claim_state`] method on [`super::RemoteTables`],
/// like `ctx.db.claim_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claim_state().on_insert(...)`.
pub struct ClaimStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<ClaimState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `claim_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClaimStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClaimStateTableHandle`], which mediates access to the table `claim_state`.
    fn claim_state(&self) -> ClaimStateTableHandle<'_>;
}

impl ClaimStateTableAccess for super::RemoteTables {
    fn claim_state(&self) -> ClaimStateTableHandle<'_> {
        ClaimStateTableHandle {
            imp: self.imp.get_table::<ClaimState>("claim_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClaimStateInsertCallbackId(__sdk::CallbackId);
pub struct ClaimStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ClaimStateTableHandle<'ctx> {
    type Row = ClaimState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClaimState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClaimStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimStateInsertCallbackId {
        ClaimStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClaimStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClaimStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaimStateDeleteCallbackId {
        ClaimStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClaimStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ClaimState>("claim_state");
    _table.add_unique_constraint::<u64>("claim_id", |row| &row.claim_id);
}
pub struct ClaimStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClaimStateTableHandle<'ctx> {
    type UpdateCallbackId = ClaimStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClaimStateUpdateCallbackId {
        ClaimStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClaimStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ClaimState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ClaimState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `claim_id` unique index on the table `claim_state`,
/// which allows point queries on the field of the same name
/// via the [`ClaimStateClaimIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claim_state().claim_id().find(...)`.
pub struct ClaimStateClaimIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ClaimState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClaimStateTableHandle<'ctx> {
    /// Get a handle on the `claim_id` unique index on the table `claim_state`.
    pub fn claim_id(&self) -> ClaimStateClaimIdUnique<'ctx> {
        ClaimStateClaimIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("claim_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClaimStateClaimIdUnique<'ctx> {
    /// Find the subscribed row whose `claim_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ClaimState> {
        self.imp.find(col_val)
    }
}
