// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::currency_txn_type::CurrencyTxn;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `currency_txn`.
///
/// Obtain a handle from the [`CurrencyTxnTableAccess::currency_txn`] method on [`super::RemoteTables`],
/// like `ctx.db.currency_txn()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.currency_txn().on_insert(...)`.
pub struct CurrencyTxnTableHandle<'ctx> {
    imp: __sdk::TableHandle<CurrencyTxn>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `currency_txn`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CurrencyTxnTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CurrencyTxnTableHandle`], which mediates access to the table `currency_txn`.
    fn currency_txn(&self) -> CurrencyTxnTableHandle<'_>;
}

impl CurrencyTxnTableAccess for super::RemoteTables {
    fn currency_txn(&self) -> CurrencyTxnTableHandle<'_> {
        CurrencyTxnTableHandle {
            imp: self.imp.get_table::<CurrencyTxn>("currency_txn"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CurrencyTxnInsertCallbackId(__sdk::CallbackId);
pub struct CurrencyTxnDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CurrencyTxnTableHandle<'ctx> {
    type Row = CurrencyTxn;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CurrencyTxn> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CurrencyTxnInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CurrencyTxnInsertCallbackId {
        CurrencyTxnInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CurrencyTxnInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CurrencyTxnDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CurrencyTxnDeleteCallbackId {
        CurrencyTxnDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CurrencyTxnDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CurrencyTxn>("currency_txn");
    _table.add_unique_constraint::<u64>("txn_id", |row| &row.txn_id);
}
pub struct CurrencyTxnUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CurrencyTxnTableHandle<'ctx> {
    type UpdateCallbackId = CurrencyTxnUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CurrencyTxnUpdateCallbackId {
        CurrencyTxnUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CurrencyTxnUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CurrencyTxn>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CurrencyTxn>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `txn_id` unique index on the table `currency_txn`,
/// which allows point queries on the field of the same name
/// via the [`CurrencyTxnTxnIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.currency_txn().txn_id().find(...)`.
pub struct CurrencyTxnTxnIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CurrencyTxn, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CurrencyTxnTableHandle<'ctx> {
    /// Get a handle on the `txn_id` unique index on the table `currency_txn`.
    pub fn txn_id(&self) -> CurrencyTxnTxnIdUnique<'ctx> {
        CurrencyTxnTxnIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("txn_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CurrencyTxnTxnIdUnique<'ctx> {
    /// Find the subscribed row whose `txn_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CurrencyTxn> {
        self.imp.find(col_val)
    }
}
