// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EconomySetParamArgs {
    pub param_key: String,
    pub int_value: i64,
    pub float_value: f64,
}

impl From<EconomySetParamArgs> for super::Reducer {
    fn from(args: EconomySetParamArgs) -> Self {
        Self::EconomySetParam {
            param_key: args.param_key,
            int_value: args.int_value,
            float_value: args.float_value,
        }
    }
}

impl __sdk::InModule for EconomySetParamArgs {
    type Module = super::RemoteModule;
}

pub struct EconomySetParamCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `economy_set_param`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait economy_set_param {
    /// Request that the remote module invoke the reducer `economy_set_param` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_economy_set_param`] callbacks.
    fn economy_set_param(
        &self,
        param_key: String,
        int_value: i64,
        float_value: f64,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `economy_set_param`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EconomySetParamCallbackId`] can be passed to [`Self::remove_on_economy_set_param`]
    /// to cancel the callback.
    fn on_economy_set_param(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &i64, &f64) + Send + 'static,
    ) -> EconomySetParamCallbackId;
    /// Cancel a callback previously registered by [`Self::on_economy_set_param`],
    /// causing it not to run in the future.
    fn remove_on_economy_set_param(&self, callback: EconomySetParamCallbackId);
}

impl economy_set_param for super::RemoteReducers {
    fn economy_set_param(
        &self,
        param_key: String,
        int_value: i64,
        float_value: f64,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "economy_set_param",
            EconomySetParamArgs {
                param_key,
                int_value,
                float_value,
            },
        )
    }
    fn on_economy_set_param(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &i64, &f64) + Send + 'static,
    ) -> EconomySetParamCallbackId {
        EconomySetParamCallbackId(self.imp.on_reducer(
            "economy_set_param",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::EconomySetParam {
                                    param_key,
                                    int_value,
                                    float_value,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, param_key, int_value, float_value)
            }),
        ))
    }
    fn remove_on_economy_set_param(&self, callback: EconomySetParamCallbackId) {
        self.imp.remove_on_reducer("economy_set_param", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `economy_set_param`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_economy_set_param {
    /// Set the call-reducer flags for the reducer `economy_set_param` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn economy_set_param(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_economy_set_param for super::SetReducerFlags {
    fn economy_set_param(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("economy_set_param", flags);
    }
}
