// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EnvironmentEffectDesc {
    pub effect_id: u64,
    pub name: String,
    pub hazard_biome_id: u16,
    pub status_effect_id: u64,
    pub damage_per_tick: u32,
    pub exposure_per_tick: i32,
    pub max_exposure: i32,
    pub exposure_decay_per_tick: i32,
    pub resistance_level_required: u32,
    pub damage_interval_seconds: u32,
    pub enabled: bool,
}

impl __sdk::InModule for EnvironmentEffectDesc {
    type Module = super::RemoteModule;
}
