// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::feature_flags_type::FeatureFlags;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `feature_flags`.
///
/// Obtain a handle from the [`FeatureFlagsTableAccess::feature_flags`] method on [`super::RemoteTables`],
/// like `ctx.db.feature_flags()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.feature_flags().on_insert(...)`.
pub struct FeatureFlagsTableHandle<'ctx> {
    imp: __sdk::TableHandle<FeatureFlags>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `feature_flags`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FeatureFlagsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FeatureFlagsTableHandle`], which mediates access to the table `feature_flags`.
    fn feature_flags(&self) -> FeatureFlagsTableHandle<'_>;
}

impl FeatureFlagsTableAccess for super::RemoteTables {
    fn feature_flags(&self) -> FeatureFlagsTableHandle<'_> {
        FeatureFlagsTableHandle {
            imp: self.imp.get_table::<FeatureFlags>("feature_flags"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FeatureFlagsInsertCallbackId(__sdk::CallbackId);
pub struct FeatureFlagsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FeatureFlagsTableHandle<'ctx> {
    type Row = FeatureFlags;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FeatureFlags> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FeatureFlagsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FeatureFlagsInsertCallbackId {
        FeatureFlagsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FeatureFlagsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FeatureFlagsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FeatureFlagsDeleteCallbackId {
        FeatureFlagsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FeatureFlagsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FeatureFlags>("feature_flags");
    _table.add_unique_constraint::<String>("flag_key", |row| &row.flag_key);
}
pub struct FeatureFlagsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FeatureFlagsTableHandle<'ctx> {
    type UpdateCallbackId = FeatureFlagsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FeatureFlagsUpdateCallbackId {
        FeatureFlagsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FeatureFlagsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<FeatureFlags>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FeatureFlags>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `flag_key` unique index on the table `feature_flags`,
/// which allows point queries on the field of the same name
/// via the [`FeatureFlagsFlagKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.feature_flags().flag_key().find(...)`.
pub struct FeatureFlagsFlagKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FeatureFlags, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FeatureFlagsTableHandle<'ctx> {
    /// Get a handle on the `flag_key` unique index on the table `feature_flags`.
    pub fn flag_key(&self) -> FeatureFlagsFlagKeyUnique<'ctx> {
        FeatureFlagsFlagKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("flag_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FeatureFlagsFlagKeyUnique<'ctx> {
    /// Find the subscribed row whose `flag_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<FeatureFlags> {
        self.imp.find(col_val)
    }
}
