// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::friend_edge_type::FriendEdge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `friend_edge`.
///
/// Obtain a handle from the [`FriendEdgeTableAccess::friend_edge`] method on [`super::RemoteTables`],
/// like `ctx.db.friend_edge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.friend_edge().on_insert(...)`.
pub struct FriendEdgeTableHandle<'ctx> {
    imp: __sdk::TableHandle<FriendEdge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `friend_edge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FriendEdgeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FriendEdgeTableHandle`], which mediates access to the table `friend_edge`.
    fn friend_edge(&self) -> FriendEdgeTableHandle<'_>;
}

impl FriendEdgeTableAccess for super::RemoteTables {
    fn friend_edge(&self) -> FriendEdgeTableHandle<'_> {
        FriendEdgeTableHandle {
            imp: self.imp.get_table::<FriendEdge>("friend_edge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FriendEdgeInsertCallbackId(__sdk::CallbackId);
pub struct FriendEdgeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FriendEdgeTableHandle<'ctx> {
    type Row = FriendEdge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FriendEdge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FriendEdgeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FriendEdgeInsertCallbackId {
        FriendEdgeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FriendEdgeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FriendEdgeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FriendEdgeDeleteCallbackId {
        FriendEdgeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FriendEdgeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FriendEdge>("friend_edge");
    _table.add_unique_constraint::<String>("edge_key", |row| &row.edge_key);
}
pub struct FriendEdgeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FriendEdgeTableHandle<'ctx> {
    type UpdateCallbackId = FriendEdgeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FriendEdgeUpdateCallbackId {
        FriendEdgeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FriendEdgeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<FriendEdge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FriendEdge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `edge_key` unique index on the table `friend_edge`,
/// which allows point queries on the field of the same name
/// via the [`FriendEdgeEdgeKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.friend_edge().edge_key().find(...)`.
pub struct FriendEdgeEdgeKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FriendEdge, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FriendEdgeTableHandle<'ctx> {
    /// Get a handle on the `edge_key` unique index on the table `friend_edge`.
    pub fn edge_key(&self) -> FriendEdgeEdgeKeyUnique<'ctx> {
        FriendEdgeEdgeKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("edge_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FriendEdgeEdgeKeyUnique<'ctx> {
    /// Find the subscribed row whose `edge_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<FriendEdge> {
        self.imp.find(col_val)
    }
}
