// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GuildCreateArgs {
    pub guild_id: String,
    pub name: String,
}

impl From<GuildCreateArgs> for super::Reducer {
    fn from(args: GuildCreateArgs) -> Self {
        Self::GuildCreate {
            guild_id: args.guild_id,
            name: args.name,
        }
    }
}

impl __sdk::InModule for GuildCreateArgs {
    type Module = super::RemoteModule;
}

pub struct GuildCreateCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `guild_create`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait guild_create {
    /// Request that the remote module invoke the reducer `guild_create` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_guild_create`] callbacks.
    fn guild_create(&self, guild_id: String, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `guild_create`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`GuildCreateCallbackId`] can be passed to [`Self::remove_on_guild_create`]
    /// to cancel the callback.
    fn on_guild_create(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> GuildCreateCallbackId;
    /// Cancel a callback previously registered by [`Self::on_guild_create`],
    /// causing it not to run in the future.
    fn remove_on_guild_create(&self, callback: GuildCreateCallbackId);
}

impl guild_create for super::RemoteReducers {
    fn guild_create(&self, guild_id: String, name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("guild_create", GuildCreateArgs { guild_id, name })
    }
    fn on_guild_create(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> GuildCreateCallbackId {
        GuildCreateCallbackId(self.imp.on_reducer(
            "guild_create",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::GuildCreate { guild_id, name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, guild_id, name)
            }),
        ))
    }
    fn remove_on_guild_create(&self, callback: GuildCreateCallbackId) {
        self.imp.remove_on_reducer("guild_create", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `guild_create`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_guild_create {
    /// Set the call-reducer flags for the reducer `guild_create` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn guild_create(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_guild_create for super::SetReducerFlags {
    fn guild_create(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("guild_create", flags);
    }
}
