// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HousingChangeEntranceArgs {
    pub housing_entity_id: u64,
    pub new_entrance_building_entity_id: u64,
    pub target_region_index: u32,
    pub moving_minutes: i32,
}

impl From<HousingChangeEntranceArgs> for super::Reducer {
    fn from(args: HousingChangeEntranceArgs) -> Self {
        Self::HousingChangeEntrance {
            housing_entity_id: args.housing_entity_id,
            new_entrance_building_entity_id: args.new_entrance_building_entity_id,
            target_region_index: args.target_region_index,
            moving_minutes: args.moving_minutes,
        }
    }
}

impl __sdk::InModule for HousingChangeEntranceArgs {
    type Module = super::RemoteModule;
}

pub struct HousingChangeEntranceCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `housing_change_entrance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait housing_change_entrance {
    /// Request that the remote module invoke the reducer `housing_change_entrance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_housing_change_entrance`] callbacks.
    fn housing_change_entrance(
        &self,
        housing_entity_id: u64,
        new_entrance_building_entity_id: u64,
        target_region_index: u32,
        moving_minutes: i32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `housing_change_entrance`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`HousingChangeEntranceCallbackId`] can be passed to [`Self::remove_on_housing_change_entrance`]
    /// to cancel the callback.
    fn on_housing_change_entrance(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &u64, &u32, &i32) + Send + 'static,
    ) -> HousingChangeEntranceCallbackId;
    /// Cancel a callback previously registered by [`Self::on_housing_change_entrance`],
    /// causing it not to run in the future.
    fn remove_on_housing_change_entrance(&self, callback: HousingChangeEntranceCallbackId);
}

impl housing_change_entrance for super::RemoteReducers {
    fn housing_change_entrance(
        &self,
        housing_entity_id: u64,
        new_entrance_building_entity_id: u64,
        target_region_index: u32,
        moving_minutes: i32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "housing_change_entrance",
            HousingChangeEntranceArgs {
                housing_entity_id,
                new_entrance_building_entity_id,
                target_region_index,
                moving_minutes,
            },
        )
    }
    fn on_housing_change_entrance(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &u64, &u32, &i32) + Send + 'static,
    ) -> HousingChangeEntranceCallbackId {
        HousingChangeEntranceCallbackId(self.imp.on_reducer(
            "housing_change_entrance",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::HousingChangeEntrance {
                                    housing_entity_id,
                                    new_entrance_building_entity_id,
                                    target_region_index,
                                    moving_minutes,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    housing_entity_id,
                    new_entrance_building_entity_id,
                    target_region_index,
                    moving_minutes,
                )
            }),
        ))
    }
    fn remove_on_housing_change_entrance(&self, callback: HousingChangeEntranceCallbackId) {
        self.imp
            .remove_on_reducer("housing_change_entrance", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `housing_change_entrance`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_housing_change_entrance {
    /// Set the call-reducer flags for the reducer `housing_change_entrance` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn housing_change_entrance(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_housing_change_entrance for super::SetReducerFlags {
    fn housing_change_entrance(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("housing_change_entrance", flags);
    }
}
