// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HousingEnterArgs {
    pub housing_entity_id: u64,
    pub portal_x: f32,
    pub portal_y: f32,
    pub portal_z: f32,
}

impl From<HousingEnterArgs> for super::Reducer {
    fn from(args: HousingEnterArgs) -> Self {
        Self::HousingEnter {
            housing_entity_id: args.housing_entity_id,
            portal_x: args.portal_x,
            portal_y: args.portal_y,
            portal_z: args.portal_z,
        }
    }
}

impl __sdk::InModule for HousingEnterArgs {
    type Module = super::RemoteModule;
}

pub struct HousingEnterCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `housing_enter`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait housing_enter {
    /// Request that the remote module invoke the reducer `housing_enter` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_housing_enter`] callbacks.
    fn housing_enter(
        &self,
        housing_entity_id: u64,
        portal_x: f32,
        portal_y: f32,
        portal_z: f32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `housing_enter`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`HousingEnterCallbackId`] can be passed to [`Self::remove_on_housing_enter`]
    /// to cancel the callback.
    fn on_housing_enter(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &f32, &f32, &f32) + Send + 'static,
    ) -> HousingEnterCallbackId;
    /// Cancel a callback previously registered by [`Self::on_housing_enter`],
    /// causing it not to run in the future.
    fn remove_on_housing_enter(&self, callback: HousingEnterCallbackId);
}

impl housing_enter for super::RemoteReducers {
    fn housing_enter(
        &self,
        housing_entity_id: u64,
        portal_x: f32,
        portal_y: f32,
        portal_z: f32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "housing_enter",
            HousingEnterArgs {
                housing_entity_id,
                portal_x,
                portal_y,
                portal_z,
            },
        )
    }
    fn on_housing_enter(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &f32, &f32, &f32) + Send + 'static,
    ) -> HousingEnterCallbackId {
        HousingEnterCallbackId(self.imp.on_reducer(
            "housing_enter",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::HousingEnter {
                                    housing_entity_id,
                                    portal_x,
                                    portal_y,
                                    portal_z,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, housing_entity_id, portal_x, portal_y, portal_z)
            }),
        ))
    }
    fn remove_on_housing_enter(&self, callback: HousingEnterCallbackId) {
        self.imp.remove_on_reducer("housing_enter", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `housing_enter`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_housing_enter {
    /// Set the call-reducer flags for the reducer `housing_enter` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn housing_enter(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_housing_enter for super::SetReducerFlags {
    fn housing_enter(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("housing_enter", flags);
    }
}
