// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ImportCsvDataArgs {}

impl From<ImportCsvDataArgs> for super::Reducer {
    fn from(args: ImportCsvDataArgs) -> Self {
        Self::ImportCsvData
    }
}

impl __sdk::InModule for ImportCsvDataArgs {
    type Module = super::RemoteModule;
}

pub struct ImportCsvDataCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `import_csv_data`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait import_csv_data {
    /// Request that the remote module invoke the reducer `import_csv_data` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_import_csv_data`] callbacks.
    fn import_csv_data(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `import_csv_data`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ImportCsvDataCallbackId`] can be passed to [`Self::remove_on_import_csv_data`]
    /// to cancel the callback.
    fn on_import_csv_data(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ImportCsvDataCallbackId;
    /// Cancel a callback previously registered by [`Self::on_import_csv_data`],
    /// causing it not to run in the future.
    fn remove_on_import_csv_data(&self, callback: ImportCsvDataCallbackId);
}

impl import_csv_data for super::RemoteReducers {
    fn import_csv_data(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("import_csv_data", ImportCsvDataArgs {})
    }
    fn on_import_csv_data(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ImportCsvDataCallbackId {
        ImportCsvDataCallbackId(self.imp.on_reducer(
            "import_csv_data",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ImportCsvData {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_import_csv_data(&self, callback: ImportCsvDataCallbackId) {
        self.imp.remove_on_reducer("import_csv_data", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `import_csv_data`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_import_csv_data {
    /// Set the call-reducer flags for the reducer `import_csv_data` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn import_csv_data(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_import_csv_data for super::SetReducerFlags {
    fn import_csv_data(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("import_csv_data", flags);
    }
}
