// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InteriorMarkEmptyArgs {
    pub housing_entity_id: u64,
    pub is_empty: bool,
    pub respawn_delay_seconds: u32,
}

impl From<InteriorMarkEmptyArgs> for super::Reducer {
    fn from(args: InteriorMarkEmptyArgs) -> Self {
        Self::InteriorMarkEmpty {
            housing_entity_id: args.housing_entity_id,
            is_empty: args.is_empty,
            respawn_delay_seconds: args.respawn_delay_seconds,
        }
    }
}

impl __sdk::InModule for InteriorMarkEmptyArgs {
    type Module = super::RemoteModule;
}

pub struct InteriorMarkEmptyCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `interior_mark_empty`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait interior_mark_empty {
    /// Request that the remote module invoke the reducer `interior_mark_empty` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_interior_mark_empty`] callbacks.
    fn interior_mark_empty(
        &self,
        housing_entity_id: u64,
        is_empty: bool,
        respawn_delay_seconds: u32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `interior_mark_empty`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`InteriorMarkEmptyCallbackId`] can be passed to [`Self::remove_on_interior_mark_empty`]
    /// to cancel the callback.
    fn on_interior_mark_empty(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &bool, &u32) + Send + 'static,
    ) -> InteriorMarkEmptyCallbackId;
    /// Cancel a callback previously registered by [`Self::on_interior_mark_empty`],
    /// causing it not to run in the future.
    fn remove_on_interior_mark_empty(&self, callback: InteriorMarkEmptyCallbackId);
}

impl interior_mark_empty for super::RemoteReducers {
    fn interior_mark_empty(
        &self,
        housing_entity_id: u64,
        is_empty: bool,
        respawn_delay_seconds: u32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "interior_mark_empty",
            InteriorMarkEmptyArgs {
                housing_entity_id,
                is_empty,
                respawn_delay_seconds,
            },
        )
    }
    fn on_interior_mark_empty(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &bool, &u32) + Send + 'static,
    ) -> InteriorMarkEmptyCallbackId {
        InteriorMarkEmptyCallbackId(self.imp.on_reducer(
            "interior_mark_empty",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::InteriorMarkEmpty {
                                    housing_entity_id,
                                    is_empty,
                                    respawn_delay_seconds,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, housing_entity_id, is_empty, respawn_delay_seconds)
            }),
        ))
    }
    fn remove_on_interior_mark_empty(&self, callback: InteriorMarkEmptyCallbackId) {
        self.imp
            .remove_on_reducer("interior_mark_empty", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `interior_mark_empty`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_interior_mark_empty {
    /// Set the call-reducer flags for the reducer `interior_mark_empty` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn interior_mark_empty(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_interior_mark_empty for super::SetReducerFlags {
    fn interior_mark_empty(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("interior_mark_empty", flags);
    }
}
