// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcPolicyViolation {
    pub violation_id: u64,
    pub npc_id: u64,
    pub player_identity: __sdk::Identity,
    pub reason: String,
    pub severity: u8,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for NpcPolicyViolation {
    type Module = super::RemoteModule;
}
