// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_cost_metrics_type::NpcCostMetrics;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_cost_metrics`.
///
/// Obtain a handle from the [`NpcCostMetricsTableAccess::npc_cost_metrics`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_cost_metrics()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_cost_metrics().on_insert(...)`.
pub struct NpcCostMetricsTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcCostMetrics>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_cost_metrics`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcCostMetricsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcCostMetricsTableHandle`], which mediates access to the table `npc_cost_metrics`.
    fn npc_cost_metrics(&self) -> NpcCostMetricsTableHandle<'_>;
}

impl NpcCostMetricsTableAccess for super::RemoteTables {
    fn npc_cost_metrics(&self) -> NpcCostMetricsTableHandle<'_> {
        NpcCostMetricsTableHandle {
            imp: self.imp.get_table::<NpcCostMetrics>("npc_cost_metrics"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcCostMetricsInsertCallbackId(__sdk::CallbackId);
pub struct NpcCostMetricsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcCostMetricsTableHandle<'ctx> {
    type Row = NpcCostMetrics;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcCostMetrics> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcCostMetricsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcCostMetricsInsertCallbackId {
        NpcCostMetricsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcCostMetricsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcCostMetricsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcCostMetricsDeleteCallbackId {
        NpcCostMetricsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcCostMetricsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcCostMetrics>("npc_cost_metrics");
    _table.add_unique_constraint::<u64>("metric_id", |row| &row.metric_id);
}
pub struct NpcCostMetricsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcCostMetricsTableHandle<'ctx> {
    type UpdateCallbackId = NpcCostMetricsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcCostMetricsUpdateCallbackId {
        NpcCostMetricsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcCostMetricsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<NpcCostMetrics>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcCostMetrics>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `metric_id` unique index on the table `npc_cost_metrics`,
/// which allows point queries on the field of the same name
/// via the [`NpcCostMetricsMetricIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_cost_metrics().metric_id().find(...)`.
pub struct NpcCostMetricsMetricIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcCostMetrics, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcCostMetricsTableHandle<'ctx> {
    /// Get a handle on the `metric_id` unique index on the table `npc_cost_metrics`.
    pub fn metric_id(&self) -> NpcCostMetricsMetricIdUnique<'ctx> {
        NpcCostMetricsMetricIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("metric_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcCostMetricsMetricIdUnique<'ctx> {
    /// Find the subscribed row whose `metric_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcCostMetrics> {
        self.imp.find(col_val)
    }
}
