// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct NpcTradeArgs {
    pub npc_id: u64,
    pub request_id: String,
}

impl From<NpcTradeArgs> for super::Reducer {
    fn from(args: NpcTradeArgs) -> Self {
        Self::NpcTrade {
            npc_id: args.npc_id,
            request_id: args.request_id,
        }
    }
}

impl __sdk::InModule for NpcTradeArgs {
    type Module = super::RemoteModule;
}

pub struct NpcTradeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `npc_trade`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait npc_trade {
    /// Request that the remote module invoke the reducer `npc_trade` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_npc_trade`] callbacks.
    fn npc_trade(&self, npc_id: u64, request_id: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `npc_trade`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`NpcTradeCallbackId`] can be passed to [`Self::remove_on_npc_trade`]
    /// to cancel the callback.
    fn on_npc_trade(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> NpcTradeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_npc_trade`],
    /// causing it not to run in the future.
    fn remove_on_npc_trade(&self, callback: NpcTradeCallbackId);
}

impl npc_trade for super::RemoteReducers {
    fn npc_trade(&self, npc_id: u64, request_id: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("npc_trade", NpcTradeArgs { npc_id, request_id })
    }
    fn on_npc_trade(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> NpcTradeCallbackId {
        NpcTradeCallbackId(self.imp.on_reducer(
            "npc_trade",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::NpcTrade { npc_id, request_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, npc_id, request_id)
            }),
        ))
    }
    fn remove_on_npc_trade(&self, callback: NpcTradeCallbackId) {
        self.imp.remove_on_reducer("npc_trade", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `npc_trade`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_npc_trade {
    /// Set the call-reducer flags for the reducer `npc_trade` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn npc_trade(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_npc_trade for super::SetReducerFlags {
    fn npc_trade(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("npc_trade", flags);
    }
}
