// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_relation_type::NpcRelation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_relation`.
///
/// Obtain a handle from the [`NpcRelationTableAccess::npc_relation`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_relation()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_relation().on_insert(...)`.
pub struct NpcRelationTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcRelation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_relation`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcRelationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcRelationTableHandle`], which mediates access to the table `npc_relation`.
    fn npc_relation(&self) -> NpcRelationTableHandle<'_>;
}

impl NpcRelationTableAccess for super::RemoteTables {
    fn npc_relation(&self) -> NpcRelationTableHandle<'_> {
        NpcRelationTableHandle {
            imp: self.imp.get_table::<NpcRelation>("npc_relation"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcRelationInsertCallbackId(__sdk::CallbackId);
pub struct NpcRelationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcRelationTableHandle<'ctx> {
    type Row = NpcRelation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcRelation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcRelationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcRelationInsertCallbackId {
        NpcRelationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcRelationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcRelationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcRelationDeleteCallbackId {
        NpcRelationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcRelationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcRelation>("npc_relation");
    _table.add_unique_constraint::<String>("relation_key", |row| &row.relation_key);
}
pub struct NpcRelationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcRelationTableHandle<'ctx> {
    type UpdateCallbackId = NpcRelationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcRelationUpdateCallbackId {
        NpcRelationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcRelationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<NpcRelation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcRelation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `relation_key` unique index on the table `npc_relation`,
/// which allows point queries on the field of the same name
/// via the [`NpcRelationRelationKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_relation().relation_key().find(...)`.
pub struct NpcRelationRelationKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcRelation, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcRelationTableHandle<'ctx> {
    /// Get a handle on the `relation_key` unique index on the table `npc_relation`.
    pub fn relation_key(&self) -> NpcRelationRelationKeyUnique<'ctx> {
        NpcRelationRelationKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("relation_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcRelationRelationKeyUnique<'ctx> {
    /// Find the subscribed row whose `relation_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<NpcRelation> {
        self.imp.find(col_val)
    }
}
