// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_conversation_session_type::NpcConversationSession;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_conversation_session`.
///
/// Obtain a handle from the [`NpcConversationSessionTableAccess::npc_conversation_session`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_conversation_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_conversation_session().on_insert(...)`.
pub struct NpcConversationSessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcConversationSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_conversation_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcConversationSessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcConversationSessionTableHandle`], which mediates access to the table `npc_conversation_session`.
    fn npc_conversation_session(&self) -> NpcConversationSessionTableHandle<'_>;
}

impl NpcConversationSessionTableAccess for super::RemoteTables {
    fn npc_conversation_session(&self) -> NpcConversationSessionTableHandle<'_> {
        NpcConversationSessionTableHandle {
            imp: self
                .imp
                .get_table::<NpcConversationSession>("npc_conversation_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcConversationSessionInsertCallbackId(__sdk::CallbackId);
pub struct NpcConversationSessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcConversationSessionTableHandle<'ctx> {
    type Row = NpcConversationSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcConversationSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcConversationSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcConversationSessionInsertCallbackId {
        NpcConversationSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcConversationSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcConversationSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcConversationSessionDeleteCallbackId {
        NpcConversationSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcConversationSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<NpcConversationSession>("npc_conversation_session");
    _table.add_unique_constraint::<String>("session_id", |row| &row.session_id);
}
pub struct NpcConversationSessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcConversationSessionTableHandle<'ctx> {
    type UpdateCallbackId = NpcConversationSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcConversationSessionUpdateCallbackId {
        NpcConversationSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcConversationSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<NpcConversationSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcConversationSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `session_id` unique index on the table `npc_conversation_session`,
/// which allows point queries on the field of the same name
/// via the [`NpcConversationSessionSessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_conversation_session().session_id().find(...)`.
pub struct NpcConversationSessionSessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcConversationSession, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcConversationSessionTableHandle<'ctx> {
    /// Get a handle on the `session_id` unique index on the table `npc_conversation_session`.
    pub fn session_id(&self) -> NpcConversationSessionSessionIdUnique<'ctx> {
        NpcConversationSessionSessionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("session_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcConversationSessionSessionIdUnique<'ctx> {
    /// Find the subscribed row whose `session_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<NpcConversationSession> {
        self.imp.find(col_val)
    }
}
