// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::quest_state_type::QuestState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `quest_state`.
///
/// Obtain a handle from the [`QuestStateTableAccess::quest_state`] method on [`super::RemoteTables`],
/// like `ctx.db.quest_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quest_state().on_insert(...)`.
pub struct QuestStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<QuestState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `quest_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait QuestStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`QuestStateTableHandle`], which mediates access to the table `quest_state`.
    fn quest_state(&self) -> QuestStateTableHandle<'_>;
}

impl QuestStateTableAccess for super::RemoteTables {
    fn quest_state(&self) -> QuestStateTableHandle<'_> {
        QuestStateTableHandle {
            imp: self.imp.get_table::<QuestState>("quest_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct QuestStateInsertCallbackId(__sdk::CallbackId);
pub struct QuestStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for QuestStateTableHandle<'ctx> {
    type Row = QuestState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = QuestState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = QuestStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuestStateInsertCallbackId {
        QuestStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: QuestStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = QuestStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuestStateDeleteCallbackId {
        QuestStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: QuestStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<QuestState>("quest_state");
    _table.add_unique_constraint::<String>("quest_key", |row| &row.quest_key);
}
pub struct QuestStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for QuestStateTableHandle<'ctx> {
    type UpdateCallbackId = QuestStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> QuestStateUpdateCallbackId {
        QuestStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: QuestStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<QuestState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<QuestState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `quest_key` unique index on the table `quest_state`,
/// which allows point queries on the field of the same name
/// via the [`QuestStateQuestKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quest_state().quest_key().find(...)`.
pub struct QuestStateQuestKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<QuestState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> QuestStateTableHandle<'ctx> {
    /// Get a handle on the `quest_key` unique index on the table `quest_state`.
    pub fn quest_key(&self) -> QuestStateQuestKeyUnique<'ctx> {
        QuestStateQuestKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("quest_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> QuestStateQuestKeyUnique<'ctx> {
    /// Find the subscribed row whose `quest_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<QuestState> {
        self.imp.find(col_val)
    }
}
