// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::quest_stage_state_type::QuestStageState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `quest_stage_state`.
///
/// Obtain a handle from the [`QuestStageStateTableAccess::quest_stage_state`] method on [`super::RemoteTables`],
/// like `ctx.db.quest_stage_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quest_stage_state().on_insert(...)`.
pub struct QuestStageStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<QuestStageState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `quest_stage_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait QuestStageStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`QuestStageStateTableHandle`], which mediates access to the table `quest_stage_state`.
    fn quest_stage_state(&self) -> QuestStageStateTableHandle<'_>;
}

impl QuestStageStateTableAccess for super::RemoteTables {
    fn quest_stage_state(&self) -> QuestStageStateTableHandle<'_> {
        QuestStageStateTableHandle {
            imp: self.imp.get_table::<QuestStageState>("quest_stage_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct QuestStageStateInsertCallbackId(__sdk::CallbackId);
pub struct QuestStageStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for QuestStageStateTableHandle<'ctx> {
    type Row = QuestStageState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = QuestStageState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = QuestStageStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuestStageStateInsertCallbackId {
        QuestStageStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: QuestStageStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = QuestStageStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuestStageStateDeleteCallbackId {
        QuestStageStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: QuestStageStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<QuestStageState>("quest_stage_state");
    _table.add_unique_constraint::<String>("stage_key", |row| &row.stage_key);
}
pub struct QuestStageStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for QuestStageStateTableHandle<'ctx> {
    type UpdateCallbackId = QuestStageStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> QuestStageStateUpdateCallbackId {
        QuestStageStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: QuestStageStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<QuestStageState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<QuestStageState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `stage_key` unique index on the table `quest_stage_state`,
/// which allows point queries on the field of the same name
/// via the [`QuestStageStateStageKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.quest_stage_state().stage_key().find(...)`.
pub struct QuestStageStateStageKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<QuestStageState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> QuestStageStateTableHandle<'ctx> {
    /// Get a handle on the `stage_key` unique index on the table `quest_stage_state`.
    pub fn stage_key(&self) -> QuestStageStateStageKeyUnique<'ctx> {
        QuestStageStateStageKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("stage_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> QuestStageStateStageKeyUnique<'ctx> {
    /// Find the subscribed row whose `stage_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<QuestStageState> {
        self.imp.find(col_val)
    }
}
