// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReportReviewArgs {
    pub report_id: u64,
    pub mark_valid: bool,
    pub reason: String,
    pub close_report: bool,
}

impl From<ReportReviewArgs> for super::Reducer {
    fn from(args: ReportReviewArgs) -> Self {
        Self::ReportReview {
            report_id: args.report_id,
            mark_valid: args.mark_valid,
            reason: args.reason,
            close_report: args.close_report,
        }
    }
}

impl __sdk::InModule for ReportReviewArgs {
    type Module = super::RemoteModule;
}

pub struct ReportReviewCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `report_review`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait report_review {
    /// Request that the remote module invoke the reducer `report_review` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_report_review`] callbacks.
    fn report_review(
        &self,
        report_id: u64,
        mark_valid: bool,
        reason: String,
        close_report: bool,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `report_review`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ReportReviewCallbackId`] can be passed to [`Self::remove_on_report_review`]
    /// to cancel the callback.
    fn on_report_review(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &bool, &String, &bool) + Send + 'static,
    ) -> ReportReviewCallbackId;
    /// Cancel a callback previously registered by [`Self::on_report_review`],
    /// causing it not to run in the future.
    fn remove_on_report_review(&self, callback: ReportReviewCallbackId);
}

impl report_review for super::RemoteReducers {
    fn report_review(
        &self,
        report_id: u64,
        mark_valid: bool,
        reason: String,
        close_report: bool,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "report_review",
            ReportReviewArgs {
                report_id,
                mark_valid,
                reason,
                close_report,
            },
        )
    }
    fn on_report_review(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &bool, &String, &bool)
            + Send
            + 'static,
    ) -> ReportReviewCallbackId {
        ReportReviewCallbackId(self.imp.on_reducer(
            "report_review",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ReportReview {
                                    report_id,
                                    mark_valid,
                                    reason,
                                    close_report,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, report_id, mark_valid, reason, close_report)
            }),
        ))
    }
    fn remove_on_report_review(&self, callback: ReportReviewCallbackId) {
        self.imp.remove_on_reducer("report_review", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `report_review`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_report_review {
    /// Set the call-reducer flags for the reducer `report_review` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn report_review(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_report_review for super::SetReducerFlags {
    fn report_review(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("report_review", flags);
    }
}
