// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReportSubmitArgs {
    pub target_identity: __sdk::Identity,
    pub report_type: String,
    pub payload: String,
}

impl From<ReportSubmitArgs> for super::Reducer {
    fn from(args: ReportSubmitArgs) -> Self {
        Self::ReportSubmit {
            target_identity: args.target_identity,
            report_type: args.report_type,
            payload: args.payload,
        }
    }
}

impl __sdk::InModule for ReportSubmitArgs {
    type Module = super::RemoteModule;
}

pub struct ReportSubmitCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `report_submit`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait report_submit {
    /// Request that the remote module invoke the reducer `report_submit` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_report_submit`] callbacks.
    fn report_submit(
        &self,
        target_identity: __sdk::Identity,
        report_type: String,
        payload: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `report_submit`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ReportSubmitCallbackId`] can be passed to [`Self::remove_on_report_submit`]
    /// to cancel the callback.
    fn on_report_submit(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &String, &String)
            + Send
            + 'static,
    ) -> ReportSubmitCallbackId;
    /// Cancel a callback previously registered by [`Self::on_report_submit`],
    /// causing it not to run in the future.
    fn remove_on_report_submit(&self, callback: ReportSubmitCallbackId);
}

impl report_submit for super::RemoteReducers {
    fn report_submit(
        &self,
        target_identity: __sdk::Identity,
        report_type: String,
        payload: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "report_submit",
            ReportSubmitArgs {
                target_identity,
                report_type,
                payload,
            },
        )
    }
    fn on_report_submit(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &String, &String)
            + Send
            + 'static,
    ) -> ReportSubmitCallbackId {
        ReportSubmitCallbackId(self.imp.on_reducer(
            "report_submit",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ReportSubmit {
                                    target_identity,
                                    report_type,
                                    payload,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, target_identity, report_type, payload)
            }),
        ))
    }
    fn remove_on_report_submit(&self, callback: ReportSubmitCallbackId) {
        self.imp.remove_on_reducer("report_submit", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `report_submit`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_report_submit {
    /// Set the call-reducer flags for the reducer `report_submit` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn report_submit(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_report_submit for super::SetReducerFlags {
    fn report_submit(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("report_submit", flags);
    }
}
