// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::role_binding_type::RoleBinding;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `role_binding`.
///
/// Obtain a handle from the [`RoleBindingTableAccess::role_binding`] method on [`super::RemoteTables`],
/// like `ctx.db.role_binding()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.role_binding().on_insert(...)`.
pub struct RoleBindingTableHandle<'ctx> {
    imp: __sdk::TableHandle<RoleBinding>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `role_binding`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RoleBindingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RoleBindingTableHandle`], which mediates access to the table `role_binding`.
    fn role_binding(&self) -> RoleBindingTableHandle<'_>;
}

impl RoleBindingTableAccess for super::RemoteTables {
    fn role_binding(&self) -> RoleBindingTableHandle<'_> {
        RoleBindingTableHandle {
            imp: self.imp.get_table::<RoleBinding>("role_binding"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RoleBindingInsertCallbackId(__sdk::CallbackId);
pub struct RoleBindingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RoleBindingTableHandle<'ctx> {
    type Row = RoleBinding;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoleBinding> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RoleBindingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoleBindingInsertCallbackId {
        RoleBindingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RoleBindingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RoleBindingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoleBindingDeleteCallbackId {
        RoleBindingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RoleBindingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RoleBinding>("role_binding");
    _table.add_unique_constraint::<String>("binding_id", |row| &row.binding_id);
}
pub struct RoleBindingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RoleBindingTableHandle<'ctx> {
    type UpdateCallbackId = RoleBindingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RoleBindingUpdateCallbackId {
        RoleBindingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RoleBindingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<RoleBinding>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RoleBinding>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `binding_id` unique index on the table `role_binding`,
/// which allows point queries on the field of the same name
/// via the [`RoleBindingBindingIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.role_binding().binding_id().find(...)`.
pub struct RoleBindingBindingIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RoleBinding, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RoleBindingTableHandle<'ctx> {
    /// Get a handle on the `binding_id` unique index on the table `role_binding`.
    pub fn binding_id(&self) -> RoleBindingBindingIdUnique<'ctx> {
        RoleBindingBindingIdUnique {
            imp: self.imp.get_unique_constraint::<String>("binding_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RoleBindingBindingIdUnique<'ctx> {
    /// Find the subscribed row whose `binding_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<RoleBinding> {
        self.imp.find(col_val)
    }
}
