// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RoleGrantArgs {
    pub target_identity: __sdk::Identity,
    pub role: String,
}

impl From<RoleGrantArgs> for super::Reducer {
    fn from(args: RoleGrantArgs) -> Self {
        Self::RoleGrant {
            target_identity: args.target_identity,
            role: args.role,
        }
    }
}

impl __sdk::InModule for RoleGrantArgs {
    type Module = super::RemoteModule;
}

pub struct RoleGrantCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `role_grant`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait role_grant {
    /// Request that the remote module invoke the reducer `role_grant` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_role_grant`] callbacks.
    fn role_grant(&self, target_identity: __sdk::Identity, role: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `role_grant`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RoleGrantCallbackId`] can be passed to [`Self::remove_on_role_grant`]
    /// to cancel the callback.
    fn on_role_grant(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &String) + Send + 'static,
    ) -> RoleGrantCallbackId;
    /// Cancel a callback previously registered by [`Self::on_role_grant`],
    /// causing it not to run in the future.
    fn remove_on_role_grant(&self, callback: RoleGrantCallbackId);
}

impl role_grant for super::RemoteReducers {
    fn role_grant(&self, target_identity: __sdk::Identity, role: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "role_grant",
            RoleGrantArgs {
                target_identity,
                role,
            },
        )
    }
    fn on_role_grant(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &String)
            + Send
            + 'static,
    ) -> RoleGrantCallbackId {
        RoleGrantCallbackId(self.imp.on_reducer(
            "role_grant",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::RoleGrant {
                                    target_identity,
                                    role,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, target_identity, role)
            }),
        ))
    }
    fn remove_on_role_grant(&self, callback: RoleGrantCallbackId) {
        self.imp.remove_on_reducer("role_grant", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `role_grant`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_role_grant {
    /// Set the call-reducer flags for the reducer `role_grant` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn role_grant(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_role_grant for super::SetReducerFlags {
    fn role_grant(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("role_grant", flags);
    }
}
