// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::session_cleanup_loop_timer_type::SessionCleanupLoopTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SessionCleanupAgentLoopArgs {
    pub arg: SessionCleanupLoopTimer,
}

impl From<SessionCleanupAgentLoopArgs> for super::Reducer {
    fn from(args: SessionCleanupAgentLoopArgs) -> Self {
        Self::SessionCleanupAgentLoop { arg: args.arg }
    }
}

impl __sdk::InModule for SessionCleanupAgentLoopArgs {
    type Module = super::RemoteModule;
}

pub struct SessionCleanupAgentLoopCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `session_cleanup_agent_loop`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait session_cleanup_agent_loop {
    /// Request that the remote module invoke the reducer `session_cleanup_agent_loop` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_session_cleanup_agent_loop`] callbacks.
    fn session_cleanup_agent_loop(&self, arg: SessionCleanupLoopTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `session_cleanup_agent_loop`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SessionCleanupAgentLoopCallbackId`] can be passed to [`Self::remove_on_session_cleanup_agent_loop`]
    /// to cancel the callback.
    fn on_session_cleanup_agent_loop(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &SessionCleanupLoopTimer) + Send + 'static,
    ) -> SessionCleanupAgentLoopCallbackId;
    /// Cancel a callback previously registered by [`Self::on_session_cleanup_agent_loop`],
    /// causing it not to run in the future.
    fn remove_on_session_cleanup_agent_loop(&self, callback: SessionCleanupAgentLoopCallbackId);
}

impl session_cleanup_agent_loop for super::RemoteReducers {
    fn session_cleanup_agent_loop(&self, arg: SessionCleanupLoopTimer) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "session_cleanup_agent_loop",
            SessionCleanupAgentLoopArgs { arg },
        )
    }
    fn on_session_cleanup_agent_loop(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &SessionCleanupLoopTimer) + Send + 'static,
    ) -> SessionCleanupAgentLoopCallbackId {
        SessionCleanupAgentLoopCallbackId(self.imp.on_reducer(
            "session_cleanup_agent_loop",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SessionCleanupAgentLoop { arg },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, arg)
            }),
        ))
    }
    fn remove_on_session_cleanup_agent_loop(&self, callback: SessionCleanupAgentLoopCallbackId) {
        self.imp
            .remove_on_reducer("session_cleanup_agent_loop", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `session_cleanup_agent_loop`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_session_cleanup_agent_loop {
    /// Set the call-reducer flags for the reducer `session_cleanup_agent_loop` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn session_cleanup_agent_loop(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_session_cleanup_agent_loop for super::SetReducerFlags {
    fn session_cleanup_agent_loop(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("session_cleanup_agent_loop", flags);
    }
}
