// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::skill_progress_type::SkillProgress;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `skill_progress`.
///
/// Obtain a handle from the [`SkillProgressTableAccess::skill_progress`] method on [`super::RemoteTables`],
/// like `ctx.db.skill_progress()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill_progress().on_insert(...)`.
pub struct SkillProgressTableHandle<'ctx> {
    imp: __sdk::TableHandle<SkillProgress>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `skill_progress`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SkillProgressTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SkillProgressTableHandle`], which mediates access to the table `skill_progress`.
    fn skill_progress(&self) -> SkillProgressTableHandle<'_>;
}

impl SkillProgressTableAccess for super::RemoteTables {
    fn skill_progress(&self) -> SkillProgressTableHandle<'_> {
        SkillProgressTableHandle {
            imp: self.imp.get_table::<SkillProgress>("skill_progress"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SkillProgressInsertCallbackId(__sdk::CallbackId);
pub struct SkillProgressDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SkillProgressTableHandle<'ctx> {
    type Row = SkillProgress;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SkillProgress> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SkillProgressInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillProgressInsertCallbackId {
        SkillProgressInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SkillProgressInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SkillProgressDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillProgressDeleteCallbackId {
        SkillProgressDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SkillProgressDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SkillProgress>("skill_progress");
    _table.add_unique_constraint::<String>("skill_key", |row| &row.skill_key);
}
pub struct SkillProgressUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SkillProgressTableHandle<'ctx> {
    type UpdateCallbackId = SkillProgressUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SkillProgressUpdateCallbackId {
        SkillProgressUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SkillProgressUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SkillProgress>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SkillProgress>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `skill_key` unique index on the table `skill_progress`,
/// which allows point queries on the field of the same name
/// via the [`SkillProgressSkillKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill_progress().skill_key().find(...)`.
pub struct SkillProgressSkillKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SkillProgress, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SkillProgressTableHandle<'ctx> {
    /// Get a handle on the `skill_key` unique index on the table `skill_progress`.
    pub fn skill_key(&self) -> SkillProgressSkillKeyUnique<'ctx> {
        SkillProgressSkillKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("skill_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SkillProgressSkillKeyUnique<'ctx> {
    /// Find the subscribed row whose `skill_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SkillProgress> {
        self.imp.find(col_val)
    }
}
