// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartWorldAgentsArgs {}

impl From<StartWorldAgentsArgs> for super::Reducer {
    fn from(args: StartWorldAgentsArgs) -> Self {
        Self::StartWorldAgents
    }
}

impl __sdk::InModule for StartWorldAgentsArgs {
    type Module = super::RemoteModule;
}

pub struct StartWorldAgentsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_world_agents`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_world_agents {
    /// Request that the remote module invoke the reducer `start_world_agents` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_start_world_agents`] callbacks.
    fn start_world_agents(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `start_world_agents`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`StartWorldAgentsCallbackId`] can be passed to [`Self::remove_on_start_world_agents`]
    /// to cancel the callback.
    fn on_start_world_agents(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> StartWorldAgentsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_start_world_agents`],
    /// causing it not to run in the future.
    fn remove_on_start_world_agents(&self, callback: StartWorldAgentsCallbackId);
}

impl start_world_agents for super::RemoteReducers {
    fn start_world_agents(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("start_world_agents", StartWorldAgentsArgs {})
    }
    fn on_start_world_agents(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> StartWorldAgentsCallbackId {
        StartWorldAgentsCallbackId(self.imp.on_reducer(
            "start_world_agents",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::StartWorldAgents {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_start_world_agents(&self, callback: StartWorldAgentsCallbackId) {
        self.imp.remove_on_reducer("start_world_agents", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `start_world_agents`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_start_world_agents {
    /// Set the call-reducer flags for the reducer `start_world_agents` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn start_world_agents(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_start_world_agents for super::SetReducerFlags {
    fn start_world_agents(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("start_world_agents", flags);
    }
}
