// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StatusEffect {
    pub status_key: String,
    pub entity_id: u64,
    pub effect_id: u64,
    pub stack: u16,
    pub expires_at: __sdk::Timestamp,
}

impl __sdk::InModule for StatusEffect {
    type Module = super::RemoteModule;
}
