// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tax_policy_type::TaxPolicy;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tax_policy`.
///
/// Obtain a handle from the [`TaxPolicyTableAccess::tax_policy`] method on [`super::RemoteTables`],
/// like `ctx.db.tax_policy()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tax_policy().on_insert(...)`.
pub struct TaxPolicyTableHandle<'ctx> {
    imp: __sdk::TableHandle<TaxPolicy>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tax_policy`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TaxPolicyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TaxPolicyTableHandle`], which mediates access to the table `tax_policy`.
    fn tax_policy(&self) -> TaxPolicyTableHandle<'_>;
}

impl TaxPolicyTableAccess for super::RemoteTables {
    fn tax_policy(&self) -> TaxPolicyTableHandle<'_> {
        TaxPolicyTableHandle {
            imp: self.imp.get_table::<TaxPolicy>("tax_policy"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TaxPolicyInsertCallbackId(__sdk::CallbackId);
pub struct TaxPolicyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TaxPolicyTableHandle<'ctx> {
    type Row = TaxPolicy;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TaxPolicy> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TaxPolicyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaxPolicyInsertCallbackId {
        TaxPolicyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TaxPolicyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TaxPolicyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaxPolicyDeleteCallbackId {
        TaxPolicyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TaxPolicyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TaxPolicy>("tax_policy");
    _table.add_unique_constraint::<u64>("item_def_id", |row| &row.item_def_id);
}
pub struct TaxPolicyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TaxPolicyTableHandle<'ctx> {
    type UpdateCallbackId = TaxPolicyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TaxPolicyUpdateCallbackId {
        TaxPolicyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TaxPolicyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TaxPolicy>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TaxPolicy>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `item_def_id` unique index on the table `tax_policy`,
/// which allows point queries on the field of the same name
/// via the [`TaxPolicyItemDefIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tax_policy().item_def_id().find(...)`.
pub struct TaxPolicyItemDefIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TaxPolicy, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TaxPolicyTableHandle<'ctx> {
    /// Get a handle on the `item_def_id` unique index on the table `tax_policy`.
    pub fn item_def_id(&self) -> TaxPolicyItemDefIdUnique<'ctx> {
        TaxPolicyItemDefIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("item_def_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TaxPolicyItemDefIdUnique<'ctx> {
    /// Find the subscribed row whose `item_def_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TaxPolicy> {
        self.imp.find(col_val)
    }
}
