// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TradeAcceptArgs {
    pub session_id: String,
    pub accepted: bool,
}

impl From<TradeAcceptArgs> for super::Reducer {
    fn from(args: TradeAcceptArgs) -> Self {
        Self::TradeAccept {
            session_id: args.session_id,
            accepted: args.accepted,
        }
    }
}

impl __sdk::InModule for TradeAcceptArgs {
    type Module = super::RemoteModule;
}

pub struct TradeAcceptCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `trade_accept`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait trade_accept {
    /// Request that the remote module invoke the reducer `trade_accept` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_trade_accept`] callbacks.
    fn trade_accept(&self, session_id: String, accepted: bool) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `trade_accept`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`TradeAcceptCallbackId`] can be passed to [`Self::remove_on_trade_accept`]
    /// to cancel the callback.
    fn on_trade_accept(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &bool) + Send + 'static,
    ) -> TradeAcceptCallbackId;
    /// Cancel a callback previously registered by [`Self::on_trade_accept`],
    /// causing it not to run in the future.
    fn remove_on_trade_accept(&self, callback: TradeAcceptCallbackId);
}

impl trade_accept for super::RemoteReducers {
    fn trade_accept(&self, session_id: String, accepted: bool) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "trade_accept",
            TradeAcceptArgs {
                session_id,
                accepted,
            },
        )
    }
    fn on_trade_accept(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &bool) + Send + 'static,
    ) -> TradeAcceptCallbackId {
        TradeAcceptCallbackId(self.imp.on_reducer(
            "trade_accept",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::TradeAccept {
                                    session_id,
                                    accepted,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, session_id, accepted)
            }),
        ))
    }
    fn remove_on_trade_accept(&self, callback: TradeAcceptCallbackId) {
        self.imp.remove_on_reducer("trade_accept", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `trade_accept`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_trade_accept {
    /// Set the call-reducer flags for the reducer `trade_accept` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn trade_accept(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_trade_accept for super::SetReducerFlags {
    fn trade_accept(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("trade_accept", flags);
    }
}
