// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnlockInventoryContainerArgs {
    pub container_id: u64,
}

impl From<UnlockInventoryContainerArgs> for super::Reducer {
    fn from(args: UnlockInventoryContainerArgs) -> Self {
        Self::UnlockInventoryContainer {
            container_id: args.container_id,
        }
    }
}

impl __sdk::InModule for UnlockInventoryContainerArgs {
    type Module = super::RemoteModule;
}

pub struct UnlockInventoryContainerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unlock_inventory_container`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unlock_inventory_container {
    /// Request that the remote module invoke the reducer `unlock_inventory_container` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_unlock_inventory_container`] callbacks.
    fn unlock_inventory_container(&self, container_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `unlock_inventory_container`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UnlockInventoryContainerCallbackId`] can be passed to [`Self::remove_on_unlock_inventory_container`]
    /// to cancel the callback.
    fn on_unlock_inventory_container(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> UnlockInventoryContainerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_unlock_inventory_container`],
    /// causing it not to run in the future.
    fn remove_on_unlock_inventory_container(&self, callback: UnlockInventoryContainerCallbackId);
}

impl unlock_inventory_container for super::RemoteReducers {
    fn unlock_inventory_container(&self, container_id: u64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "unlock_inventory_container",
            UnlockInventoryContainerArgs { container_id },
        )
    }
    fn on_unlock_inventory_container(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> UnlockInventoryContainerCallbackId {
        UnlockInventoryContainerCallbackId(self.imp.on_reducer(
            "unlock_inventory_container",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UnlockInventoryContainer { container_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, container_id)
            }),
        ))
    }
    fn remove_on_unlock_inventory_container(&self, callback: UnlockInventoryContainerCallbackId) {
        self.imp
            .remove_on_reducer("unlock_inventory_container", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `unlock_inventory_container`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_unlock_inventory_container {
    /// Set the call-reducer flags for the reducer `unlock_inventory_container` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn unlock_inventory_container(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_unlock_inventory_container for super::SetReducerFlags {
    fn unlock_inventory_container(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("unlock_inventory_container", flags);
    }
}
