// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  requestKey: __t.string().primaryKey().name("request_key"),
  identity: __t.identity(),
  requestId: __t.string().name("request_id"),
  regionId: __t.u64().name("region_id"),
  dimensionId: __t.u32().name("dimension_id"),
  buildingDefId: __t.u64().name("building_def_id"),
  hexX: __t.i32().name("hex_x"),
  hexZ: __t.i32().name("hex_z"),
  facing: __t.u8(),
  isValid: __t.bool().name("is_valid"),
  reasonCode: __t.string().name("reason_code"),
  checkedAt: __t.timestamp().name("checked_at"),
});
