// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  intentId: __t.string().primaryKey().name("intent_id"),
  attacker: __t.identity(),
  target: __t.identity(),
  regionId: __t.u64().name("region_id"),
  dimensionId: __t.u32().name("dimension_id"),
  frameNo: __t.u64().name("frame_no"),
  skillSlot: __t.u8().name("skill_slot"),
  clientTimeMs: __t.u64().name("client_time_ms"),
  submittedAt: __t.timestamp().name("submitted_at"),
});
