// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.u64().primaryKey().name("npc_id"),
  npcType: __t.u8().name("npc_type"),
  regionId: __t.u64().name("region_id"),
  dimensionId: __t.u32().name("dimension_id"),
  hexX: __t.i32().name("hex_x"),
  hexZ: __t.i32().name("hex_z"),
  destHexX: __t.i32().name("dest_hex_x"),
  destHexZ: __t.i32().name("dest_hex_z"),
  role: __t.u8(),
  mood: __t.u8(),
  traveling: __t.bool(),
  scheduleKind: __t.u8().name("schedule_kind"),
  nextActionTs: __t.u64().name("next_action_ts"),
  anchorEntityId: __t.u64().name("anchor_entity_id"),
  previousAnchors: __t.array(__t.u64()).name("previous_anchors"),
});
