// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  orderKey: __t.string().primaryKey().name("order_key"),
  npcId: __t.u64().name("npc_id"),
  npcType: __t.u8().name("npc_type"),
  orderDefId: __t.u64().name("order_def_id"),
  itemDefId: __t.u64().name("item_def_id"),
  side: __t.u8(),
  quantity: __t.u32(),
  unitPrice: __t.u64().name("unit_price"),
  status: __t.u8(),
  refreshAt: __t.u64().name("refresh_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
