// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  itemInstanceId: __t.u64().primaryKey().name("item_instance_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  containerId: __t.u64().name("container_id"),
  slotIndex: __t.u32().name("slot_index"),
  itemDefId: __t.u64().name("item_def_id"),
  quantity: __t.u32(),
  durability: __t.i32(),
  bound: __t.bool(),
});
