[package]
name = "stitch-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.18", default-features = false, features = [
    "std",
    "multi_threaded",
    "bevy_asset",
    "bevy_log",
    "bevy_state",
    "bevy_window",
    "bevy_winit",
    "bevy_render",
    "bevy_pbr",
    "bevy_core_pipeline",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_ui_render",
    "png",
    "x11",
    "wayland",
] }
spacetimedb-sdk = "=1.11.3"

[profile.dev]
debug = 0
codegen-units = 256
incremental = true
